// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package quant

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/quantcdn/pulumi-quant/sdk/go/quant/internal"
)

type Application struct {
	pulumi.CustomResourceState

	// Application name
	AppName pulumi.StringOutput `pulumi:"appName"`
	// Compose definition as a JSON string. Defines containers, CPU, memory, networking, and other task configuration.
	ComposeDefinition pulumi.StringOutput `pulumi:"composeDefinition"`
	// List of container names as a JSON array
	ContainerNames pulumi.StringOutput `pulumi:"containerNames"`
	// Database engine type (mysql, postgres)
	DatabaseEngine pulumi.StringOutput `pulumi:"databaseEngine"`
	// RDS instance class
	DatabaseInstanceClass pulumi.StringOutput `pulumi:"databaseInstanceClass"`
	// Enable Multi-AZ database deployment
	DatabaseMultiAz pulumi.BoolOutput `pulumi:"databaseMultiAz"`
	// Database allocated storage in GiB
	DatabaseStorageGb pulumi.IntOutput `pulumi:"databaseStorageGb"`
	// Desired task count
	DesiredCount pulumi.IntOutput `pulumi:"desiredCount"`
	// Initial environment variables as a JSON array of {name, value} objects
	Environment pulumi.StringOutput `pulumi:"environment"`
	// Mount path inside containers for the shared filesystem
	FilesystemMountPath pulumi.StringOutput `pulumi:"filesystemMountPath"`
	// Whether to create a shared filesystem
	FilesystemRequired pulumi.BoolOutput `pulumi:"filesystemRequired"`
	// Maximum task count for auto-scaling
	MaxCapacity pulumi.IntOutput `pulumi:"maxCapacity"`
	// Minimum task count for auto-scaling
	MinCapacity pulumi.IntOutput `pulumi:"minCapacity"`
	// Organization machine name. Defaults to the provider-level organization.
	Organization pulumi.StringOutput `pulumi:"organization"`
	// Currently running task count
	RunningCount pulumi.IntOutput `pulumi:"runningCount"`
	// Application status
	Status pulumi.StringOutput `pulumi:"status"`
}

// NewApplication registers a new resource with the given unique name, arguments, and options.
func NewApplication(ctx *pulumi.Context,
	name string, args *ApplicationArgs, opts ...pulumi.ResourceOption) (*Application, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.AppName == nil {
		return nil, errors.New("invalid value for required argument 'AppName'")
	}
	if args.ComposeDefinition == nil {
		return nil, errors.New("invalid value for required argument 'ComposeDefinition'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Application
	err := ctx.RegisterResource("quant:index:Application", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetApplication gets an existing Application resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetApplication(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ApplicationState, opts ...pulumi.ResourceOption) (*Application, error) {
	var resource Application
	err := ctx.ReadResource("quant:index:Application", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Application resources.
type applicationState struct {
	// Application name
	AppName *string `pulumi:"appName"`
	// Compose definition as a JSON string. Defines containers, CPU, memory, networking, and other task configuration.
	ComposeDefinition *string `pulumi:"composeDefinition"`
	// List of container names as a JSON array
	ContainerNames *string `pulumi:"containerNames"`
	// Database engine type (mysql, postgres)
	DatabaseEngine *string `pulumi:"databaseEngine"`
	// RDS instance class
	DatabaseInstanceClass *string `pulumi:"databaseInstanceClass"`
	// Enable Multi-AZ database deployment
	DatabaseMultiAz *bool `pulumi:"databaseMultiAz"`
	// Database allocated storage in GiB
	DatabaseStorageGb *int `pulumi:"databaseStorageGb"`
	// Desired task count
	DesiredCount *int `pulumi:"desiredCount"`
	// Initial environment variables as a JSON array of {name, value} objects
	Environment *string `pulumi:"environment"`
	// Mount path inside containers for the shared filesystem
	FilesystemMountPath *string `pulumi:"filesystemMountPath"`
	// Whether to create a shared filesystem
	FilesystemRequired *bool `pulumi:"filesystemRequired"`
	// Maximum task count for auto-scaling
	MaxCapacity *int `pulumi:"maxCapacity"`
	// Minimum task count for auto-scaling
	MinCapacity *int `pulumi:"minCapacity"`
	// Organization machine name. Defaults to the provider-level organization.
	Organization *string `pulumi:"organization"`
	// Currently running task count
	RunningCount *int `pulumi:"runningCount"`
	// Application status
	Status *string `pulumi:"status"`
}

type ApplicationState struct {
	// Application name
	AppName pulumi.StringPtrInput
	// Compose definition as a JSON string. Defines containers, CPU, memory, networking, and other task configuration.
	ComposeDefinition pulumi.StringPtrInput
	// List of container names as a JSON array
	ContainerNames pulumi.StringPtrInput
	// Database engine type (mysql, postgres)
	DatabaseEngine pulumi.StringPtrInput
	// RDS instance class
	DatabaseInstanceClass pulumi.StringPtrInput
	// Enable Multi-AZ database deployment
	DatabaseMultiAz pulumi.BoolPtrInput
	// Database allocated storage in GiB
	DatabaseStorageGb pulumi.IntPtrInput
	// Desired task count
	DesiredCount pulumi.IntPtrInput
	// Initial environment variables as a JSON array of {name, value} objects
	Environment pulumi.StringPtrInput
	// Mount path inside containers for the shared filesystem
	FilesystemMountPath pulumi.StringPtrInput
	// Whether to create a shared filesystem
	FilesystemRequired pulumi.BoolPtrInput
	// Maximum task count for auto-scaling
	MaxCapacity pulumi.IntPtrInput
	// Minimum task count for auto-scaling
	MinCapacity pulumi.IntPtrInput
	// Organization machine name. Defaults to the provider-level organization.
	Organization pulumi.StringPtrInput
	// Currently running task count
	RunningCount pulumi.IntPtrInput
	// Application status
	Status pulumi.StringPtrInput
}

func (ApplicationState) ElementType() reflect.Type {
	return reflect.TypeOf((*applicationState)(nil)).Elem()
}

type applicationArgs struct {
	// Application name
	AppName string `pulumi:"appName"`
	// Compose definition as a JSON string. Defines containers, CPU, memory, networking, and other task configuration.
	ComposeDefinition string `pulumi:"composeDefinition"`
	// Database engine type (mysql, postgres)
	DatabaseEngine *string `pulumi:"databaseEngine"`
	// RDS instance class
	DatabaseInstanceClass *string `pulumi:"databaseInstanceClass"`
	// Enable Multi-AZ database deployment
	DatabaseMultiAz *bool `pulumi:"databaseMultiAz"`
	// Database allocated storage in GiB
	DatabaseStorageGb *int `pulumi:"databaseStorageGb"`
	// Initial environment variables as a JSON array of {name, value} objects
	Environment *string `pulumi:"environment"`
	// Mount path inside containers for the shared filesystem
	FilesystemMountPath *string `pulumi:"filesystemMountPath"`
	// Whether to create a shared filesystem
	FilesystemRequired *bool `pulumi:"filesystemRequired"`
	// Maximum task count for auto-scaling
	MaxCapacity *int `pulumi:"maxCapacity"`
	// Minimum task count for auto-scaling
	MinCapacity *int `pulumi:"minCapacity"`
	// Organization machine name. Defaults to the provider-level organization.
	Organization *string `pulumi:"organization"`
}

// The set of arguments for constructing a Application resource.
type ApplicationArgs struct {
	// Application name
	AppName pulumi.StringInput
	// Compose definition as a JSON string. Defines containers, CPU, memory, networking, and other task configuration.
	ComposeDefinition pulumi.StringInput
	// Database engine type (mysql, postgres)
	DatabaseEngine pulumi.StringPtrInput
	// RDS instance class
	DatabaseInstanceClass pulumi.StringPtrInput
	// Enable Multi-AZ database deployment
	DatabaseMultiAz pulumi.BoolPtrInput
	// Database allocated storage in GiB
	DatabaseStorageGb pulumi.IntPtrInput
	// Initial environment variables as a JSON array of {name, value} objects
	Environment pulumi.StringPtrInput
	// Mount path inside containers for the shared filesystem
	FilesystemMountPath pulumi.StringPtrInput
	// Whether to create a shared filesystem
	FilesystemRequired pulumi.BoolPtrInput
	// Maximum task count for auto-scaling
	MaxCapacity pulumi.IntPtrInput
	// Minimum task count for auto-scaling
	MinCapacity pulumi.IntPtrInput
	// Organization machine name. Defaults to the provider-level organization.
	Organization pulumi.StringPtrInput
}

func (ApplicationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*applicationArgs)(nil)).Elem()
}

type ApplicationInput interface {
	pulumi.Input

	ToApplicationOutput() ApplicationOutput
	ToApplicationOutputWithContext(ctx context.Context) ApplicationOutput
}

func (*Application) ElementType() reflect.Type {
	return reflect.TypeOf((**Application)(nil)).Elem()
}

func (i *Application) ToApplicationOutput() ApplicationOutput {
	return i.ToApplicationOutputWithContext(context.Background())
}

func (i *Application) ToApplicationOutputWithContext(ctx context.Context) ApplicationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationOutput)
}

// ApplicationArrayInput is an input type that accepts ApplicationArray and ApplicationArrayOutput values.
// You can construct a concrete instance of `ApplicationArrayInput` via:
//
//	ApplicationArray{ ApplicationArgs{...} }
type ApplicationArrayInput interface {
	pulumi.Input

	ToApplicationArrayOutput() ApplicationArrayOutput
	ToApplicationArrayOutputWithContext(context.Context) ApplicationArrayOutput
}

type ApplicationArray []ApplicationInput

func (ApplicationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Application)(nil)).Elem()
}

func (i ApplicationArray) ToApplicationArrayOutput() ApplicationArrayOutput {
	return i.ToApplicationArrayOutputWithContext(context.Background())
}

func (i ApplicationArray) ToApplicationArrayOutputWithContext(ctx context.Context) ApplicationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationArrayOutput)
}

// ApplicationMapInput is an input type that accepts ApplicationMap and ApplicationMapOutput values.
// You can construct a concrete instance of `ApplicationMapInput` via:
//
//	ApplicationMap{ "key": ApplicationArgs{...} }
type ApplicationMapInput interface {
	pulumi.Input

	ToApplicationMapOutput() ApplicationMapOutput
	ToApplicationMapOutputWithContext(context.Context) ApplicationMapOutput
}

type ApplicationMap map[string]ApplicationInput

func (ApplicationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Application)(nil)).Elem()
}

func (i ApplicationMap) ToApplicationMapOutput() ApplicationMapOutput {
	return i.ToApplicationMapOutputWithContext(context.Background())
}

func (i ApplicationMap) ToApplicationMapOutputWithContext(ctx context.Context) ApplicationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApplicationMapOutput)
}

type ApplicationOutput struct{ *pulumi.OutputState }

func (ApplicationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Application)(nil)).Elem()
}

func (o ApplicationOutput) ToApplicationOutput() ApplicationOutput {
	return o
}

func (o ApplicationOutput) ToApplicationOutputWithContext(ctx context.Context) ApplicationOutput {
	return o
}

// Application name
func (o ApplicationOutput) AppName() pulumi.StringOutput {
	return o.ApplyT(func(v *Application) pulumi.StringOutput { return v.AppName }).(pulumi.StringOutput)
}

// Compose definition as a JSON string. Defines containers, CPU, memory, networking, and other task configuration.
func (o ApplicationOutput) ComposeDefinition() pulumi.StringOutput {
	return o.ApplyT(func(v *Application) pulumi.StringOutput { return v.ComposeDefinition }).(pulumi.StringOutput)
}

// List of container names as a JSON array
func (o ApplicationOutput) ContainerNames() pulumi.StringOutput {
	return o.ApplyT(func(v *Application) pulumi.StringOutput { return v.ContainerNames }).(pulumi.StringOutput)
}

// Database engine type (mysql, postgres)
func (o ApplicationOutput) DatabaseEngine() pulumi.StringOutput {
	return o.ApplyT(func(v *Application) pulumi.StringOutput { return v.DatabaseEngine }).(pulumi.StringOutput)
}

// RDS instance class
func (o ApplicationOutput) DatabaseInstanceClass() pulumi.StringOutput {
	return o.ApplyT(func(v *Application) pulumi.StringOutput { return v.DatabaseInstanceClass }).(pulumi.StringOutput)
}

// Enable Multi-AZ database deployment
func (o ApplicationOutput) DatabaseMultiAz() pulumi.BoolOutput {
	return o.ApplyT(func(v *Application) pulumi.BoolOutput { return v.DatabaseMultiAz }).(pulumi.BoolOutput)
}

// Database allocated storage in GiB
func (o ApplicationOutput) DatabaseStorageGb() pulumi.IntOutput {
	return o.ApplyT(func(v *Application) pulumi.IntOutput { return v.DatabaseStorageGb }).(pulumi.IntOutput)
}

// Desired task count
func (o ApplicationOutput) DesiredCount() pulumi.IntOutput {
	return o.ApplyT(func(v *Application) pulumi.IntOutput { return v.DesiredCount }).(pulumi.IntOutput)
}

// Initial environment variables as a JSON array of {name, value} objects
func (o ApplicationOutput) Environment() pulumi.StringOutput {
	return o.ApplyT(func(v *Application) pulumi.StringOutput { return v.Environment }).(pulumi.StringOutput)
}

// Mount path inside containers for the shared filesystem
func (o ApplicationOutput) FilesystemMountPath() pulumi.StringOutput {
	return o.ApplyT(func(v *Application) pulumi.StringOutput { return v.FilesystemMountPath }).(pulumi.StringOutput)
}

// Whether to create a shared filesystem
func (o ApplicationOutput) FilesystemRequired() pulumi.BoolOutput {
	return o.ApplyT(func(v *Application) pulumi.BoolOutput { return v.FilesystemRequired }).(pulumi.BoolOutput)
}

// Maximum task count for auto-scaling
func (o ApplicationOutput) MaxCapacity() pulumi.IntOutput {
	return o.ApplyT(func(v *Application) pulumi.IntOutput { return v.MaxCapacity }).(pulumi.IntOutput)
}

// Minimum task count for auto-scaling
func (o ApplicationOutput) MinCapacity() pulumi.IntOutput {
	return o.ApplyT(func(v *Application) pulumi.IntOutput { return v.MinCapacity }).(pulumi.IntOutput)
}

// Organization machine name. Defaults to the provider-level organization.
func (o ApplicationOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v *Application) pulumi.StringOutput { return v.Organization }).(pulumi.StringOutput)
}

// Currently running task count
func (o ApplicationOutput) RunningCount() pulumi.IntOutput {
	return o.ApplyT(func(v *Application) pulumi.IntOutput { return v.RunningCount }).(pulumi.IntOutput)
}

// Application status
func (o ApplicationOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *Application) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

type ApplicationArrayOutput struct{ *pulumi.OutputState }

func (ApplicationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Application)(nil)).Elem()
}

func (o ApplicationArrayOutput) ToApplicationArrayOutput() ApplicationArrayOutput {
	return o
}

func (o ApplicationArrayOutput) ToApplicationArrayOutputWithContext(ctx context.Context) ApplicationArrayOutput {
	return o
}

func (o ApplicationArrayOutput) Index(i pulumi.IntInput) ApplicationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Application {
		return vs[0].([]*Application)[vs[1].(int)]
	}).(ApplicationOutput)
}

type ApplicationMapOutput struct{ *pulumi.OutputState }

func (ApplicationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Application)(nil)).Elem()
}

func (o ApplicationMapOutput) ToApplicationMapOutput() ApplicationMapOutput {
	return o
}

func (o ApplicationMapOutput) ToApplicationMapOutputWithContext(ctx context.Context) ApplicationMapOutput {
	return o
}

func (o ApplicationMapOutput) MapIndex(k pulumi.StringInput) ApplicationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Application {
		return vs[0].(map[string]*Application)[vs[1].(string)]
	}).(ApplicationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationInput)(nil)).Elem(), &Application{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationArrayInput)(nil)).Elem(), ApplicationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationMapInput)(nil)).Elem(), ApplicationMap{})
	pulumi.RegisterOutputType(ApplicationOutput{})
	pulumi.RegisterOutputType(ApplicationArrayOutput{})
	pulumi.RegisterOutputType(ApplicationMapOutput{})
}
