// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package quant

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/quantcdn/pulumi-quant/sdk/go/quant/internal"
)

type KvItem struct {
	pulumi.CustomResourceState

	// Item key
	Key pulumi.StringOutput `pulumi:"key"`
	// Organization machine name (defaults to provider organization)
	Organization pulumi.StringOutput `pulumi:"organization"`
	// Project machine name
	Project pulumi.StringOutput `pulumi:"project"`
	// Store as secret with KMS encryption
	Secret pulumi.BoolOutput `pulumi:"secret"`
	// KV store ID
	StoreId pulumi.StringOutput `pulumi:"storeId"`
	// Item value (can be a JSON string)
	Value pulumi.StringOutput `pulumi:"value"`
}

// NewKvItem registers a new resource with the given unique name, arguments, and options.
func NewKvItem(ctx *pulumi.Context,
	name string, args *KvItemArgs, opts ...pulumi.ResourceOption) (*KvItem, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Key == nil {
		return nil, errors.New("invalid value for required argument 'Key'")
	}
	if args.Project == nil {
		return nil, errors.New("invalid value for required argument 'Project'")
	}
	if args.StoreId == nil {
		return nil, errors.New("invalid value for required argument 'StoreId'")
	}
	if args.Value == nil {
		return nil, errors.New("invalid value for required argument 'Value'")
	}
	if args.Value != nil {
		args.Value = pulumi.ToSecret(args.Value).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"value",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource KvItem
	err := ctx.RegisterResource("quant:index:KvItem", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetKvItem gets an existing KvItem resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetKvItem(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *KvItemState, opts ...pulumi.ResourceOption) (*KvItem, error) {
	var resource KvItem
	err := ctx.ReadResource("quant:index:KvItem", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering KvItem resources.
type kvItemState struct {
	// Item key
	Key *string `pulumi:"key"`
	// Organization machine name (defaults to provider organization)
	Organization *string `pulumi:"organization"`
	// Project machine name
	Project *string `pulumi:"project"`
	// Store as secret with KMS encryption
	Secret *bool `pulumi:"secret"`
	// KV store ID
	StoreId *string `pulumi:"storeId"`
	// Item value (can be a JSON string)
	Value *string `pulumi:"value"`
}

type KvItemState struct {
	// Item key
	Key pulumi.StringPtrInput
	// Organization machine name (defaults to provider organization)
	Organization pulumi.StringPtrInput
	// Project machine name
	Project pulumi.StringPtrInput
	// Store as secret with KMS encryption
	Secret pulumi.BoolPtrInput
	// KV store ID
	StoreId pulumi.StringPtrInput
	// Item value (can be a JSON string)
	Value pulumi.StringPtrInput
}

func (KvItemState) ElementType() reflect.Type {
	return reflect.TypeOf((*kvItemState)(nil)).Elem()
}

type kvItemArgs struct {
	// Item key
	Key string `pulumi:"key"`
	// Organization machine name (defaults to provider organization)
	Organization *string `pulumi:"organization"`
	// Project machine name
	Project string `pulumi:"project"`
	// Store as secret with KMS encryption
	Secret *bool `pulumi:"secret"`
	// KV store ID
	StoreId string `pulumi:"storeId"`
	// Item value (can be a JSON string)
	Value string `pulumi:"value"`
}

// The set of arguments for constructing a KvItem resource.
type KvItemArgs struct {
	// Item key
	Key pulumi.StringInput
	// Organization machine name (defaults to provider organization)
	Organization pulumi.StringPtrInput
	// Project machine name
	Project pulumi.StringInput
	// Store as secret with KMS encryption
	Secret pulumi.BoolPtrInput
	// KV store ID
	StoreId pulumi.StringInput
	// Item value (can be a JSON string)
	Value pulumi.StringInput
}

func (KvItemArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*kvItemArgs)(nil)).Elem()
}

type KvItemInput interface {
	pulumi.Input

	ToKvItemOutput() KvItemOutput
	ToKvItemOutputWithContext(ctx context.Context) KvItemOutput
}

func (*KvItem) ElementType() reflect.Type {
	return reflect.TypeOf((**KvItem)(nil)).Elem()
}

func (i *KvItem) ToKvItemOutput() KvItemOutput {
	return i.ToKvItemOutputWithContext(context.Background())
}

func (i *KvItem) ToKvItemOutputWithContext(ctx context.Context) KvItemOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KvItemOutput)
}

// KvItemArrayInput is an input type that accepts KvItemArray and KvItemArrayOutput values.
// You can construct a concrete instance of `KvItemArrayInput` via:
//
//	KvItemArray{ KvItemArgs{...} }
type KvItemArrayInput interface {
	pulumi.Input

	ToKvItemArrayOutput() KvItemArrayOutput
	ToKvItemArrayOutputWithContext(context.Context) KvItemArrayOutput
}

type KvItemArray []KvItemInput

func (KvItemArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KvItem)(nil)).Elem()
}

func (i KvItemArray) ToKvItemArrayOutput() KvItemArrayOutput {
	return i.ToKvItemArrayOutputWithContext(context.Background())
}

func (i KvItemArray) ToKvItemArrayOutputWithContext(ctx context.Context) KvItemArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KvItemArrayOutput)
}

// KvItemMapInput is an input type that accepts KvItemMap and KvItemMapOutput values.
// You can construct a concrete instance of `KvItemMapInput` via:
//
//	KvItemMap{ "key": KvItemArgs{...} }
type KvItemMapInput interface {
	pulumi.Input

	ToKvItemMapOutput() KvItemMapOutput
	ToKvItemMapOutputWithContext(context.Context) KvItemMapOutput
}

type KvItemMap map[string]KvItemInput

func (KvItemMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KvItem)(nil)).Elem()
}

func (i KvItemMap) ToKvItemMapOutput() KvItemMapOutput {
	return i.ToKvItemMapOutputWithContext(context.Background())
}

func (i KvItemMap) ToKvItemMapOutputWithContext(ctx context.Context) KvItemMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KvItemMapOutput)
}

type KvItemOutput struct{ *pulumi.OutputState }

func (KvItemOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KvItem)(nil)).Elem()
}

func (o KvItemOutput) ToKvItemOutput() KvItemOutput {
	return o
}

func (o KvItemOutput) ToKvItemOutputWithContext(ctx context.Context) KvItemOutput {
	return o
}

// Item key
func (o KvItemOutput) Key() pulumi.StringOutput {
	return o.ApplyT(func(v *KvItem) pulumi.StringOutput { return v.Key }).(pulumi.StringOutput)
}

// Organization machine name (defaults to provider organization)
func (o KvItemOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v *KvItem) pulumi.StringOutput { return v.Organization }).(pulumi.StringOutput)
}

// Project machine name
func (o KvItemOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *KvItem) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// Store as secret with KMS encryption
func (o KvItemOutput) Secret() pulumi.BoolOutput {
	return o.ApplyT(func(v *KvItem) pulumi.BoolOutput { return v.Secret }).(pulumi.BoolOutput)
}

// KV store ID
func (o KvItemOutput) StoreId() pulumi.StringOutput {
	return o.ApplyT(func(v *KvItem) pulumi.StringOutput { return v.StoreId }).(pulumi.StringOutput)
}

// Item value (can be a JSON string)
func (o KvItemOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v *KvItem) pulumi.StringOutput { return v.Value }).(pulumi.StringOutput)
}

type KvItemArrayOutput struct{ *pulumi.OutputState }

func (KvItemArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KvItem)(nil)).Elem()
}

func (o KvItemArrayOutput) ToKvItemArrayOutput() KvItemArrayOutput {
	return o
}

func (o KvItemArrayOutput) ToKvItemArrayOutputWithContext(ctx context.Context) KvItemArrayOutput {
	return o
}

func (o KvItemArrayOutput) Index(i pulumi.IntInput) KvItemOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *KvItem {
		return vs[0].([]*KvItem)[vs[1].(int)]
	}).(KvItemOutput)
}

type KvItemMapOutput struct{ *pulumi.OutputState }

func (KvItemMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KvItem)(nil)).Elem()
}

func (o KvItemMapOutput) ToKvItemMapOutput() KvItemMapOutput {
	return o
}

func (o KvItemMapOutput) ToKvItemMapOutputWithContext(ctx context.Context) KvItemMapOutput {
	return o
}

func (o KvItemMapOutput) MapIndex(k pulumi.StringInput) KvItemOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *KvItem {
		return vs[0].(map[string]*KvItem)[vs[1].(string)]
	}).(KvItemOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*KvItemInput)(nil)).Elem(), &KvItem{})
	pulumi.RegisterInputType(reflect.TypeOf((*KvItemArrayInput)(nil)).Elem(), KvItemArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*KvItemMapInput)(nil)).Elem(), KvItemMap{})
	pulumi.RegisterOutputType(KvItemOutput{})
	pulumi.RegisterOutputType(KvItemArrayOutput{})
	pulumi.RegisterOutputType(KvItemMapOutput{})
}
