// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package quant

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/quantcdn/pulumi-quant/sdk/go/quant/internal"
)

type KvStore struct {
	pulumi.CustomResourceState

	// Store name
	Name pulumi.StringOutput `pulumi:"name"`
	// Organization machine name (defaults to provider organization)
	Organization pulumi.StringOutput `pulumi:"organization"`
	// Project machine name
	Project pulumi.StringOutput `pulumi:"project"`
	// Store ID
	StoreId pulumi.StringOutput `pulumi:"storeId"`
}

// NewKvStore registers a new resource with the given unique name, arguments, and options.
func NewKvStore(ctx *pulumi.Context,
	name string, args *KvStoreArgs, opts ...pulumi.ResourceOption) (*KvStore, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Project == nil {
		return nil, errors.New("invalid value for required argument 'Project'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource KvStore
	err := ctx.RegisterResource("quant:index:KvStore", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetKvStore gets an existing KvStore resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetKvStore(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *KvStoreState, opts ...pulumi.ResourceOption) (*KvStore, error) {
	var resource KvStore
	err := ctx.ReadResource("quant:index:KvStore", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering KvStore resources.
type kvStoreState struct {
	// Store name
	Name *string `pulumi:"name"`
	// Organization machine name (defaults to provider organization)
	Organization *string `pulumi:"organization"`
	// Project machine name
	Project *string `pulumi:"project"`
	// Store ID
	StoreId *string `pulumi:"storeId"`
}

type KvStoreState struct {
	// Store name
	Name pulumi.StringPtrInput
	// Organization machine name (defaults to provider organization)
	Organization pulumi.StringPtrInput
	// Project machine name
	Project pulumi.StringPtrInput
	// Store ID
	StoreId pulumi.StringPtrInput
}

func (KvStoreState) ElementType() reflect.Type {
	return reflect.TypeOf((*kvStoreState)(nil)).Elem()
}

type kvStoreArgs struct {
	// Store name
	Name *string `pulumi:"name"`
	// Organization machine name (defaults to provider organization)
	Organization *string `pulumi:"organization"`
	// Project machine name
	Project string `pulumi:"project"`
}

// The set of arguments for constructing a KvStore resource.
type KvStoreArgs struct {
	// Store name
	Name pulumi.StringPtrInput
	// Organization machine name (defaults to provider organization)
	Organization pulumi.StringPtrInput
	// Project machine name
	Project pulumi.StringInput
}

func (KvStoreArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*kvStoreArgs)(nil)).Elem()
}

type KvStoreInput interface {
	pulumi.Input

	ToKvStoreOutput() KvStoreOutput
	ToKvStoreOutputWithContext(ctx context.Context) KvStoreOutput
}

func (*KvStore) ElementType() reflect.Type {
	return reflect.TypeOf((**KvStore)(nil)).Elem()
}

func (i *KvStore) ToKvStoreOutput() KvStoreOutput {
	return i.ToKvStoreOutputWithContext(context.Background())
}

func (i *KvStore) ToKvStoreOutputWithContext(ctx context.Context) KvStoreOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KvStoreOutput)
}

// KvStoreArrayInput is an input type that accepts KvStoreArray and KvStoreArrayOutput values.
// You can construct a concrete instance of `KvStoreArrayInput` via:
//
//	KvStoreArray{ KvStoreArgs{...} }
type KvStoreArrayInput interface {
	pulumi.Input

	ToKvStoreArrayOutput() KvStoreArrayOutput
	ToKvStoreArrayOutputWithContext(context.Context) KvStoreArrayOutput
}

type KvStoreArray []KvStoreInput

func (KvStoreArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KvStore)(nil)).Elem()
}

func (i KvStoreArray) ToKvStoreArrayOutput() KvStoreArrayOutput {
	return i.ToKvStoreArrayOutputWithContext(context.Background())
}

func (i KvStoreArray) ToKvStoreArrayOutputWithContext(ctx context.Context) KvStoreArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KvStoreArrayOutput)
}

// KvStoreMapInput is an input type that accepts KvStoreMap and KvStoreMapOutput values.
// You can construct a concrete instance of `KvStoreMapInput` via:
//
//	KvStoreMap{ "key": KvStoreArgs{...} }
type KvStoreMapInput interface {
	pulumi.Input

	ToKvStoreMapOutput() KvStoreMapOutput
	ToKvStoreMapOutputWithContext(context.Context) KvStoreMapOutput
}

type KvStoreMap map[string]KvStoreInput

func (KvStoreMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KvStore)(nil)).Elem()
}

func (i KvStoreMap) ToKvStoreMapOutput() KvStoreMapOutput {
	return i.ToKvStoreMapOutputWithContext(context.Background())
}

func (i KvStoreMap) ToKvStoreMapOutputWithContext(ctx context.Context) KvStoreMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(KvStoreMapOutput)
}

type KvStoreOutput struct{ *pulumi.OutputState }

func (KvStoreOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**KvStore)(nil)).Elem()
}

func (o KvStoreOutput) ToKvStoreOutput() KvStoreOutput {
	return o
}

func (o KvStoreOutput) ToKvStoreOutputWithContext(ctx context.Context) KvStoreOutput {
	return o
}

// Store name
func (o KvStoreOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *KvStore) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Organization machine name (defaults to provider organization)
func (o KvStoreOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v *KvStore) pulumi.StringOutput { return v.Organization }).(pulumi.StringOutput)
}

// Project machine name
func (o KvStoreOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v *KvStore) pulumi.StringOutput { return v.Project }).(pulumi.StringOutput)
}

// Store ID
func (o KvStoreOutput) StoreId() pulumi.StringOutput {
	return o.ApplyT(func(v *KvStore) pulumi.StringOutput { return v.StoreId }).(pulumi.StringOutput)
}

type KvStoreArrayOutput struct{ *pulumi.OutputState }

func (KvStoreArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*KvStore)(nil)).Elem()
}

func (o KvStoreArrayOutput) ToKvStoreArrayOutput() KvStoreArrayOutput {
	return o
}

func (o KvStoreArrayOutput) ToKvStoreArrayOutputWithContext(ctx context.Context) KvStoreArrayOutput {
	return o
}

func (o KvStoreArrayOutput) Index(i pulumi.IntInput) KvStoreOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *KvStore {
		return vs[0].([]*KvStore)[vs[1].(int)]
	}).(KvStoreOutput)
}

type KvStoreMapOutput struct{ *pulumi.OutputState }

func (KvStoreMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*KvStore)(nil)).Elem()
}

func (o KvStoreMapOutput) ToKvStoreMapOutput() KvStoreMapOutput {
	return o
}

func (o KvStoreMapOutput) ToKvStoreMapOutputWithContext(ctx context.Context) KvStoreMapOutput {
	return o
}

func (o KvStoreMapOutput) MapIndex(k pulumi.StringInput) KvStoreOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *KvStore {
		return vs[0].(map[string]*KvStore)[vs[1].(string)]
	}).(KvStoreOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*KvStoreInput)(nil)).Elem(), &KvStore{})
	pulumi.RegisterInputType(reflect.TypeOf((*KvStoreArrayInput)(nil)).Elem(), KvStoreArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*KvStoreMapInput)(nil)).Elem(), KvStoreMap{})
	pulumi.RegisterOutputType(KvStoreOutput{})
	pulumi.RegisterOutputType(KvStoreArrayOutput{})
	pulumi.RegisterOutputType(KvStoreMapOutput{})
}
