// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package quant

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/quantcdn/pulumi-quant/sdk/go/quant/internal"
)

type Volume struct {
	pulumi.CustomResourceState

	// EFS access point ARN
	AccessPointArn pulumi.StringOutput `pulumi:"accessPointArn"`
	// EFS access point ID
	AccessPointId pulumi.StringOutput `pulumi:"accessPointId"`
	// Application name
	Application pulumi.StringOutput `pulumi:"application"`
	// Creation timestamp
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Volume description
	Description pulumi.StringOutput `pulumi:"description"`
	// Environment name
	Environment pulumi.StringOutput `pulumi:"environment"`
	// EFS filesystem ID
	EnvironmentEfsId pulumi.StringOutput `pulumi:"environmentEfsId"`
	// Organization machine name (defaults to provider organization)
	Organization pulumi.StringOutput `pulumi:"organization"`
	// Root directory path
	RootDirectory pulumi.StringOutput `pulumi:"rootDirectory"`
	// Volume ID
	VolumeId pulumi.StringOutput `pulumi:"volumeId"`
	// Volume name
	VolumeName pulumi.StringOutput `pulumi:"volumeName"`
}

// NewVolume registers a new resource with the given unique name, arguments, and options.
func NewVolume(ctx *pulumi.Context,
	name string, args *VolumeArgs, opts ...pulumi.ResourceOption) (*Volume, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Application == nil {
		return nil, errors.New("invalid value for required argument 'Application'")
	}
	if args.Environment == nil {
		return nil, errors.New("invalid value for required argument 'Environment'")
	}
	if args.VolumeName == nil {
		return nil, errors.New("invalid value for required argument 'VolumeName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Volume
	err := ctx.RegisterResource("quant:index:Volume", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVolume gets an existing Volume resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVolume(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VolumeState, opts ...pulumi.ResourceOption) (*Volume, error) {
	var resource Volume
	err := ctx.ReadResource("quant:index:Volume", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Volume resources.
type volumeState struct {
	// EFS access point ARN
	AccessPointArn *string `pulumi:"accessPointArn"`
	// EFS access point ID
	AccessPointId *string `pulumi:"accessPointId"`
	// Application name
	Application *string `pulumi:"application"`
	// Creation timestamp
	CreatedAt *string `pulumi:"createdAt"`
	// Volume description
	Description *string `pulumi:"description"`
	// Environment name
	Environment *string `pulumi:"environment"`
	// EFS filesystem ID
	EnvironmentEfsId *string `pulumi:"environmentEfsId"`
	// Organization machine name (defaults to provider organization)
	Organization *string `pulumi:"organization"`
	// Root directory path
	RootDirectory *string `pulumi:"rootDirectory"`
	// Volume ID
	VolumeId *string `pulumi:"volumeId"`
	// Volume name
	VolumeName *string `pulumi:"volumeName"`
}

type VolumeState struct {
	// EFS access point ARN
	AccessPointArn pulumi.StringPtrInput
	// EFS access point ID
	AccessPointId pulumi.StringPtrInput
	// Application name
	Application pulumi.StringPtrInput
	// Creation timestamp
	CreatedAt pulumi.StringPtrInput
	// Volume description
	Description pulumi.StringPtrInput
	// Environment name
	Environment pulumi.StringPtrInput
	// EFS filesystem ID
	EnvironmentEfsId pulumi.StringPtrInput
	// Organization machine name (defaults to provider organization)
	Organization pulumi.StringPtrInput
	// Root directory path
	RootDirectory pulumi.StringPtrInput
	// Volume ID
	VolumeId pulumi.StringPtrInput
	// Volume name
	VolumeName pulumi.StringPtrInput
}

func (VolumeState) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeState)(nil)).Elem()
}

type volumeArgs struct {
	// Application name
	Application string `pulumi:"application"`
	// Volume description
	Description *string `pulumi:"description"`
	// Environment name
	Environment string `pulumi:"environment"`
	// Organization machine name (defaults to provider organization)
	Organization *string `pulumi:"organization"`
	// Root directory path
	RootDirectory *string `pulumi:"rootDirectory"`
	// Volume name
	VolumeName string `pulumi:"volumeName"`
}

// The set of arguments for constructing a Volume resource.
type VolumeArgs struct {
	// Application name
	Application pulumi.StringInput
	// Volume description
	Description pulumi.StringPtrInput
	// Environment name
	Environment pulumi.StringInput
	// Organization machine name (defaults to provider organization)
	Organization pulumi.StringPtrInput
	// Root directory path
	RootDirectory pulumi.StringPtrInput
	// Volume name
	VolumeName pulumi.StringInput
}

func (VolumeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*volumeArgs)(nil)).Elem()
}

type VolumeInput interface {
	pulumi.Input

	ToVolumeOutput() VolumeOutput
	ToVolumeOutputWithContext(ctx context.Context) VolumeOutput
}

func (*Volume) ElementType() reflect.Type {
	return reflect.TypeOf((**Volume)(nil)).Elem()
}

func (i *Volume) ToVolumeOutput() VolumeOutput {
	return i.ToVolumeOutputWithContext(context.Background())
}

func (i *Volume) ToVolumeOutputWithContext(ctx context.Context) VolumeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeOutput)
}

// VolumeArrayInput is an input type that accepts VolumeArray and VolumeArrayOutput values.
// You can construct a concrete instance of `VolumeArrayInput` via:
//
//	VolumeArray{ VolumeArgs{...} }
type VolumeArrayInput interface {
	pulumi.Input

	ToVolumeArrayOutput() VolumeArrayOutput
	ToVolumeArrayOutputWithContext(context.Context) VolumeArrayOutput
}

type VolumeArray []VolumeInput

func (VolumeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Volume)(nil)).Elem()
}

func (i VolumeArray) ToVolumeArrayOutput() VolumeArrayOutput {
	return i.ToVolumeArrayOutputWithContext(context.Background())
}

func (i VolumeArray) ToVolumeArrayOutputWithContext(ctx context.Context) VolumeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeArrayOutput)
}

// VolumeMapInput is an input type that accepts VolumeMap and VolumeMapOutput values.
// You can construct a concrete instance of `VolumeMapInput` via:
//
//	VolumeMap{ "key": VolumeArgs{...} }
type VolumeMapInput interface {
	pulumi.Input

	ToVolumeMapOutput() VolumeMapOutput
	ToVolumeMapOutputWithContext(context.Context) VolumeMapOutput
}

type VolumeMap map[string]VolumeInput

func (VolumeMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Volume)(nil)).Elem()
}

func (i VolumeMap) ToVolumeMapOutput() VolumeMapOutput {
	return i.ToVolumeMapOutputWithContext(context.Background())
}

func (i VolumeMap) ToVolumeMapOutputWithContext(ctx context.Context) VolumeMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(VolumeMapOutput)
}

type VolumeOutput struct{ *pulumi.OutputState }

func (VolumeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Volume)(nil)).Elem()
}

func (o VolumeOutput) ToVolumeOutput() VolumeOutput {
	return o
}

func (o VolumeOutput) ToVolumeOutputWithContext(ctx context.Context) VolumeOutput {
	return o
}

// EFS access point ARN
func (o VolumeOutput) AccessPointArn() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.AccessPointArn }).(pulumi.StringOutput)
}

// EFS access point ID
func (o VolumeOutput) AccessPointId() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.AccessPointId }).(pulumi.StringOutput)
}

// Application name
func (o VolumeOutput) Application() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.Application }).(pulumi.StringOutput)
}

// Creation timestamp
func (o VolumeOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Volume description
func (o VolumeOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// Environment name
func (o VolumeOutput) Environment() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.Environment }).(pulumi.StringOutput)
}

// EFS filesystem ID
func (o VolumeOutput) EnvironmentEfsId() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.EnvironmentEfsId }).(pulumi.StringOutput)
}

// Organization machine name (defaults to provider organization)
func (o VolumeOutput) Organization() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.Organization }).(pulumi.StringOutput)
}

// Root directory path
func (o VolumeOutput) RootDirectory() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.RootDirectory }).(pulumi.StringOutput)
}

// Volume ID
func (o VolumeOutput) VolumeId() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.VolumeId }).(pulumi.StringOutput)
}

// Volume name
func (o VolumeOutput) VolumeName() pulumi.StringOutput {
	return o.ApplyT(func(v *Volume) pulumi.StringOutput { return v.VolumeName }).(pulumi.StringOutput)
}

type VolumeArrayOutput struct{ *pulumi.OutputState }

func (VolumeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Volume)(nil)).Elem()
}

func (o VolumeArrayOutput) ToVolumeArrayOutput() VolumeArrayOutput {
	return o
}

func (o VolumeArrayOutput) ToVolumeArrayOutputWithContext(ctx context.Context) VolumeArrayOutput {
	return o
}

func (o VolumeArrayOutput) Index(i pulumi.IntInput) VolumeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Volume {
		return vs[0].([]*Volume)[vs[1].(int)]
	}).(VolumeOutput)
}

type VolumeMapOutput struct{ *pulumi.OutputState }

func (VolumeMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Volume)(nil)).Elem()
}

func (o VolumeMapOutput) ToVolumeMapOutput() VolumeMapOutput {
	return o
}

func (o VolumeMapOutput) ToVolumeMapOutputWithContext(ctx context.Context) VolumeMapOutput {
	return o
}

func (o VolumeMapOutput) MapIndex(k pulumi.StringInput) VolumeOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Volume {
		return vs[0].(map[string]*Volume)[vs[1].(string)]
	}).(VolumeOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeInput)(nil)).Elem(), &Volume{})
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeArrayInput)(nil)).Elem(), VolumeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*VolumeMapInput)(nil)).Elem(), VolumeMap{})
	pulumi.RegisterOutputType(VolumeOutput{})
	pulumi.RegisterOutputType(VolumeArrayOutput{})
	pulumi.RegisterOutputType(VolumeMapOutput{})
}
