// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant
{
    [QuantResourceType("quant:index:Environment")]
    public partial class Environment : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Application name
        /// </summary>
        [Output("application")]
        public Output<string> Application { get; private set; } = null!;

        /// <summary>
        /// Clone configuration from an existing environment
        /// </summary>
        [Output("cloneConfigurationFrom")]
        public Output<string> CloneConfigurationFrom { get; private set; } = null!;

        /// <summary>
        /// Compose definition as a JSON string
        /// </summary>
        [Output("composeDefinition")]
        public Output<string> ComposeDefinition { get; private set; } = null!;

        /// <summary>
        /// Creation timestamp
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Current deployment status
        /// </summary>
        [Output("deploymentStatus")]
        public Output<string> DeploymentStatus { get; private set; } = null!;

        /// <summary>
        /// Desired number of tasks
        /// </summary>
        [Output("desiredCount")]
        public Output<int> DesiredCount { get; private set; } = null!;

        /// <summary>
        /// Environment name (e.g., staging, development)
        /// </summary>
        [Output("envName")]
        public Output<string> EnvName { get; private set; } = null!;

        /// <summary>
        /// Environment variables as a JSON array of {name, value} objects
        /// </summary>
        [Output("environmentVariables")]
        public Output<string> EnvironmentVariables { get; private set; } = null!;

        /// <summary>
        /// Optional image tag suffix for cloning
        /// </summary>
        [Output("imageSuffix")]
        public Output<string> ImageSuffix { get; private set; } = null!;

        /// <summary>
        /// Maximum number of instances for auto-scaling
        /// </summary>
        [Output("maxCapacity")]
        public Output<int> MaxCapacity { get; private set; } = null!;

        /// <summary>
        /// Whether to merge environment variables with cloned ones
        /// </summary>
        [Output("mergeEnvironment")]
        public Output<bool> MergeEnvironment { get; private set; } = null!;

        /// <summary>
        /// Minimum number of instances for auto-scaling
        /// </summary>
        [Output("minCapacity")]
        public Output<int> MinCapacity { get; private set; } = null!;

        /// <summary>
        /// Organization machine name (defaults to provider organization)
        /// </summary>
        [Output("organization")]
        public Output<string> Organization { get; private set; } = null!;

        /// <summary>
        /// Number of running tasks
        /// </summary>
        [Output("runningCount")]
        public Output<int> RunningCount { get; private set; } = null!;

        /// <summary>
        /// Spot configuration as a JSON string
        /// </summary>
        [Output("spotConfiguration")]
        public Output<string> SpotConfiguration { get; private set; } = null!;

        /// <summary>
        /// Environment status
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;

        /// <summary>
        /// Last update timestamp
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a Environment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Environment(string name, EnvironmentArgs args, CustomResourceOptions? options = null)
            : base("quant:index:Environment", name, args ?? new EnvironmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Environment(string name, Input<string> id, EnvironmentState? state = null, CustomResourceOptions? options = null)
            : base("quant:index:Environment", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/quantcdn/pulumi-quant",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Environment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Environment Get(string name, Input<string> id, EnvironmentState? state = null, CustomResourceOptions? options = null)
        {
            return new Environment(name, id, state, options);
        }
    }

    public sealed class EnvironmentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Application name
        /// </summary>
        [Input("application", required: true)]
        public Input<string> Application { get; set; } = null!;

        /// <summary>
        /// Clone configuration from an existing environment
        /// </summary>
        [Input("cloneConfigurationFrom")]
        public Input<string>? CloneConfigurationFrom { get; set; }

        /// <summary>
        /// Compose definition as a JSON string
        /// </summary>
        [Input("composeDefinition")]
        public Input<string>? ComposeDefinition { get; set; }

        /// <summary>
        /// Environment name (e.g., staging, development)
        /// </summary>
        [Input("envName", required: true)]
        public Input<string> EnvName { get; set; } = null!;

        /// <summary>
        /// Environment variables as a JSON array of {name, value} objects
        /// </summary>
        [Input("environmentVariables")]
        public Input<string>? EnvironmentVariables { get; set; }

        /// <summary>
        /// Optional image tag suffix for cloning
        /// </summary>
        [Input("imageSuffix")]
        public Input<string>? ImageSuffix { get; set; }

        /// <summary>
        /// Maximum number of instances for auto-scaling
        /// </summary>
        [Input("maxCapacity")]
        public Input<int>? MaxCapacity { get; set; }

        /// <summary>
        /// Whether to merge environment variables with cloned ones
        /// </summary>
        [Input("mergeEnvironment")]
        public Input<bool>? MergeEnvironment { get; set; }

        /// <summary>
        /// Minimum number of instances for auto-scaling
        /// </summary>
        [Input("minCapacity")]
        public Input<int>? MinCapacity { get; set; }

        /// <summary>
        /// Organization machine name (defaults to provider organization)
        /// </summary>
        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// Spot configuration as a JSON string
        /// </summary>
        [Input("spotConfiguration")]
        public Input<string>? SpotConfiguration { get; set; }

        public EnvironmentArgs()
        {
        }
        public static new EnvironmentArgs Empty => new EnvironmentArgs();
    }

    public sealed class EnvironmentState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Application name
        /// </summary>
        [Input("application")]
        public Input<string>? Application { get; set; }

        /// <summary>
        /// Clone configuration from an existing environment
        /// </summary>
        [Input("cloneConfigurationFrom")]
        public Input<string>? CloneConfigurationFrom { get; set; }

        /// <summary>
        /// Compose definition as a JSON string
        /// </summary>
        [Input("composeDefinition")]
        public Input<string>? ComposeDefinition { get; set; }

        /// <summary>
        /// Creation timestamp
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Current deployment status
        /// </summary>
        [Input("deploymentStatus")]
        public Input<string>? DeploymentStatus { get; set; }

        /// <summary>
        /// Desired number of tasks
        /// </summary>
        [Input("desiredCount")]
        public Input<int>? DesiredCount { get; set; }

        /// <summary>
        /// Environment name (e.g., staging, development)
        /// </summary>
        [Input("envName")]
        public Input<string>? EnvName { get; set; }

        /// <summary>
        /// Environment variables as a JSON array of {name, value} objects
        /// </summary>
        [Input("environmentVariables")]
        public Input<string>? EnvironmentVariables { get; set; }

        /// <summary>
        /// Optional image tag suffix for cloning
        /// </summary>
        [Input("imageSuffix")]
        public Input<string>? ImageSuffix { get; set; }

        /// <summary>
        /// Maximum number of instances for auto-scaling
        /// </summary>
        [Input("maxCapacity")]
        public Input<int>? MaxCapacity { get; set; }

        /// <summary>
        /// Whether to merge environment variables with cloned ones
        /// </summary>
        [Input("mergeEnvironment")]
        public Input<bool>? MergeEnvironment { get; set; }

        /// <summary>
        /// Minimum number of instances for auto-scaling
        /// </summary>
        [Input("minCapacity")]
        public Input<int>? MinCapacity { get; set; }

        /// <summary>
        /// Organization machine name (defaults to provider organization)
        /// </summary>
        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// Number of running tasks
        /// </summary>
        [Input("runningCount")]
        public Input<int>? RunningCount { get; set; }

        /// <summary>
        /// Spot configuration as a JSON string
        /// </summary>
        [Input("spotConfiguration")]
        public Input<string>? SpotConfiguration { get; set; }

        /// <summary>
        /// Environment status
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Last update timestamp
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public EnvironmentState()
        {
        }
        public static new EnvironmentState Empty => new EnvironmentState();
    }
}
