// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant
{
    [QuantResourceType("quant:index:Header")]
    public partial class Header : global::Pulumi.CustomResource
    {
        /// <summary>
        /// HTTP headers to be set for the project
        /// </summary>
        [Output("headers")]
        public Output<ImmutableDictionary<string, string>> Headers { get; private set; } = null!;

        [Output("organization")]
        public Output<string> Organization { get; private set; } = null!;

        [Output("project")]
        public Output<string> Project { get; private set; } = null!;


        /// <summary>
        /// Create a Header resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Header(string name, HeaderArgs args, CustomResourceOptions? options = null)
            : base("quant:index:Header", name, args ?? new HeaderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Header(string name, Input<string> id, HeaderState? state = null, CustomResourceOptions? options = null)
            : base("quant:index:Header", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/quantcdn/pulumi-quant",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Header resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Header Get(string name, Input<string> id, HeaderState? state = null, CustomResourceOptions? options = null)
        {
            return new Header(name, id, state, options);
        }
    }

    public sealed class HeaderArgs : global::Pulumi.ResourceArgs
    {
        [Input("headers", required: true)]
        private InputMap<string>? _headers;

        /// <summary>
        /// HTTP headers to be set for the project
        /// </summary>
        public InputMap<string> Headers
        {
            get => _headers ?? (_headers = new InputMap<string>());
            set => _headers = value;
        }

        [Input("organization")]
        public Input<string>? Organization { get; set; }

        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        public HeaderArgs()
        {
        }
        public static new HeaderArgs Empty => new HeaderArgs();
    }

    public sealed class HeaderState : global::Pulumi.ResourceArgs
    {
        [Input("headers")]
        private InputMap<string>? _headers;

        /// <summary>
        /// HTTP headers to be set for the project
        /// </summary>
        public InputMap<string> Headers
        {
            get => _headers ?? (_headers = new InputMap<string>());
            set => _headers = value;
        }

        [Input("organization")]
        public Input<string>? Organization { get; set; }

        [Input("project")]
        public Input<string>? Project { get; set; }

        public HeaderState()
        {
        }
        public static new HeaderState Empty => new HeaderState();
    }
}
