// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant
{
    [QuantResourceType("quant:index:KvItem")]
    public partial class KvItem : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Item key
        /// </summary>
        [Output("key")]
        public Output<string> Key { get; private set; } = null!;

        /// <summary>
        /// Organization machine name (defaults to provider organization)
        /// </summary>
        [Output("organization")]
        public Output<string> Organization { get; private set; } = null!;

        /// <summary>
        /// Project machine name
        /// </summary>
        [Output("project")]
        public Output<string> Project { get; private set; } = null!;

        /// <summary>
        /// Store as secret with KMS encryption
        /// </summary>
        [Output("secret")]
        public Output<bool> Secret { get; private set; } = null!;

        /// <summary>
        /// KV store ID
        /// </summary>
        [Output("storeId")]
        public Output<string> StoreId { get; private set; } = null!;

        /// <summary>
        /// Item value (can be a JSON string)
        /// </summary>
        [Output("value")]
        public Output<string> Value { get; private set; } = null!;


        /// <summary>
        /// Create a KvItem resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public KvItem(string name, KvItemArgs args, CustomResourceOptions? options = null)
            : base("quant:index:KvItem", name, args ?? new KvItemArgs(), MakeResourceOptions(options, ""))
        {
        }

        private KvItem(string name, Input<string> id, KvItemState? state = null, CustomResourceOptions? options = null)
            : base("quant:index:KvItem", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/quantcdn/pulumi-quant",
                AdditionalSecretOutputs =
                {
                    "value",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing KvItem resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static KvItem Get(string name, Input<string> id, KvItemState? state = null, CustomResourceOptions? options = null)
        {
            return new KvItem(name, id, state, options);
        }
    }

    public sealed class KvItemArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Item key
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// Organization machine name (defaults to provider organization)
        /// </summary>
        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// Project machine name
        /// </summary>
        [Input("project", required: true)]
        public Input<string> Project { get; set; } = null!;

        /// <summary>
        /// Store as secret with KMS encryption
        /// </summary>
        [Input("secret")]
        public Input<bool>? Secret { get; set; }

        /// <summary>
        /// KV store ID
        /// </summary>
        [Input("storeId", required: true)]
        public Input<string> StoreId { get; set; } = null!;

        [Input("value", required: true)]
        private Input<string>? _value;

        /// <summary>
        /// Item value (can be a JSON string)
        /// </summary>
        public Input<string>? Value
        {
            get => _value;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _value = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public KvItemArgs()
        {
        }
        public static new KvItemArgs Empty => new KvItemArgs();
    }

    public sealed class KvItemState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Item key
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// Organization machine name (defaults to provider organization)
        /// </summary>
        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// Project machine name
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        /// <summary>
        /// Store as secret with KMS encryption
        /// </summary>
        [Input("secret")]
        public Input<bool>? Secret { get; set; }

        /// <summary>
        /// KV store ID
        /// </summary>
        [Input("storeId")]
        public Input<string>? StoreId { get; set; }

        [Input("value")]
        private Input<string>? _value;

        /// <summary>
        /// Item value (can be a JSON string)
        /// </summary>
        public Input<string>? Value
        {
            get => _value;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _value = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public KvItemState()
        {
        }
        public static new KvItemState Empty => new KvItemState();
    }
}
