// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant
{
    /// <summary>
    /// The provider type for the quant package. By default, resources use package-wide configuration
    /// settings, however an explicit `Provider` instance may be created and passed during resource
    /// construction to achieve fine-grained programmatic control over provider settings. See the
    /// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
    /// </summary>
    [QuantResourceType("pulumi:providers:quant")]
    public partial class Provider : global::Pulumi.ProviderResource
    {
        /// <summary>
        /// The base URL for the QuantCDN API. Can also be set via QUANTCDN_BASE_URL environment variable.
        /// </summary>
        [Output("baseUrl")]
        public Output<string?> BaseUrl { get; private set; } = null!;

        /// <summary>
        /// The QuantCDN API Bearer token used to authenticate requests. Can also be set via QUANTCDN_API_TOKEN environment variable.
        /// </summary>
        [Output("bearer")]
        public Output<string?> Bearer { get; private set; } = null!;

        /// <summary>
        /// The QuantCDN organization machine name. Can also be set via QUANTCDN_ORGANIZATION environment variable.
        /// </summary>
        [Output("organization")]
        public Output<string?> Organization { get; private set; } = null!;


        /// <summary>
        /// Create a Provider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Provider(string name, ProviderArgs? args = null, CustomResourceOptions? options = null)
            : base("quant", name, args ?? new ProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/quantcdn/pulumi-quant",
                AdditionalSecretOutputs =
                {
                    "bearer",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }

        /// <summary>
        /// This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
        /// </summary>
        public global::Pulumi.Output<ProviderTerraformConfigResult> TerraformConfig()
            => global::Pulumi.Deployment.Instance.Call<ProviderTerraformConfigResult>("pulumi:providers:quant/terraformConfig", CallArgs.Empty, this);
    }

    public sealed class ProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Base delay in milliseconds for exponential backoff. Defaults to 500
        /// </summary>
        [Input("baseDelayMs", json: true)]
        public Input<int>? BaseDelayMs { get; set; }

        /// <summary>
        /// The base URL for the QuantCDN API. Can also be set via QUANTCDN_BASE_URL environment variable.
        /// </summary>
        [Input("baseUrl")]
        public Input<string>? BaseUrl { get; set; }

        [Input("bearer")]
        private Input<string>? _bearer;

        /// <summary>
        /// The QuantCDN API Bearer token used to authenticate requests. Can also be set via QUANTCDN_API_TOKEN environment variable.
        /// </summary>
        public Input<string>? Bearer
        {
            get => _bearer;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _bearer = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Whether to add random jitter to retry delays to avoid thundering herd. Defaults to true
        /// </summary>
        [Input("enableJitter", json: true)]
        public Input<bool>? EnableJitter { get; set; }

        /// <summary>
        /// Maximum delay in milliseconds for exponential backoff. Defaults to 30000 (30 seconds)
        /// </summary>
        [Input("maxDelayMs", json: true)]
        public Input<int>? MaxDelayMs { get; set; }

        /// <summary>
        /// Maximum number of retry attempts for failed requests. Defaults to 3
        /// </summary>
        [Input("maxRetries", json: true)]
        public Input<int>? MaxRetries { get; set; }

        /// <summary>
        /// The QuantCDN organization machine name. Can also be set via QUANTCDN_ORGANIZATION environment variable.
        /// </summary>
        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// Maximum number of requests per second to send to the API. Defaults to 10.0
        /// </summary>
        [Input("requestsPerSecond", json: true)]
        public Input<double>? RequestsPerSecond { get; set; }

        /// <summary>
        /// HTTP client timeout in seconds for API requests. Defaults to 120 seconds to handle slow operations and potential deadlocks. Can also be set via QUANTCDN_TIMEOUT_SECONDS environment variable.
        /// </summary>
        [Input("timeoutSeconds", json: true)]
        public Input<int>? TimeoutSeconds { get; set; }

        public ProviderArgs()
        {
        }
        public static new ProviderArgs Empty => new ProviderArgs();
    }

    /// <summary>
    /// The results of the <see cref="Provider.TerraformConfig"/> method.
    /// </summary>
    [OutputType]
    public sealed class ProviderTerraformConfigResult
    {
        public readonly ImmutableDictionary<string, object> Result;

        [OutputConstructor]
        private ProviderTerraformConfigResult(ImmutableDictionary<string, object> result)
        {
            Result = result;
        }
    }
}
