// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant
{
    [QuantResourceType("quant:index:RuleProxy")]
    public partial class RuleProxy : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Rule action
        /// </summary>
        [Output("action")]
        public Output<string> Action { get; private set; } = null!;

        [Output("actionConfig")]
        public Output<Outputs.RuleProxyActionConfig> ActionConfig { get; private set; } = null!;

        /// <summary>
        /// Quant Cloud application container (required when ApplicationProxy is true)
        /// </summary>
        [Output("applicationContainer")]
        public Output<string> ApplicationContainer { get; private set; } = null!;

        /// <summary>
        /// Quant Cloud application environment (required when ApplicationProxy is true)
        /// </summary>
        [Output("applicationEnvironment")]
        public Output<string> ApplicationEnvironment { get; private set; } = null!;

        /// <summary>
        /// Quant Cloud application name (required when ApplicationProxy is true)
        /// </summary>
        [Output("applicationName")]
        public Output<string> ApplicationName { get; private set; } = null!;

        /// <summary>
        /// Quant Cloud application port (required when ApplicationProxy is true)
        /// </summary>
        [Output("applicationPort")]
        public Output<int> ApplicationPort { get; private set; } = null!;

        /// <summary>
        /// Enable Quant Cloud application proxy mode
        /// </summary>
        [Output("applicationProxy")]
        public Output<bool> ApplicationProxy { get; private set; } = null!;

        /// <summary>
        /// Basic auth password
        /// </summary>
        [Output("authPass")]
        public Output<string> AuthPass { get; private set; } = null!;

        /// <summary>
        /// Basic auth username
        /// </summary>
        [Output("authUser")]
        public Output<string> AuthUser { get; private set; } = null!;

        /// <summary>
        /// Cache lifetime
        /// </summary>
        [Output("cacheLifetime")]
        public Output<string> CacheLifetime { get; private set; } = null!;

        /// <summary>
        /// Country filter type (country_is, country_is_not, any)
        /// </summary>
        [Output("country")]
        public Output<string> Country { get; private set; } = null!;

        /// <summary>
        /// Allowed countries
        /// </summary>
        [Output("countryIs")]
        public Output<ImmutableArray<string>> CountryIs { get; private set; } = null!;

        /// <summary>
        /// Excluded countries
        /// </summary>
        [Output("countryIsNots")]
        public Output<ImmutableArray<string>> CountryIsNots { get; private set; } = null!;

        /// <summary>
        /// Disable SSL verification
        /// </summary>
        [Output("disableSslVerify")]
        public Output<bool> DisableSslVerify { get; private set; } = null!;

        /// <summary>
        /// Whether rule is disabled
        /// </summary>
        [Output("disabled")]
        public Output<bool> Disabled { get; private set; } = null!;

        /// <summary>
        /// Domain patterns (default: any)
        /// </summary>
        [Output("domains")]
        public Output<ImmutableArray<string>> Domains { get; private set; } = null!;

        /// <summary>
        /// Failover cache lifetime in seconds
        /// </summary>
        [Output("failoverLifetime")]
        public Output<string> FailoverLifetime { get; private set; } = null!;

        /// <summary>
        /// Enable failover mode
        /// </summary>
        [Output("failoverMode")]
        public Output<bool> FailoverMode { get; private set; } = null!;

        /// <summary>
        /// Origin status codes that trigger failover
        /// </summary>
        [Output("failoverOriginStatusCodes")]
        public Output<ImmutableArray<string>> FailoverOriginStatusCodes { get; private set; } = null!;

        /// <summary>
        /// Failover TTFB threshold in milliseconds
        /// </summary>
        [Output("failoverOriginTtfb")]
        public Output<string> FailoverOriginTtfb { get; private set; } = null!;

        /// <summary>
        /// Host header override
        /// </summary>
        [Output("host")]
        public Output<string> Host { get; private set; } = null!;

        /// <summary>
        /// Headers to inject
        /// </summary>
        [Output("injectHeaders")]
        public Output<ImmutableDictionary<string, string>> InjectHeaders { get; private set; } = null!;

        /// <summary>
        /// IP filter type (ip_is, ip_is_not, any)
        /// </summary>
        [Output("ip")]
        public Output<string> Ip { get; private set; } = null!;

        /// <summary>
        /// Allowed IP addresses
        /// </summary>
        [Output("ipIs")]
        public Output<ImmutableArray<string>> IpIs { get; private set; } = null!;

        /// <summary>
        /// Excluded IP addresses
        /// </summary>
        [Output("ipIsNots")]
        public Output<ImmutableArray<string>> IpIsNots { get; private set; } = null!;

        /// <summary>
        /// Method filter type (method_is, method_is_not, any)
        /// </summary>
        [Output("method")]
        public Output<string> Method { get; private set; } = null!;

        /// <summary>
        /// Allowed HTTP methods
        /// </summary>
        [Output("methodIs")]
        public Output<ImmutableArray<string>> MethodIs { get; private set; } = null!;

        /// <summary>
        /// Excluded HTTP methods
        /// </summary>
        [Output("methodIsNots")]
        public Output<ImmutableArray<string>> MethodIsNots { get; private set; } = null!;

        /// <summary>
        /// Rule name
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Only proxy 404 responses
        /// </summary>
        [Output("onlyProxy404")]
        public Output<bool> OnlyProxy404 { get; private set; } = null!;

        /// <summary>
        /// Only apply with cookie
        /// </summary>
        [Output("onlyWithCookie")]
        public Output<string> OnlyWithCookie { get; private set; } = null!;

        [Output("organization")]
        public Output<string> Organization { get; private set; } = null!;

        /// <summary>
        /// Origin timeout
        /// </summary>
        [Output("originTimeout")]
        public Output<string> OriginTimeout { get; private set; } = null!;

        [Output("project")]
        public Output<string> Project { get; private set; } = null!;

        /// <summary>
        /// Proxy alert enabled
        /// </summary>
        [Output("proxyAlertEnabled")]
        public Output<bool> ProxyAlertEnabled { get; private set; } = null!;

        /// <summary>
        /// Headers to strip from response
        /// </summary>
        [Output("proxyStripHeaders")]
        public Output<ImmutableArray<string>> ProxyStripHeaders { get; private set; } = null!;

        /// <summary>
        /// Headers to strip from request
        /// </summary>
        [Output("proxyStripRequestHeaders")]
        public Output<ImmutableArray<string>> ProxyStripRequestHeaders { get; private set; } = null!;

        [Output("rule")]
        public Output<string> Rule { get; private set; } = null!;

        /// <summary>
        /// Rule ID
        /// </summary>
        [Output("ruleId")]
        public Output<string> RuleId { get; private set; } = null!;

        /// <summary>
        /// Static error page content (HTML) to serve on origin errors
        /// </summary>
        [Output("staticErrorPage")]
        public Output<string> StaticErrorPage { get; private set; } = null!;

        /// <summary>
        /// Origin status codes that trigger static error page
        /// </summary>
        [Output("staticErrorPageStatusCodes")]
        public Output<ImmutableArray<string>> StaticErrorPageStatusCodes { get; private set; } = null!;

        /// <summary>
        /// Target URL to proxy to
        /// </summary>
        [Output("to")]
        public Output<string> To { get; private set; } = null!;

        /// <summary>
        /// URL patterns
        /// </summary>
        [Output("urls")]
        public Output<ImmutableArray<string>> Urls { get; private set; } = null!;

        /// <summary>
        /// Rule UUID
        /// </summary>
        [Output("uuid")]
        public Output<string> Uuid { get; private set; } = null!;

        /// <summary>
        /// Web Application Firewall configuration
        /// </summary>
        [Output("wafConfig")]
        public Output<Outputs.RuleProxyWafConfig> WafConfig { get; private set; } = null!;

        /// <summary>
        /// WAF enabled
        /// </summary>
        [Output("wafEnabled")]
        public Output<bool> WafEnabled { get; private set; } = null!;

        /// <summary>
        /// Rule weight
        /// </summary>
        [Output("weight")]
        public Output<int> Weight { get; private set; } = null!;


        /// <summary>
        /// Create a RuleProxy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public RuleProxy(string name, RuleProxyArgs args, CustomResourceOptions? options = null)
            : base("quant:index:RuleProxy", name, args ?? new RuleProxyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private RuleProxy(string name, Input<string> id, RuleProxyState? state = null, CustomResourceOptions? options = null)
            : base("quant:index:RuleProxy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/quantcdn/pulumi-quant",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing RuleProxy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static RuleProxy Get(string name, Input<string> id, RuleProxyState? state = null, CustomResourceOptions? options = null)
        {
            return new RuleProxy(name, id, state, options);
        }
    }

    public sealed class RuleProxyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Quant Cloud application container (required when ApplicationProxy is true)
        /// </summary>
        [Input("applicationContainer")]
        public Input<string>? ApplicationContainer { get; set; }

        /// <summary>
        /// Quant Cloud application environment (required when ApplicationProxy is true)
        /// </summary>
        [Input("applicationEnvironment")]
        public Input<string>? ApplicationEnvironment { get; set; }

        /// <summary>
        /// Quant Cloud application name (required when ApplicationProxy is true)
        /// </summary>
        [Input("applicationName")]
        public Input<string>? ApplicationName { get; set; }

        /// <summary>
        /// Quant Cloud application port (required when ApplicationProxy is true)
        /// </summary>
        [Input("applicationPort")]
        public Input<int>? ApplicationPort { get; set; }

        /// <summary>
        /// Enable Quant Cloud application proxy mode
        /// </summary>
        [Input("applicationProxy")]
        public Input<bool>? ApplicationProxy { get; set; }

        /// <summary>
        /// Basic auth password
        /// </summary>
        [Input("authPass")]
        public Input<string>? AuthPass { get; set; }

        /// <summary>
        /// Basic auth username
        /// </summary>
        [Input("authUser")]
        public Input<string>? AuthUser { get; set; }

        /// <summary>
        /// Cache lifetime
        /// </summary>
        [Input("cacheLifetime")]
        public Input<string>? CacheLifetime { get; set; }

        /// <summary>
        /// Country filter type (country_is, country_is_not, any)
        /// </summary>
        [Input("country")]
        public Input<string>? Country { get; set; }

        [Input("countryIs")]
        private InputList<string>? _countryIs;

        /// <summary>
        /// Allowed countries
        /// </summary>
        public InputList<string> CountryIs
        {
            get => _countryIs ?? (_countryIs = new InputList<string>());
            set => _countryIs = value;
        }

        [Input("countryIsNots")]
        private InputList<string>? _countryIsNots;

        /// <summary>
        /// Excluded countries
        /// </summary>
        public InputList<string> CountryIsNots
        {
            get => _countryIsNots ?? (_countryIsNots = new InputList<string>());
            set => _countryIsNots = value;
        }

        /// <summary>
        /// Disable SSL verification
        /// </summary>
        [Input("disableSslVerify")]
        public Input<bool>? DisableSslVerify { get; set; }

        /// <summary>
        /// Whether rule is disabled
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        [Input("domains", required: true)]
        private InputList<string>? _domains;

        /// <summary>
        /// Domain patterns (default: any)
        /// </summary>
        public InputList<string> Domains
        {
            get => _domains ?? (_domains = new InputList<string>());
            set => _domains = value;
        }

        /// <summary>
        /// Failover cache lifetime in seconds
        /// </summary>
        [Input("failoverLifetime")]
        public Input<string>? FailoverLifetime { get; set; }

        /// <summary>
        /// Enable failover mode
        /// </summary>
        [Input("failoverMode")]
        public Input<bool>? FailoverMode { get; set; }

        [Input("failoverOriginStatusCodes")]
        private InputList<string>? _failoverOriginStatusCodes;

        /// <summary>
        /// Origin status codes that trigger failover
        /// </summary>
        public InputList<string> FailoverOriginStatusCodes
        {
            get => _failoverOriginStatusCodes ?? (_failoverOriginStatusCodes = new InputList<string>());
            set => _failoverOriginStatusCodes = value;
        }

        /// <summary>
        /// Failover TTFB threshold in milliseconds
        /// </summary>
        [Input("failoverOriginTtfb")]
        public Input<string>? FailoverOriginTtfb { get; set; }

        /// <summary>
        /// Host header override
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        [Input("injectHeaders")]
        private InputMap<string>? _injectHeaders;

        /// <summary>
        /// Headers to inject
        /// </summary>
        public InputMap<string> InjectHeaders
        {
            get => _injectHeaders ?? (_injectHeaders = new InputMap<string>());
            set => _injectHeaders = value;
        }

        /// <summary>
        /// IP filter type (ip_is, ip_is_not, any)
        /// </summary>
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        [Input("ipIs")]
        private InputList<string>? _ipIs;

        /// <summary>
        /// Allowed IP addresses
        /// </summary>
        public InputList<string> IpIs
        {
            get => _ipIs ?? (_ipIs = new InputList<string>());
            set => _ipIs = value;
        }

        [Input("ipIsNots")]
        private InputList<string>? _ipIsNots;

        /// <summary>
        /// Excluded IP addresses
        /// </summary>
        public InputList<string> IpIsNots
        {
            get => _ipIsNots ?? (_ipIsNots = new InputList<string>());
            set => _ipIsNots = value;
        }

        /// <summary>
        /// Method filter type (method_is, method_is_not, any)
        /// </summary>
        [Input("method")]
        public Input<string>? Method { get; set; }

        [Input("methodIs")]
        private InputList<string>? _methodIs;

        /// <summary>
        /// Allowed HTTP methods
        /// </summary>
        public InputList<string> MethodIs
        {
            get => _methodIs ?? (_methodIs = new InputList<string>());
            set => _methodIs = value;
        }

        [Input("methodIsNots")]
        private InputList<string>? _methodIsNots;

        /// <summary>
        /// Excluded HTTP methods
        /// </summary>
        public InputList<string> MethodIsNots
        {
            get => _methodIsNots ?? (_methodIsNots = new InputList<string>());
            set => _methodIsNots = value;
        }

        /// <summary>
        /// Rule name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Only proxy 404 responses
        /// </summary>
        [Input("onlyProxy404")]
        public Input<bool>? OnlyProxy404 { get; set; }

        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// Origin timeout
        /// </summary>
        [Input("originTimeout")]
        public Input<string>? OriginTimeout { get; set; }

        [Input("project")]
        public Input<string>? Project { get; set; }

        /// <summary>
        /// Proxy alert enabled
        /// </summary>
        [Input("proxyAlertEnabled")]
        public Input<bool>? ProxyAlertEnabled { get; set; }

        [Input("proxyStripHeaders")]
        private InputList<string>? _proxyStripHeaders;

        /// <summary>
        /// Headers to strip from response
        /// </summary>
        public InputList<string> ProxyStripHeaders
        {
            get => _proxyStripHeaders ?? (_proxyStripHeaders = new InputList<string>());
            set => _proxyStripHeaders = value;
        }

        [Input("proxyStripRequestHeaders")]
        private InputList<string>? _proxyStripRequestHeaders;

        /// <summary>
        /// Headers to strip from request
        /// </summary>
        public InputList<string> ProxyStripRequestHeaders
        {
            get => _proxyStripRequestHeaders ?? (_proxyStripRequestHeaders = new InputList<string>());
            set => _proxyStripRequestHeaders = value;
        }

        [Input("rule")]
        public Input<string>? Rule { get; set; }

        /// <summary>
        /// Static error page content (HTML) to serve on origin errors
        /// </summary>
        [Input("staticErrorPage")]
        public Input<string>? StaticErrorPage { get; set; }

        [Input("staticErrorPageStatusCodes")]
        private InputList<string>? _staticErrorPageStatusCodes;

        /// <summary>
        /// Origin status codes that trigger static error page
        /// </summary>
        public InputList<string> StaticErrorPageStatusCodes
        {
            get => _staticErrorPageStatusCodes ?? (_staticErrorPageStatusCodes = new InputList<string>());
            set => _staticErrorPageStatusCodes = value;
        }

        /// <summary>
        /// Target URL to proxy to
        /// </summary>
        [Input("to", required: true)]
        public Input<string> To { get; set; } = null!;

        [Input("urls", required: true)]
        private InputList<string>? _urls;

        /// <summary>
        /// URL patterns
        /// </summary>
        public InputList<string> Urls
        {
            get => _urls ?? (_urls = new InputList<string>());
            set => _urls = value;
        }

        /// <summary>
        /// Rule UUID
        /// </summary>
        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        /// <summary>
        /// Web Application Firewall configuration
        /// </summary>
        [Input("wafConfig")]
        public Input<Inputs.RuleProxyWafConfigArgs>? WafConfig { get; set; }

        /// <summary>
        /// WAF enabled
        /// </summary>
        [Input("wafEnabled")]
        public Input<bool>? WafEnabled { get; set; }

        /// <summary>
        /// Rule weight
        /// </summary>
        [Input("weight")]
        public Input<int>? Weight { get; set; }

        public RuleProxyArgs()
        {
        }
        public static new RuleProxyArgs Empty => new RuleProxyArgs();
    }

    public sealed class RuleProxyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Rule action
        /// </summary>
        [Input("action")]
        public Input<string>? Action { get; set; }

        [Input("actionConfig")]
        public Input<Inputs.RuleProxyActionConfigGetArgs>? ActionConfig { get; set; }

        /// <summary>
        /// Quant Cloud application container (required when ApplicationProxy is true)
        /// </summary>
        [Input("applicationContainer")]
        public Input<string>? ApplicationContainer { get; set; }

        /// <summary>
        /// Quant Cloud application environment (required when ApplicationProxy is true)
        /// </summary>
        [Input("applicationEnvironment")]
        public Input<string>? ApplicationEnvironment { get; set; }

        /// <summary>
        /// Quant Cloud application name (required when ApplicationProxy is true)
        /// </summary>
        [Input("applicationName")]
        public Input<string>? ApplicationName { get; set; }

        /// <summary>
        /// Quant Cloud application port (required when ApplicationProxy is true)
        /// </summary>
        [Input("applicationPort")]
        public Input<int>? ApplicationPort { get; set; }

        /// <summary>
        /// Enable Quant Cloud application proxy mode
        /// </summary>
        [Input("applicationProxy")]
        public Input<bool>? ApplicationProxy { get; set; }

        /// <summary>
        /// Basic auth password
        /// </summary>
        [Input("authPass")]
        public Input<string>? AuthPass { get; set; }

        /// <summary>
        /// Basic auth username
        /// </summary>
        [Input("authUser")]
        public Input<string>? AuthUser { get; set; }

        /// <summary>
        /// Cache lifetime
        /// </summary>
        [Input("cacheLifetime")]
        public Input<string>? CacheLifetime { get; set; }

        /// <summary>
        /// Country filter type (country_is, country_is_not, any)
        /// </summary>
        [Input("country")]
        public Input<string>? Country { get; set; }

        [Input("countryIs")]
        private InputList<string>? _countryIs;

        /// <summary>
        /// Allowed countries
        /// </summary>
        public InputList<string> CountryIs
        {
            get => _countryIs ?? (_countryIs = new InputList<string>());
            set => _countryIs = value;
        }

        [Input("countryIsNots")]
        private InputList<string>? _countryIsNots;

        /// <summary>
        /// Excluded countries
        /// </summary>
        public InputList<string> CountryIsNots
        {
            get => _countryIsNots ?? (_countryIsNots = new InputList<string>());
            set => _countryIsNots = value;
        }

        /// <summary>
        /// Disable SSL verification
        /// </summary>
        [Input("disableSslVerify")]
        public Input<bool>? DisableSslVerify { get; set; }

        /// <summary>
        /// Whether rule is disabled
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        [Input("domains")]
        private InputList<string>? _domains;

        /// <summary>
        /// Domain patterns (default: any)
        /// </summary>
        public InputList<string> Domains
        {
            get => _domains ?? (_domains = new InputList<string>());
            set => _domains = value;
        }

        /// <summary>
        /// Failover cache lifetime in seconds
        /// </summary>
        [Input("failoverLifetime")]
        public Input<string>? FailoverLifetime { get; set; }

        /// <summary>
        /// Enable failover mode
        /// </summary>
        [Input("failoverMode")]
        public Input<bool>? FailoverMode { get; set; }

        [Input("failoverOriginStatusCodes")]
        private InputList<string>? _failoverOriginStatusCodes;

        /// <summary>
        /// Origin status codes that trigger failover
        /// </summary>
        public InputList<string> FailoverOriginStatusCodes
        {
            get => _failoverOriginStatusCodes ?? (_failoverOriginStatusCodes = new InputList<string>());
            set => _failoverOriginStatusCodes = value;
        }

        /// <summary>
        /// Failover TTFB threshold in milliseconds
        /// </summary>
        [Input("failoverOriginTtfb")]
        public Input<string>? FailoverOriginTtfb { get; set; }

        /// <summary>
        /// Host header override
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        [Input("injectHeaders")]
        private InputMap<string>? _injectHeaders;

        /// <summary>
        /// Headers to inject
        /// </summary>
        public InputMap<string> InjectHeaders
        {
            get => _injectHeaders ?? (_injectHeaders = new InputMap<string>());
            set => _injectHeaders = value;
        }

        /// <summary>
        /// IP filter type (ip_is, ip_is_not, any)
        /// </summary>
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        [Input("ipIs")]
        private InputList<string>? _ipIs;

        /// <summary>
        /// Allowed IP addresses
        /// </summary>
        public InputList<string> IpIs
        {
            get => _ipIs ?? (_ipIs = new InputList<string>());
            set => _ipIs = value;
        }

        [Input("ipIsNots")]
        private InputList<string>? _ipIsNots;

        /// <summary>
        /// Excluded IP addresses
        /// </summary>
        public InputList<string> IpIsNots
        {
            get => _ipIsNots ?? (_ipIsNots = new InputList<string>());
            set => _ipIsNots = value;
        }

        /// <summary>
        /// Method filter type (method_is, method_is_not, any)
        /// </summary>
        [Input("method")]
        public Input<string>? Method { get; set; }

        [Input("methodIs")]
        private InputList<string>? _methodIs;

        /// <summary>
        /// Allowed HTTP methods
        /// </summary>
        public InputList<string> MethodIs
        {
            get => _methodIs ?? (_methodIs = new InputList<string>());
            set => _methodIs = value;
        }

        [Input("methodIsNots")]
        private InputList<string>? _methodIsNots;

        /// <summary>
        /// Excluded HTTP methods
        /// </summary>
        public InputList<string> MethodIsNots
        {
            get => _methodIsNots ?? (_methodIsNots = new InputList<string>());
            set => _methodIsNots = value;
        }

        /// <summary>
        /// Rule name
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Only proxy 404 responses
        /// </summary>
        [Input("onlyProxy404")]
        public Input<bool>? OnlyProxy404 { get; set; }

        /// <summary>
        /// Only apply with cookie
        /// </summary>
        [Input("onlyWithCookie")]
        public Input<string>? OnlyWithCookie { get; set; }

        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// Origin timeout
        /// </summary>
        [Input("originTimeout")]
        public Input<string>? OriginTimeout { get; set; }

        [Input("project")]
        public Input<string>? Project { get; set; }

        /// <summary>
        /// Proxy alert enabled
        /// </summary>
        [Input("proxyAlertEnabled")]
        public Input<bool>? ProxyAlertEnabled { get; set; }

        [Input("proxyStripHeaders")]
        private InputList<string>? _proxyStripHeaders;

        /// <summary>
        /// Headers to strip from response
        /// </summary>
        public InputList<string> ProxyStripHeaders
        {
            get => _proxyStripHeaders ?? (_proxyStripHeaders = new InputList<string>());
            set => _proxyStripHeaders = value;
        }

        [Input("proxyStripRequestHeaders")]
        private InputList<string>? _proxyStripRequestHeaders;

        /// <summary>
        /// Headers to strip from request
        /// </summary>
        public InputList<string> ProxyStripRequestHeaders
        {
            get => _proxyStripRequestHeaders ?? (_proxyStripRequestHeaders = new InputList<string>());
            set => _proxyStripRequestHeaders = value;
        }

        [Input("rule")]
        public Input<string>? Rule { get; set; }

        /// <summary>
        /// Rule ID
        /// </summary>
        [Input("ruleId")]
        public Input<string>? RuleId { get; set; }

        /// <summary>
        /// Static error page content (HTML) to serve on origin errors
        /// </summary>
        [Input("staticErrorPage")]
        public Input<string>? StaticErrorPage { get; set; }

        [Input("staticErrorPageStatusCodes")]
        private InputList<string>? _staticErrorPageStatusCodes;

        /// <summary>
        /// Origin status codes that trigger static error page
        /// </summary>
        public InputList<string> StaticErrorPageStatusCodes
        {
            get => _staticErrorPageStatusCodes ?? (_staticErrorPageStatusCodes = new InputList<string>());
            set => _staticErrorPageStatusCodes = value;
        }

        /// <summary>
        /// Target URL to proxy to
        /// </summary>
        [Input("to")]
        public Input<string>? To { get; set; }

        [Input("urls")]
        private InputList<string>? _urls;

        /// <summary>
        /// URL patterns
        /// </summary>
        public InputList<string> Urls
        {
            get => _urls ?? (_urls = new InputList<string>());
            set => _urls = value;
        }

        /// <summary>
        /// Rule UUID
        /// </summary>
        [Input("uuid")]
        public Input<string>? Uuid { get; set; }

        /// <summary>
        /// Web Application Firewall configuration
        /// </summary>
        [Input("wafConfig")]
        public Input<Inputs.RuleProxyWafConfigGetArgs>? WafConfig { get; set; }

        /// <summary>
        /// WAF enabled
        /// </summary>
        [Input("wafEnabled")]
        public Input<bool>? WafEnabled { get; set; }

        /// <summary>
        /// Rule weight
        /// </summary>
        [Input("weight")]
        public Input<int>? Weight { get; set; }

        public RuleProxyState()
        {
        }
        public static new RuleProxyState Empty => new RuleProxyState();
    }
}
