// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace QuantCDN.Quant
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("quant");

        private static readonly __Value<int?> _baseDelayMs = new __Value<int?>(() => __config.GetInt32("baseDelayMs"));
        /// <summary>
        /// Base delay in milliseconds for exponential backoff. Defaults to 500
        /// </summary>
        public static int? BaseDelayMs
        {
            get => _baseDelayMs.Get();
            set => _baseDelayMs.Set(value);
        }

        private static readonly __Value<string?> _baseUrl = new __Value<string?>(() => __config.Get("baseUrl"));
        /// <summary>
        /// The base URL for the QuantCDN API. Can also be set via QUANTCDN_BASE_URL environment variable.
        /// </summary>
        public static string? BaseUrl
        {
            get => _baseUrl.Get();
            set => _baseUrl.Set(value);
        }

        private static readonly __Value<string?> _bearer = new __Value<string?>(() => __config.Get("bearer"));
        /// <summary>
        /// The QuantCDN API Bearer token used to authenticate requests. Can also be set via QUANTCDN_API_TOKEN environment variable.
        /// </summary>
        public static string? Bearer
        {
            get => _bearer.Get();
            set => _bearer.Set(value);
        }

        private static readonly __Value<bool?> _enableJitter = new __Value<bool?>(() => __config.GetBoolean("enableJitter"));
        /// <summary>
        /// Whether to add random jitter to retry delays to avoid thundering herd. Defaults to true
        /// </summary>
        public static bool? EnableJitter
        {
            get => _enableJitter.Get();
            set => _enableJitter.Set(value);
        }

        private static readonly __Value<int?> _maxDelayMs = new __Value<int?>(() => __config.GetInt32("maxDelayMs"));
        /// <summary>
        /// Maximum delay in milliseconds for exponential backoff. Defaults to 30000 (30 seconds)
        /// </summary>
        public static int? MaxDelayMs
        {
            get => _maxDelayMs.Get();
            set => _maxDelayMs.Set(value);
        }

        private static readonly __Value<int?> _maxRetries = new __Value<int?>(() => __config.GetInt32("maxRetries"));
        /// <summary>
        /// Maximum number of retry attempts for failed requests. Defaults to 3
        /// </summary>
        public static int? MaxRetries
        {
            get => _maxRetries.Get();
            set => _maxRetries.Set(value);
        }

        private static readonly __Value<string?> _organization = new __Value<string?>(() => __config.Get("organization"));
        /// <summary>
        /// The QuantCDN organization machine name. Can also be set via QUANTCDN_ORGANIZATION environment variable.
        /// </summary>
        public static string? Organization
        {
            get => _organization.Get();
            set => _organization.Set(value);
        }

        private static readonly __Value<double?> _requestsPerSecond = new __Value<double?>(() => __config.GetDouble("requestsPerSecond"));
        /// <summary>
        /// Maximum number of requests per second to send to the API. Defaults to 10.0
        /// </summary>
        public static double? RequestsPerSecond
        {
            get => _requestsPerSecond.Get();
            set => _requestsPerSecond.Set(value);
        }

        private static readonly __Value<int?> _timeoutSeconds = new __Value<int?>(() => __config.GetInt32("timeoutSeconds"));
        /// <summary>
        /// HTTP client timeout in seconds for API requests. Defaults to 120 seconds to handle slow operations and potential deadlocks. Can also be set via QUANTCDN_TIMEOUT_SECONDS environment variable.
        /// </summary>
        public static int? TimeoutSeconds
        {
            get => _timeoutSeconds.Get();
            set => _timeoutSeconds.Set(value);
        }

    }
}
