# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .ai_governance import *
from .ai_skill import *
from .ai_vector_collection import *
from .ai_vector_document import *
from .application import *
from .crawler import *
from .crawler_schedule import *
from .cron_job import *
from .domain import *
from .environment import *
from .get_project import *
from .get_projects import *
from .header import *
from .kv_item import *
from .kv_store import *
from .project import *
from .provider import *
from .rule_auth import *
from .rule_bot_challenge import *
from .rule_content_filter import *
from .rule_custom_response import *
from .rule_function import *
from .rule_headers import *
from .rule_proxy import *
from .rule_redirect import *
from .rule_serve_static import *
from .volume import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_quant.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_quant.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "quant",
  "mod": "index",
  "fqn": "pulumi_quant",
  "classes": {
   "quant:index:AiGovernance": "AiGovernance",
   "quant:index:AiSkill": "AiSkill",
   "quant:index:AiVectorCollection": "AiVectorCollection",
   "quant:index:AiVectorDocument": "AiVectorDocument",
   "quant:index:Application": "Application",
   "quant:index:Crawler": "Crawler",
   "quant:index:CrawlerSchedule": "CrawlerSchedule",
   "quant:index:CronJob": "CronJob",
   "quant:index:Domain": "Domain",
   "quant:index:Environment": "Environment",
   "quant:index:Header": "Header",
   "quant:index:KvItem": "KvItem",
   "quant:index:KvStore": "KvStore",
   "quant:index:Project": "Project",
   "quant:index:RuleAuth": "RuleAuth",
   "quant:index:RuleBotChallenge": "RuleBotChallenge",
   "quant:index:RuleContentFilter": "RuleContentFilter",
   "quant:index:RuleCustomResponse": "RuleCustomResponse",
   "quant:index:RuleFunction": "RuleFunction",
   "quant:index:RuleHeaders": "RuleHeaders",
   "quant:index:RuleProxy": "RuleProxy",
   "quant:index:RuleRedirect": "RuleRedirect",
   "quant:index:RuleServeStatic": "RuleServeStatic",
   "quant:index:Volume": "Volume"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "quant",
  "token": "pulumi:providers:quant",
  "fqn": "pulumi_quant",
  "class": "Provider"
 }
]
"""
)
