# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['AiVectorDocumentArgs', 'AiVectorDocument']

@pulumi.input_type
class AiVectorDocumentArgs:
    def __init__(__self__, *,
                 collection_id: pulumi.Input[_builtins.str],
                 content: pulumi.Input[_builtins.str],
                 key: pulumi.Input[_builtins.str],
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 searchable_fields: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        The set of arguments for constructing a AiVectorDocument resource.

        :param pulumi.Input[_builtins.str] collection_id: Vector collection UUID
        :param pulumi.Input[_builtins.str] content: Document text content
        :param pulumi.Input[_builtins.str] key: Stable document key (max 512 characters)
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Key-value metadata attached to the document
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] searchable_fields: List of searchable field names
        """
        pulumi.set(__self__, "collection_id", collection_id)
        pulumi.set(__self__, "content", content)
        pulumi.set(__self__, "key", key)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if searchable_fields is not None:
            pulumi.set(__self__, "searchable_fields", searchable_fields)

    @_builtins.property
    @pulumi.getter(name="collectionId")
    def collection_id(self) -> pulumi.Input[_builtins.str]:
        """
        Vector collection UUID
        """
        return pulumi.get(self, "collection_id")

    @collection_id.setter
    def collection_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "collection_id", value)

    @_builtins.property
    @pulumi.getter
    def content(self) -> pulumi.Input[_builtins.str]:
        """
        Document text content
        """
        return pulumi.get(self, "content")

    @content.setter
    def content(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "content", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[_builtins.str]:
        """
        Stable document key (max 512 characters)
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Key-value metadata attached to the document
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Organization machine name (defaults to provider organization)
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization", value)

    @_builtins.property
    @pulumi.getter(name="searchableFields")
    def searchable_fields(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of searchable field names
        """
        return pulumi.get(self, "searchable_fields")

    @searchable_fields.setter
    def searchable_fields(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "searchable_fields", value)


@pulumi.input_type
class _AiVectorDocumentState:
    def __init__(__self__, *,
                 collection_id: Optional[pulumi.Input[_builtins.str]] = None,
                 content: Optional[pulumi.Input[_builtins.str]] = None,
                 content_sha256: Optional[pulumi.Input[_builtins.str]] = None,
                 document_id: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 searchable_fields: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None):
        """
        Input properties used for looking up and filtering AiVectorDocument resources.

        :param pulumi.Input[_builtins.str] collection_id: Vector collection UUID
        :param pulumi.Input[_builtins.str] content: Document text content
        :param pulumi.Input[_builtins.str] content_sha256: SHA256 hash of content for drift detection
        :param pulumi.Input[_builtins.str] document_id: Auto-assigned document UUID
        :param pulumi.Input[_builtins.str] key: Stable document key (max 512 characters)
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Key-value metadata attached to the document
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] searchable_fields: List of searchable field names
        """
        if collection_id is not None:
            pulumi.set(__self__, "collection_id", collection_id)
        if content is not None:
            pulumi.set(__self__, "content", content)
        if content_sha256 is not None:
            pulumi.set(__self__, "content_sha256", content_sha256)
        if document_id is not None:
            pulumi.set(__self__, "document_id", document_id)
        if key is not None:
            pulumi.set(__self__, "key", key)
        if metadata is not None:
            pulumi.set(__self__, "metadata", metadata)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if searchable_fields is not None:
            pulumi.set(__self__, "searchable_fields", searchable_fields)

    @_builtins.property
    @pulumi.getter(name="collectionId")
    def collection_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Vector collection UUID
        """
        return pulumi.get(self, "collection_id")

    @collection_id.setter
    def collection_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "collection_id", value)

    @_builtins.property
    @pulumi.getter
    def content(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Document text content
        """
        return pulumi.get(self, "content")

    @content.setter
    def content(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "content", value)

    @_builtins.property
    @pulumi.getter(name="contentSha256")
    def content_sha256(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        SHA256 hash of content for drift detection
        """
        return pulumi.get(self, "content_sha256")

    @content_sha256.setter
    def content_sha256(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "content_sha256", value)

    @_builtins.property
    @pulumi.getter(name="documentId")
    def document_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Auto-assigned document UUID
        """
        return pulumi.get(self, "document_id")

    @document_id.setter
    def document_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "document_id", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Stable document key (max 512 characters)
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]:
        """
        Key-value metadata attached to the document
        """
        return pulumi.get(self, "metadata")

    @metadata.setter
    def metadata(self, value: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "metadata", value)

    @_builtins.property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Organization machine name (defaults to provider organization)
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization", value)

    @_builtins.property
    @pulumi.getter(name="searchableFields")
    def searchable_fields(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        List of searchable field names
        """
        return pulumi.get(self, "searchable_fields")

    @searchable_fields.setter
    def searchable_fields(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "searchable_fields", value)


@pulumi.type_token("quant:index:AiVectorDocument")
class AiVectorDocument(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 collection_id: Optional[pulumi.Input[_builtins.str]] = None,
                 content: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 searchable_fields: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        """
        Create a AiVectorDocument resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] collection_id: Vector collection UUID
        :param pulumi.Input[_builtins.str] content: Document text content
        :param pulumi.Input[_builtins.str] key: Stable document key (max 512 characters)
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Key-value metadata attached to the document
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] searchable_fields: List of searchable field names
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: AiVectorDocumentArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a AiVectorDocument resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param AiVectorDocumentArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(AiVectorDocumentArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 collection_id: Optional[pulumi.Input[_builtins.str]] = None,
                 content: Optional[pulumi.Input[_builtins.str]] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 searchable_fields: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = AiVectorDocumentArgs.__new__(AiVectorDocumentArgs)

            if collection_id is None and not opts.urn:
                raise TypeError("Missing required property 'collection_id'")
            __props__.__dict__["collection_id"] = collection_id
            if content is None and not opts.urn:
                raise TypeError("Missing required property 'content'")
            __props__.__dict__["content"] = content
            if key is None and not opts.urn:
                raise TypeError("Missing required property 'key'")
            __props__.__dict__["key"] = key
            __props__.__dict__["metadata"] = metadata
            __props__.__dict__["organization"] = organization
            __props__.__dict__["searchable_fields"] = searchable_fields
            __props__.__dict__["content_sha256"] = None
            __props__.__dict__["document_id"] = None
        super(AiVectorDocument, __self__).__init__(
            'quant:index:AiVectorDocument',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            collection_id: Optional[pulumi.Input[_builtins.str]] = None,
            content: Optional[pulumi.Input[_builtins.str]] = None,
            content_sha256: Optional[pulumi.Input[_builtins.str]] = None,
            document_id: Optional[pulumi.Input[_builtins.str]] = None,
            key: Optional[pulumi.Input[_builtins.str]] = None,
            metadata: Optional[pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
            organization: Optional[pulumi.Input[_builtins.str]] = None,
            searchable_fields: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None) -> 'AiVectorDocument':
        """
        Get an existing AiVectorDocument resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] collection_id: Vector collection UUID
        :param pulumi.Input[_builtins.str] content: Document text content
        :param pulumi.Input[_builtins.str] content_sha256: SHA256 hash of content for drift detection
        :param pulumi.Input[_builtins.str] document_id: Auto-assigned document UUID
        :param pulumi.Input[_builtins.str] key: Stable document key (max 512 characters)
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] metadata: Key-value metadata attached to the document
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] searchable_fields: List of searchable field names
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _AiVectorDocumentState.__new__(_AiVectorDocumentState)

        __props__.__dict__["collection_id"] = collection_id
        __props__.__dict__["content"] = content
        __props__.__dict__["content_sha256"] = content_sha256
        __props__.__dict__["document_id"] = document_id
        __props__.__dict__["key"] = key
        __props__.__dict__["metadata"] = metadata
        __props__.__dict__["organization"] = organization
        __props__.__dict__["searchable_fields"] = searchable_fields
        return AiVectorDocument(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="collectionId")
    def collection_id(self) -> pulumi.Output[_builtins.str]:
        """
        Vector collection UUID
        """
        return pulumi.get(self, "collection_id")

    @_builtins.property
    @pulumi.getter
    def content(self) -> pulumi.Output[_builtins.str]:
        """
        Document text content
        """
        return pulumi.get(self, "content")

    @_builtins.property
    @pulumi.getter(name="contentSha256")
    def content_sha256(self) -> pulumi.Output[_builtins.str]:
        """
        SHA256 hash of content for drift detection
        """
        return pulumi.get(self, "content_sha256")

    @_builtins.property
    @pulumi.getter(name="documentId")
    def document_id(self) -> pulumi.Output[_builtins.str]:
        """
        Auto-assigned document UUID
        """
        return pulumi.get(self, "document_id")

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[_builtins.str]:
        """
        Stable document key (max 512 characters)
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def metadata(self) -> pulumi.Output[Optional[Mapping[str, _builtins.str]]]:
        """
        Key-value metadata attached to the document
        """
        return pulumi.get(self, "metadata")

    @_builtins.property
    @pulumi.getter
    def organization(self) -> pulumi.Output[_builtins.str]:
        """
        Organization machine name (defaults to provider organization)
        """
        return pulumi.get(self, "organization")

    @_builtins.property
    @pulumi.getter(name="searchableFields")
    def searchable_fields(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        List of searchable field names
        """
        return pulumi.get(self, "searchable_fields")

