# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['CronJobArgs', 'CronJob']

@pulumi.input_type
class CronJobArgs:
    def __init__(__self__, *,
                 application: pulumi.Input[_builtins.str],
                 command: pulumi.Input[_builtins.str],
                 environment: pulumi.Input[_builtins.str],
                 schedule_expression: pulumi.Input[_builtins.str],
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 is_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 target_container_name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a CronJob resource.

        :param pulumi.Input[_builtins.str] application: Application name
        :param pulumi.Input[_builtins.str] command: Command to execute as a JSON array of strings
        :param pulumi.Input[_builtins.str] environment: Environment name
        :param pulumi.Input[_builtins.str] schedule_expression: Cron schedule expression
        :param pulumi.Input[_builtins.str] description: Cron job description
        :param pulumi.Input[_builtins.bool] is_enabled: Whether the cron job is enabled
        :param pulumi.Input[_builtins.str] name: Cron job name
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[_builtins.str] target_container_name: Target container name
        """
        pulumi.set(__self__, "application", application)
        pulumi.set(__self__, "command", command)
        pulumi.set(__self__, "environment", environment)
        pulumi.set(__self__, "schedule_expression", schedule_expression)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if is_enabled is not None:
            pulumi.set(__self__, "is_enabled", is_enabled)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if target_container_name is not None:
            pulumi.set(__self__, "target_container_name", target_container_name)

    @_builtins.property
    @pulumi.getter
    def application(self) -> pulumi.Input[_builtins.str]:
        """
        Application name
        """
        return pulumi.get(self, "application")

    @application.setter
    def application(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "application", value)

    @_builtins.property
    @pulumi.getter
    def command(self) -> pulumi.Input[_builtins.str]:
        """
        Command to execute as a JSON array of strings
        """
        return pulumi.get(self, "command")

    @command.setter
    def command(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "command", value)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> pulumi.Input[_builtins.str]:
        """
        Environment name
        """
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter(name="scheduleExpression")
    def schedule_expression(self) -> pulumi.Input[_builtins.str]:
        """
        Cron schedule expression
        """
        return pulumi.get(self, "schedule_expression")

    @schedule_expression.setter
    def schedule_expression(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "schedule_expression", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Cron job description
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="isEnabled")
    def is_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the cron job is enabled
        """
        return pulumi.get(self, "is_enabled")

    @is_enabled.setter
    def is_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_enabled", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Cron job name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Organization machine name (defaults to provider organization)
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization", value)

    @_builtins.property
    @pulumi.getter(name="targetContainerName")
    def target_container_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Target container name
        """
        return pulumi.get(self, "target_container_name")

    @target_container_name.setter
    def target_container_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "target_container_name", value)


@pulumi.input_type
class _CronJobState:
    def __init__(__self__, *,
                 application: Optional[pulumi.Input[_builtins.str]] = None,
                 command: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 is_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 schedule: Optional[pulumi.Input[_builtins.str]] = None,
                 schedule_expression: Optional[pulumi.Input[_builtins.str]] = None,
                 target_container_name: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering CronJob resources.

        :param pulumi.Input[_builtins.str] application: Application name
        :param pulumi.Input[_builtins.str] command: Command to execute as a JSON array of strings
        :param pulumi.Input[_builtins.str] description: Cron job description
        :param pulumi.Input[_builtins.str] environment: Environment name
        :param pulumi.Input[_builtins.bool] is_enabled: Whether the cron job is enabled
        :param pulumi.Input[_builtins.str] name: Cron job name
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[_builtins.str] schedule: Resolved cron schedule
        :param pulumi.Input[_builtins.str] schedule_expression: Cron schedule expression
        :param pulumi.Input[_builtins.str] target_container_name: Target container name
        """
        if application is not None:
            pulumi.set(__self__, "application", application)
        if command is not None:
            pulumi.set(__self__, "command", command)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if is_enabled is not None:
            pulumi.set(__self__, "is_enabled", is_enabled)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if schedule is not None:
            pulumi.set(__self__, "schedule", schedule)
        if schedule_expression is not None:
            pulumi.set(__self__, "schedule_expression", schedule_expression)
        if target_container_name is not None:
            pulumi.set(__self__, "target_container_name", target_container_name)

    @_builtins.property
    @pulumi.getter
    def application(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Application name
        """
        return pulumi.get(self, "application")

    @application.setter
    def application(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "application", value)

    @_builtins.property
    @pulumi.getter
    def command(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Command to execute as a JSON array of strings
        """
        return pulumi.get(self, "command")

    @command.setter
    def command(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "command", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Cron job description
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Environment name
        """
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter(name="isEnabled")
    def is_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether the cron job is enabled
        """
        return pulumi.get(self, "is_enabled")

    @is_enabled.setter
    def is_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_enabled", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Cron job name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Organization machine name (defaults to provider organization)
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization", value)

    @_builtins.property
    @pulumi.getter
    def schedule(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Resolved cron schedule
        """
        return pulumi.get(self, "schedule")

    @schedule.setter
    def schedule(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "schedule", value)

    @_builtins.property
    @pulumi.getter(name="scheduleExpression")
    def schedule_expression(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Cron schedule expression
        """
        return pulumi.get(self, "schedule_expression")

    @schedule_expression.setter
    def schedule_expression(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "schedule_expression", value)

    @_builtins.property
    @pulumi.getter(name="targetContainerName")
    def target_container_name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Target container name
        """
        return pulumi.get(self, "target_container_name")

    @target_container_name.setter
    def target_container_name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "target_container_name", value)


@pulumi.type_token("quant:index:CronJob")
class CronJob(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 application: Optional[pulumi.Input[_builtins.str]] = None,
                 command: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 is_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 schedule_expression: Optional[pulumi.Input[_builtins.str]] = None,
                 target_container_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a CronJob resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] application: Application name
        :param pulumi.Input[_builtins.str] command: Command to execute as a JSON array of strings
        :param pulumi.Input[_builtins.str] description: Cron job description
        :param pulumi.Input[_builtins.str] environment: Environment name
        :param pulumi.Input[_builtins.bool] is_enabled: Whether the cron job is enabled
        :param pulumi.Input[_builtins.str] name: Cron job name
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[_builtins.str] schedule_expression: Cron schedule expression
        :param pulumi.Input[_builtins.str] target_container_name: Target container name
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CronJobArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a CronJob resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param CronJobArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CronJobArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 application: Optional[pulumi.Input[_builtins.str]] = None,
                 command: Optional[pulumi.Input[_builtins.str]] = None,
                 description: Optional[pulumi.Input[_builtins.str]] = None,
                 environment: Optional[pulumi.Input[_builtins.str]] = None,
                 is_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 schedule_expression: Optional[pulumi.Input[_builtins.str]] = None,
                 target_container_name: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CronJobArgs.__new__(CronJobArgs)

            if application is None and not opts.urn:
                raise TypeError("Missing required property 'application'")
            __props__.__dict__["application"] = application
            if command is None and not opts.urn:
                raise TypeError("Missing required property 'command'")
            __props__.__dict__["command"] = command
            __props__.__dict__["description"] = description
            if environment is None and not opts.urn:
                raise TypeError("Missing required property 'environment'")
            __props__.__dict__["environment"] = environment
            __props__.__dict__["is_enabled"] = is_enabled
            __props__.__dict__["name"] = name
            __props__.__dict__["organization"] = organization
            if schedule_expression is None and not opts.urn:
                raise TypeError("Missing required property 'schedule_expression'")
            __props__.__dict__["schedule_expression"] = schedule_expression
            __props__.__dict__["target_container_name"] = target_container_name
            __props__.__dict__["schedule"] = None
        super(CronJob, __self__).__init__(
            'quant:index:CronJob',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            application: Optional[pulumi.Input[_builtins.str]] = None,
            command: Optional[pulumi.Input[_builtins.str]] = None,
            description: Optional[pulumi.Input[_builtins.str]] = None,
            environment: Optional[pulumi.Input[_builtins.str]] = None,
            is_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            organization: Optional[pulumi.Input[_builtins.str]] = None,
            schedule: Optional[pulumi.Input[_builtins.str]] = None,
            schedule_expression: Optional[pulumi.Input[_builtins.str]] = None,
            target_container_name: Optional[pulumi.Input[_builtins.str]] = None) -> 'CronJob':
        """
        Get an existing CronJob resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] application: Application name
        :param pulumi.Input[_builtins.str] command: Command to execute as a JSON array of strings
        :param pulumi.Input[_builtins.str] description: Cron job description
        :param pulumi.Input[_builtins.str] environment: Environment name
        :param pulumi.Input[_builtins.bool] is_enabled: Whether the cron job is enabled
        :param pulumi.Input[_builtins.str] name: Cron job name
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[_builtins.str] schedule: Resolved cron schedule
        :param pulumi.Input[_builtins.str] schedule_expression: Cron schedule expression
        :param pulumi.Input[_builtins.str] target_container_name: Target container name
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _CronJobState.__new__(_CronJobState)

        __props__.__dict__["application"] = application
        __props__.__dict__["command"] = command
        __props__.__dict__["description"] = description
        __props__.__dict__["environment"] = environment
        __props__.__dict__["is_enabled"] = is_enabled
        __props__.__dict__["name"] = name
        __props__.__dict__["organization"] = organization
        __props__.__dict__["schedule"] = schedule
        __props__.__dict__["schedule_expression"] = schedule_expression
        __props__.__dict__["target_container_name"] = target_container_name
        return CronJob(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def application(self) -> pulumi.Output[_builtins.str]:
        """
        Application name
        """
        return pulumi.get(self, "application")

    @_builtins.property
    @pulumi.getter
    def command(self) -> pulumi.Output[_builtins.str]:
        """
        Command to execute as a JSON array of strings
        """
        return pulumi.get(self, "command")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[_builtins.str]:
        """
        Cron job description
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def environment(self) -> pulumi.Output[_builtins.str]:
        """
        Environment name
        """
        return pulumi.get(self, "environment")

    @_builtins.property
    @pulumi.getter(name="isEnabled")
    def is_enabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the cron job is enabled
        """
        return pulumi.get(self, "is_enabled")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Cron job name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def organization(self) -> pulumi.Output[_builtins.str]:
        """
        Organization machine name (defaults to provider organization)
        """
        return pulumi.get(self, "organization")

    @_builtins.property
    @pulumi.getter
    def schedule(self) -> pulumi.Output[_builtins.str]:
        """
        Resolved cron schedule
        """
        return pulumi.get(self, "schedule")

    @_builtins.property
    @pulumi.getter(name="scheduleExpression")
    def schedule_expression(self) -> pulumi.Output[_builtins.str]:
        """
        Cron schedule expression
        """
        return pulumi.get(self, "schedule_expression")

    @_builtins.property
    @pulumi.getter(name="targetContainerName")
    def target_container_name(self) -> pulumi.Output[_builtins.str]:
        """
        Target container name
        """
        return pulumi.get(self, "target_container_name")

