# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['DomainArgs', 'Domain']

@pulumi.input_type
class DomainArgs:
    def __init__(__self__, *,
                 domain: pulumi.Input[_builtins.str],
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Domain resource.

        :param pulumi.Input[_builtins.str] domain: Domain name
        :param pulumi.Input[_builtins.str] organization: Organization identifier
        :param pulumi.Input[_builtins.str] project: Project identifier
        """
        pulumi.set(__self__, "domain", domain)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if project is not None:
            pulumi.set(__self__, "project", project)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Input[_builtins.str]:
        """
        Domain name
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Organization identifier
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization", value)

    @_builtins.property
    @pulumi.getter
    def project(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Project identifier
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project", value)


@pulumi.input_type
class _DomainState:
    def __init__(__self__, *,
                 dns_engaged: Optional[pulumi.Input[_builtins.int]] = None,
                 dns_go_live_records: Optional[pulumi.Input[Sequence[pulumi.Input['DomainDnsGoLiveRecordArgs']]]] = None,
                 dns_validation_records: Optional[pulumi.Input[Sequence[pulumi.Input['DomainDnsValidationRecordArgs']]]] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering Domain resources.

        :param pulumi.Input[_builtins.int] dns_engaged: DNS engagement status. 1 indicates DNS is properly configured and engaged, 0 indicates DNS configuration is pending or incomplete.
        :param pulumi.Input[Sequence[pulumi.Input['DomainDnsGoLiveRecordArgs']]] dns_go_live_records: DNS records required to route traffic to the CDN. These records differ based on domain type (apex vs subdomain). Present when the CDN is configured and ready to receive traffic.
        :param pulumi.Input[Sequence[pulumi.Input['DomainDnsValidationRecordArgs']]] dns_validation_records: DNS validation records required for SSL certificate validation. Present for domains pending certificate validation. Each record contains the CNAME information needed to validate domain ownership.
        :param pulumi.Input[_builtins.str] domain: Domain name
        :param pulumi.Input[_builtins.str] organization: Organization identifier
        :param pulumi.Input[_builtins.str] project: Project identifier
        """
        if dns_engaged is not None:
            pulumi.set(__self__, "dns_engaged", dns_engaged)
        if dns_go_live_records is not None:
            pulumi.set(__self__, "dns_go_live_records", dns_go_live_records)
        if dns_validation_records is not None:
            pulumi.set(__self__, "dns_validation_records", dns_validation_records)
        if domain is not None:
            pulumi.set(__self__, "domain", domain)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if project is not None:
            pulumi.set(__self__, "project", project)

    @_builtins.property
    @pulumi.getter(name="dnsEngaged")
    def dns_engaged(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        DNS engagement status. 1 indicates DNS is properly configured and engaged, 0 indicates DNS configuration is pending or incomplete.
        """
        return pulumi.get(self, "dns_engaged")

    @dns_engaged.setter
    def dns_engaged(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "dns_engaged", value)

    @_builtins.property
    @pulumi.getter(name="dnsGoLiveRecords")
    def dns_go_live_records(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['DomainDnsGoLiveRecordArgs']]]]:
        """
        DNS records required to route traffic to the CDN. These records differ based on domain type (apex vs subdomain). Present when the CDN is configured and ready to receive traffic.
        """
        return pulumi.get(self, "dns_go_live_records")

    @dns_go_live_records.setter
    def dns_go_live_records(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['DomainDnsGoLiveRecordArgs']]]]):
        pulumi.set(self, "dns_go_live_records", value)

    @_builtins.property
    @pulumi.getter(name="dnsValidationRecords")
    def dns_validation_records(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['DomainDnsValidationRecordArgs']]]]:
        """
        DNS validation records required for SSL certificate validation. Present for domains pending certificate validation. Each record contains the CNAME information needed to validate domain ownership.
        """
        return pulumi.get(self, "dns_validation_records")

    @dns_validation_records.setter
    def dns_validation_records(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['DomainDnsValidationRecordArgs']]]]):
        pulumi.set(self, "dns_validation_records", value)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Domain name
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Organization identifier
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization", value)

    @_builtins.property
    @pulumi.getter
    def project(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Project identifier
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project", value)


@pulumi.type_token("quant:index:Domain")
class Domain(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Domain resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] domain: Domain name
        :param pulumi.Input[_builtins.str] organization: Organization identifier
        :param pulumi.Input[_builtins.str] project: Project identifier
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DomainArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Domain resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param DomainArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DomainArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 domain: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DomainArgs.__new__(DomainArgs)

            if domain is None and not opts.urn:
                raise TypeError("Missing required property 'domain'")
            __props__.__dict__["domain"] = domain
            __props__.__dict__["organization"] = organization
            __props__.__dict__["project"] = project
            __props__.__dict__["dns_engaged"] = None
            __props__.__dict__["dns_go_live_records"] = None
            __props__.__dict__["dns_validation_records"] = None
        super(Domain, __self__).__init__(
            'quant:index:Domain',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            dns_engaged: Optional[pulumi.Input[_builtins.int]] = None,
            dns_go_live_records: Optional[pulumi.Input[Sequence[pulumi.Input[Union['DomainDnsGoLiveRecordArgs', 'DomainDnsGoLiveRecordArgsDict']]]]] = None,
            dns_validation_records: Optional[pulumi.Input[Sequence[pulumi.Input[Union['DomainDnsValidationRecordArgs', 'DomainDnsValidationRecordArgsDict']]]]] = None,
            domain: Optional[pulumi.Input[_builtins.str]] = None,
            organization: Optional[pulumi.Input[_builtins.str]] = None,
            project: Optional[pulumi.Input[_builtins.str]] = None) -> 'Domain':
        """
        Get an existing Domain resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] dns_engaged: DNS engagement status. 1 indicates DNS is properly configured and engaged, 0 indicates DNS configuration is pending or incomplete.
        :param pulumi.Input[Sequence[pulumi.Input[Union['DomainDnsGoLiveRecordArgs', 'DomainDnsGoLiveRecordArgsDict']]]] dns_go_live_records: DNS records required to route traffic to the CDN. These records differ based on domain type (apex vs subdomain). Present when the CDN is configured and ready to receive traffic.
        :param pulumi.Input[Sequence[pulumi.Input[Union['DomainDnsValidationRecordArgs', 'DomainDnsValidationRecordArgsDict']]]] dns_validation_records: DNS validation records required for SSL certificate validation. Present for domains pending certificate validation. Each record contains the CNAME information needed to validate domain ownership.
        :param pulumi.Input[_builtins.str] domain: Domain name
        :param pulumi.Input[_builtins.str] organization: Organization identifier
        :param pulumi.Input[_builtins.str] project: Project identifier
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DomainState.__new__(_DomainState)

        __props__.__dict__["dns_engaged"] = dns_engaged
        __props__.__dict__["dns_go_live_records"] = dns_go_live_records
        __props__.__dict__["dns_validation_records"] = dns_validation_records
        __props__.__dict__["domain"] = domain
        __props__.__dict__["organization"] = organization
        __props__.__dict__["project"] = project
        return Domain(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="dnsEngaged")
    def dns_engaged(self) -> pulumi.Output[_builtins.int]:
        """
        DNS engagement status. 1 indicates DNS is properly configured and engaged, 0 indicates DNS configuration is pending or incomplete.
        """
        return pulumi.get(self, "dns_engaged")

    @_builtins.property
    @pulumi.getter(name="dnsGoLiveRecords")
    def dns_go_live_records(self) -> pulumi.Output[Sequence['outputs.DomainDnsGoLiveRecord']]:
        """
        DNS records required to route traffic to the CDN. These records differ based on domain type (apex vs subdomain). Present when the CDN is configured and ready to receive traffic.
        """
        return pulumi.get(self, "dns_go_live_records")

    @_builtins.property
    @pulumi.getter(name="dnsValidationRecords")
    def dns_validation_records(self) -> pulumi.Output[Sequence['outputs.DomainDnsValidationRecord']]:
        """
        DNS validation records required for SSL certificate validation. Present for domains pending certificate validation. Each record contains the CNAME information needed to validate domain ownership.
        """
        return pulumi.get(self, "dns_validation_records")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Output[_builtins.str]:
        """
        Domain name
        """
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter
    def organization(self) -> pulumi.Output[_builtins.str]:
        """
        Organization identifier
        """
        return pulumi.get(self, "organization")

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Output[_builtins.str]:
        """
        Project identifier
        """
        return pulumi.get(self, "project")

