# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetProjectResult',
    'AwaitableGetProjectResult',
    'get_project',
    'get_project_output',
]

@pulumi.output_type
class GetProjectResult:
    """
    A collection of values returned by getProject.
    """
    def __init__(__self__, created_at=None, git_url=None, id=None, machine_name=None, name=None, organization_id=None, region=None, security_score=None, updated_at=None, uuid=None, with_token=None, write_token=None):
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if git_url and not isinstance(git_url, str):
            raise TypeError("Expected argument 'git_url' to be a str")
        pulumi.set(__self__, "git_url", git_url)
        if id and not isinstance(id, int):
            raise TypeError("Expected argument 'id' to be a int")
        pulumi.set(__self__, "id", id)
        if machine_name and not isinstance(machine_name, str):
            raise TypeError("Expected argument 'machine_name' to be a str")
        pulumi.set(__self__, "machine_name", machine_name)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if organization_id and not isinstance(organization_id, int):
            raise TypeError("Expected argument 'organization_id' to be a int")
        pulumi.set(__self__, "organization_id", organization_id)
        if region and not isinstance(region, str):
            raise TypeError("Expected argument 'region' to be a str")
        pulumi.set(__self__, "region", region)
        if security_score and not isinstance(security_score, str):
            raise TypeError("Expected argument 'security_score' to be a str")
        pulumi.set(__self__, "security_score", security_score)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)
        if uuid and not isinstance(uuid, str):
            raise TypeError("Expected argument 'uuid' to be a str")
        pulumi.set(__self__, "uuid", uuid)
        if with_token and not isinstance(with_token, bool):
            raise TypeError("Expected argument 'with_token' to be a bool")
        pulumi.set(__self__, "with_token", with_token)
        if write_token and not isinstance(write_token, str):
            raise TypeError("Expected argument 'write_token' to be a str")
        pulumi.set(__self__, "write_token", write_token)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> _builtins.str:
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="gitUrl")
    def git_url(self) -> _builtins.str:
        return pulumi.get(self, "git_url")

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.int:
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter(name="machineName")
    def machine_name(self) -> _builtins.str:
        return pulumi.get(self, "machine_name")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="organizationId")
    def organization_id(self) -> _builtins.int:
        return pulumi.get(self, "organization_id")

    @_builtins.property
    @pulumi.getter
    def region(self) -> _builtins.str:
        return pulumi.get(self, "region")

    @_builtins.property
    @pulumi.getter(name="securityScore")
    def security_score(self) -> _builtins.str:
        return pulumi.get(self, "security_score")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> _builtins.str:
        return pulumi.get(self, "updated_at")

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> _builtins.str:
        return pulumi.get(self, "uuid")

    @_builtins.property
    @pulumi.getter(name="withToken")
    def with_token(self) -> Optional[_builtins.bool]:
        return pulumi.get(self, "with_token")

    @_builtins.property
    @pulumi.getter(name="writeToken")
    def write_token(self) -> _builtins.str:
        return pulumi.get(self, "write_token")


class AwaitableGetProjectResult(GetProjectResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetProjectResult(
            created_at=self.created_at,
            git_url=self.git_url,
            id=self.id,
            machine_name=self.machine_name,
            name=self.name,
            organization_id=self.organization_id,
            region=self.region,
            security_score=self.security_score,
            updated_at=self.updated_at,
            uuid=self.uuid,
            with_token=self.with_token,
            write_token=self.write_token)


def get_project(machine_name: Optional[_builtins.str] = None,
                with_token: Optional[_builtins.bool] = None,
                opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetProjectResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['machineName'] = machine_name
    __args__['withToken'] = with_token
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('quant:index:getProject', __args__, opts=opts, typ=GetProjectResult).value

    return AwaitableGetProjectResult(
        created_at=pulumi.get(__ret__, 'created_at'),
        git_url=pulumi.get(__ret__, 'git_url'),
        id=pulumi.get(__ret__, 'id'),
        machine_name=pulumi.get(__ret__, 'machine_name'),
        name=pulumi.get(__ret__, 'name'),
        organization_id=pulumi.get(__ret__, 'organization_id'),
        region=pulumi.get(__ret__, 'region'),
        security_score=pulumi.get(__ret__, 'security_score'),
        updated_at=pulumi.get(__ret__, 'updated_at'),
        uuid=pulumi.get(__ret__, 'uuid'),
        with_token=pulumi.get(__ret__, 'with_token'),
        write_token=pulumi.get(__ret__, 'write_token'))
def get_project_output(machine_name: Optional[pulumi.Input[_builtins.str]] = None,
                       with_token: Optional[pulumi.Input[Optional[_builtins.bool]]] = None,
                       opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetProjectResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['machineName'] = machine_name
    __args__['withToken'] = with_token
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('quant:index:getProject', __args__, opts=opts, typ=GetProjectResult)
    return __ret__.apply(lambda __response__: GetProjectResult(
        created_at=pulumi.get(__response__, 'created_at'),
        git_url=pulumi.get(__response__, 'git_url'),
        id=pulumi.get(__response__, 'id'),
        machine_name=pulumi.get(__response__, 'machine_name'),
        name=pulumi.get(__response__, 'name'),
        organization_id=pulumi.get(__response__, 'organization_id'),
        region=pulumi.get(__response__, 'region'),
        security_score=pulumi.get(__response__, 'security_score'),
        updated_at=pulumi.get(__response__, 'updated_at'),
        uuid=pulumi.get(__response__, 'uuid'),
        with_token=pulumi.get(__response__, 'with_token'),
        write_token=pulumi.get(__response__, 'write_token')))
