# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['KvItemArgs', 'KvItem']

@pulumi.input_type
class KvItemArgs:
    def __init__(__self__, *,
                 key: pulumi.Input[_builtins.str],
                 project: pulumi.Input[_builtins.str],
                 store_id: pulumi.Input[_builtins.str],
                 value: pulumi.Input[_builtins.str],
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 secret: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a KvItem resource.

        :param pulumi.Input[_builtins.str] key: Item key
        :param pulumi.Input[_builtins.str] project: Project machine name
        :param pulumi.Input[_builtins.str] store_id: KV store ID
        :param pulumi.Input[_builtins.str] value: Item value (can be a JSON string)
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[_builtins.bool] secret: Store as secret with KMS encryption
        """
        pulumi.set(__self__, "key", key)
        pulumi.set(__self__, "project", project)
        pulumi.set(__self__, "store_id", store_id)
        pulumi.set(__self__, "value", value)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if secret is not None:
            pulumi.set(__self__, "secret", secret)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[_builtins.str]:
        """
        Item key
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Input[_builtins.str]:
        """
        Project machine name
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter(name="storeId")
    def store_id(self) -> pulumi.Input[_builtins.str]:
        """
        KV store ID
        """
        return pulumi.get(self, "store_id")

    @store_id.setter
    def store_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "store_id", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str]:
        """
        Item value (can be a JSON string)
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "value", value)

    @_builtins.property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Organization machine name (defaults to provider organization)
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization", value)

    @_builtins.property
    @pulumi.getter
    def secret(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Store as secret with KMS encryption
        """
        return pulumi.get(self, "secret")

    @secret.setter
    def secret(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "secret", value)


@pulumi.input_type
class _KvItemState:
    def __init__(__self__, *,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 secret: Optional[pulumi.Input[_builtins.bool]] = None,
                 store_id: Optional[pulumi.Input[_builtins.str]] = None,
                 value: Optional[pulumi.Input[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering KvItem resources.

        :param pulumi.Input[_builtins.str] key: Item key
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[_builtins.str] project: Project machine name
        :param pulumi.Input[_builtins.bool] secret: Store as secret with KMS encryption
        :param pulumi.Input[_builtins.str] store_id: KV store ID
        :param pulumi.Input[_builtins.str] value: Item value (can be a JSON string)
        """
        if key is not None:
            pulumi.set(__self__, "key", key)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if project is not None:
            pulumi.set(__self__, "project", project)
        if secret is not None:
            pulumi.set(__self__, "secret", secret)
        if store_id is not None:
            pulumi.set(__self__, "store_id", store_id)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Item key
        """
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Organization machine name (defaults to provider organization)
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization", value)

    @_builtins.property
    @pulumi.getter
    def project(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Project machine name
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter
    def secret(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Store as secret with KMS encryption
        """
        return pulumi.get(self, "secret")

    @secret.setter
    def secret(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "secret", value)

    @_builtins.property
    @pulumi.getter(name="storeId")
    def store_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        KV store ID
        """
        return pulumi.get(self, "store_id")

    @store_id.setter
    def store_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "store_id", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Item value (can be a JSON string)
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "value", value)


@pulumi.type_token("quant:index:KvItem")
class KvItem(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 secret: Optional[pulumi.Input[_builtins.bool]] = None,
                 store_id: Optional[pulumi.Input[_builtins.str]] = None,
                 value: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a KvItem resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] key: Item key
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[_builtins.str] project: Project machine name
        :param pulumi.Input[_builtins.bool] secret: Store as secret with KMS encryption
        :param pulumi.Input[_builtins.str] store_id: KV store ID
        :param pulumi.Input[_builtins.str] value: Item value (can be a JSON string)
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: KvItemArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a KvItem resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param KvItemArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(KvItemArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 key: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 secret: Optional[pulumi.Input[_builtins.bool]] = None,
                 store_id: Optional[pulumi.Input[_builtins.str]] = None,
                 value: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = KvItemArgs.__new__(KvItemArgs)

            if key is None and not opts.urn:
                raise TypeError("Missing required property 'key'")
            __props__.__dict__["key"] = key
            __props__.__dict__["organization"] = organization
            if project is None and not opts.urn:
                raise TypeError("Missing required property 'project'")
            __props__.__dict__["project"] = project
            __props__.__dict__["secret"] = secret
            if store_id is None and not opts.urn:
                raise TypeError("Missing required property 'store_id'")
            __props__.__dict__["store_id"] = store_id
            if value is None and not opts.urn:
                raise TypeError("Missing required property 'value'")
            __props__.__dict__["value"] = None if value is None else pulumi.Output.secret(value)
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["value"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(KvItem, __self__).__init__(
            'quant:index:KvItem',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            key: Optional[pulumi.Input[_builtins.str]] = None,
            organization: Optional[pulumi.Input[_builtins.str]] = None,
            project: Optional[pulumi.Input[_builtins.str]] = None,
            secret: Optional[pulumi.Input[_builtins.bool]] = None,
            store_id: Optional[pulumi.Input[_builtins.str]] = None,
            value: Optional[pulumi.Input[_builtins.str]] = None) -> 'KvItem':
        """
        Get an existing KvItem resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] key: Item key
        :param pulumi.Input[_builtins.str] organization: Organization machine name (defaults to provider organization)
        :param pulumi.Input[_builtins.str] project: Project machine name
        :param pulumi.Input[_builtins.bool] secret: Store as secret with KMS encryption
        :param pulumi.Input[_builtins.str] store_id: KV store ID
        :param pulumi.Input[_builtins.str] value: Item value (can be a JSON string)
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _KvItemState.__new__(_KvItemState)

        __props__.__dict__["key"] = key
        __props__.__dict__["organization"] = organization
        __props__.__dict__["project"] = project
        __props__.__dict__["secret"] = secret
        __props__.__dict__["store_id"] = store_id
        __props__.__dict__["value"] = value
        return KvItem(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Output[_builtins.str]:
        """
        Item key
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def organization(self) -> pulumi.Output[_builtins.str]:
        """
        Organization machine name (defaults to provider organization)
        """
        return pulumi.get(self, "organization")

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Output[_builtins.str]:
        """
        Project machine name
        """
        return pulumi.get(self, "project")

    @_builtins.property
    @pulumi.getter
    def secret(self) -> pulumi.Output[_builtins.bool]:
        """
        Store as secret with KMS encryption
        """
        return pulumi.get(self, "secret")

    @_builtins.property
    @pulumi.getter(name="storeId")
    def store_id(self) -> pulumi.Output[_builtins.str]:
        """
        KV store ID
        """
        return pulumi.get(self, "store_id")

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Output[_builtins.str]:
        """
        Item value (can be a JSON string)
        """
        return pulumi.get(self, "value")

