# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'AiGovernanceSpendLimits',
    'AiSkillSource',
    'CrawlerAssets',
    'CrawlerAssetsNetworkIntercept',
    'CrawlerAssetsParser',
    'CrawlerSitemap',
    'DomainDnsGoLiveRecord',
    'DomainDnsValidationRecord',
    'RuleAuthActionConfig',
    'RuleBotChallengeActionConfig',
    'RuleContentFilterActionConfig',
    'RuleCustomResponseActionConfig',
    'RuleFunctionActionConfig',
    'RuleHeadersActionConfig',
    'RuleProxyActionConfig',
    'RuleProxyActionConfigNotifyConfig',
    'RuleProxyActionConfigQuantCloudSelection',
    'RuleProxyActionConfigWafConfig',
    'RuleProxyActionConfigWafConfigBlockLists',
    'RuleProxyActionConfigWafConfigHttpbl',
    'RuleProxyActionConfigWafConfigThreshold',
    'RuleProxyWafConfig',
    'RuleProxyWafConfigBlockLists',
    'RuleProxyWafConfigHttpbl',
    'RuleProxyWafConfigThreshold',
    'RuleRedirectActionConfig',
    'RuleServeStaticActionConfig',
    'GetProjectsProjectResult',
]

@pulumi.output_type
class AiGovernanceSpendLimits(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "dailyBudgetCents":
            suggest = "daily_budget_cents"
        elif key == "monthlyBudgetCents":
            suggest = "monthly_budget_cents"
        elif key == "perUserDailyBudgetCents":
            suggest = "per_user_daily_budget_cents"
        elif key == "perUserMonthlyBudgetCents":
            suggest = "per_user_monthly_budget_cents"
        elif key == "warningThresholdPercent":
            suggest = "warning_threshold_percent"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in AiGovernanceSpendLimits. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        AiGovernanceSpendLimits.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        AiGovernanceSpendLimits.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 daily_budget_cents: Optional[_builtins.int] = None,
                 monthly_budget_cents: Optional[_builtins.int] = None,
                 per_user_daily_budget_cents: Optional[_builtins.int] = None,
                 per_user_monthly_budget_cents: Optional[_builtins.int] = None,
                 warning_threshold_percent: Optional[_builtins.int] = None):
        """
        :param _builtins.int daily_budget_cents: Daily budget in cents
        :param _builtins.int monthly_budget_cents: Monthly budget in cents
        :param _builtins.int per_user_daily_budget_cents: Per-user daily budget in cents
        :param _builtins.int per_user_monthly_budget_cents: Per-user monthly budget in cents
        :param _builtins.int warning_threshold_percent: Warning threshold as a percentage of budget (0-100)
        """
        if daily_budget_cents is not None:
            pulumi.set(__self__, "daily_budget_cents", daily_budget_cents)
        if monthly_budget_cents is not None:
            pulumi.set(__self__, "monthly_budget_cents", monthly_budget_cents)
        if per_user_daily_budget_cents is not None:
            pulumi.set(__self__, "per_user_daily_budget_cents", per_user_daily_budget_cents)
        if per_user_monthly_budget_cents is not None:
            pulumi.set(__self__, "per_user_monthly_budget_cents", per_user_monthly_budget_cents)
        if warning_threshold_percent is not None:
            pulumi.set(__self__, "warning_threshold_percent", warning_threshold_percent)

    @_builtins.property
    @pulumi.getter(name="dailyBudgetCents")
    def daily_budget_cents(self) -> Optional[_builtins.int]:
        """
        Daily budget in cents
        """
        return pulumi.get(self, "daily_budget_cents")

    @_builtins.property
    @pulumi.getter(name="monthlyBudgetCents")
    def monthly_budget_cents(self) -> Optional[_builtins.int]:
        """
        Monthly budget in cents
        """
        return pulumi.get(self, "monthly_budget_cents")

    @_builtins.property
    @pulumi.getter(name="perUserDailyBudgetCents")
    def per_user_daily_budget_cents(self) -> Optional[_builtins.int]:
        """
        Per-user daily budget in cents
        """
        return pulumi.get(self, "per_user_daily_budget_cents")

    @_builtins.property
    @pulumi.getter(name="perUserMonthlyBudgetCents")
    def per_user_monthly_budget_cents(self) -> Optional[_builtins.int]:
        """
        Per-user monthly budget in cents
        """
        return pulumi.get(self, "per_user_monthly_budget_cents")

    @_builtins.property
    @pulumi.getter(name="warningThresholdPercent")
    def warning_threshold_percent(self) -> Optional[_builtins.int]:
        """
        Warning threshold as a percentage of budget (0-100)
        """
        return pulumi.get(self, "warning_threshold_percent")


@pulumi.output_type
class AiSkillSource(dict):
    def __init__(__self__, *,
                 type: _builtins.str,
                 version: _builtins.str,
                 path: Optional[_builtins.str] = None,
                 repo: Optional[_builtins.str] = None,
                 url: Optional[_builtins.str] = None):
        """
        :param _builtins.str type: Source type: `github` or `skills.sh`
        :param _builtins.str version: Pinned version tag
        :param _builtins.str path: File path within the repository
        :param _builtins.str repo: GitHub repository in `org/repo` format
        :param _builtins.str url: skills.sh URL
        """
        pulumi.set(__self__, "type", type)
        pulumi.set(__self__, "version", version)
        if path is not None:
            pulumi.set(__self__, "path", path)
        if repo is not None:
            pulumi.set(__self__, "repo", repo)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def type(self) -> _builtins.str:
        """
        Source type: `github` or `skills.sh`
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def version(self) -> _builtins.str:
        """
        Pinned version tag
        """
        return pulumi.get(self, "version")

    @_builtins.property
    @pulumi.getter
    def path(self) -> Optional[_builtins.str]:
        """
        File path within the repository
        """
        return pulumi.get(self, "path")

    @_builtins.property
    @pulumi.getter
    def repo(self) -> Optional[_builtins.str]:
        """
        GitHub repository in `org/repo` format
        """
        return pulumi.get(self, "repo")

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[_builtins.str]:
        """
        skills.sh URL
        """
        return pulumi.get(self, "url")


@pulumi.output_type
class CrawlerAssets(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "networkIntercept":
            suggest = "network_intercept"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in CrawlerAssets. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        CrawlerAssets.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        CrawlerAssets.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 network_intercept: Optional['outputs.CrawlerAssetsNetworkIntercept'] = None,
                 parser: Optional['outputs.CrawlerAssetsParser'] = None):
        """
        :param 'CrawlerAssetsNetworkInterceptArgs' network_intercept: Network intercept configuration for asset collection
        :param 'CrawlerAssetsParserArgs' parser: Parser configuration for asset extraction
        """
        if network_intercept is not None:
            pulumi.set(__self__, "network_intercept", network_intercept)
        if parser is not None:
            pulumi.set(__self__, "parser", parser)

    @_builtins.property
    @pulumi.getter(name="networkIntercept")
    def network_intercept(self) -> Optional['outputs.CrawlerAssetsNetworkIntercept']:
        """
        Network intercept configuration for asset collection
        """
        return pulumi.get(self, "network_intercept")

    @_builtins.property
    @pulumi.getter
    def parser(self) -> Optional['outputs.CrawlerAssetsParser']:
        """
        Parser configuration for asset extraction
        """
        return pulumi.get(self, "parser")


@pulumi.output_type
class CrawlerAssetsNetworkIntercept(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "executeJs":
            suggest = "execute_js"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in CrawlerAssetsNetworkIntercept. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        CrawlerAssetsNetworkIntercept.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        CrawlerAssetsNetworkIntercept.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 enabled: Optional[_builtins.bool] = None,
                 execute_js: Optional[_builtins.bool] = None,
                 timeout: Optional[_builtins.int] = None):
        """
        :param _builtins.bool enabled: Enable network intercept
        :param _builtins.bool execute_js: Execute JavaScript during asset collection
        :param _builtins.int timeout: Request timeout in seconds
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if execute_js is not None:
            pulumi.set(__self__, "execute_js", execute_js)
        if timeout is not None:
            pulumi.set(__self__, "timeout", timeout)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[_builtins.bool]:
        """
        Enable network intercept
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="executeJs")
    def execute_js(self) -> Optional[_builtins.bool]:
        """
        Execute JavaScript during asset collection
        """
        return pulumi.get(self, "execute_js")

    @_builtins.property
    @pulumi.getter
    def timeout(self) -> Optional[_builtins.int]:
        """
        Request timeout in seconds
        """
        return pulumi.get(self, "timeout")


@pulumi.output_type
class CrawlerAssetsParser(dict):
    def __init__(__self__, *,
                 enabled: Optional[_builtins.bool] = None):
        """
        :param _builtins.bool enabled: Enable parser
        """
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> Optional[_builtins.bool]:
        """
        Enable parser
        """
        return pulumi.get(self, "enabled")


@pulumi.output_type
class CrawlerSitemap(dict):
    def __init__(__self__, *,
                 recursive: Optional[_builtins.bool] = None,
                 url: Optional[_builtins.str] = None):
        """
        :param _builtins.bool recursive: Recursively follow sitemap links
        :param _builtins.str url: Sitemap URL
        """
        if recursive is not None:
            pulumi.set(__self__, "recursive", recursive)
        if url is not None:
            pulumi.set(__self__, "url", url)

    @_builtins.property
    @pulumi.getter
    def recursive(self) -> Optional[_builtins.bool]:
        """
        Recursively follow sitemap links
        """
        return pulumi.get(self, "recursive")

    @_builtins.property
    @pulumi.getter
    def url(self) -> Optional[_builtins.str]:
        """
        Sitemap URL
        """
        return pulumi.get(self, "url")


@pulumi.output_type
class DomainDnsGoLiveRecord(dict):
    def __init__(__self__, *,
                 description: Optional[_builtins.str] = None,
                 name: Optional[_builtins.str] = None,
                 type: Optional[_builtins.str] = None,
                 value: Optional[_builtins.str] = None):
        """
        :param _builtins.str description: Human-readable instructions for configuring this DNS record
        :param _builtins.str name: DNS record name/host (@ for apex/root domains, subdomain name for subdomains)
        :param _builtins.str type: DNS record type (CNAME, A, or ALIAS)
        :param _builtins.str value: DNS record value (IP addresses for A records, domain name for CNAME/ALIAS)
        """
        if description is not None:
            pulumi.set(__self__, "description", description)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]:
        """
        Human-readable instructions for configuring this DNS record
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        """
        DNS record name/host (@ for apex/root domains, subdomain name for subdomains)
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        """
        DNS record type (CNAME, A, or ALIAS)
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]:
        """
        DNS record value (IP addresses for A records, domain name for CNAME/ALIAS)
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class DomainDnsValidationRecord(dict):
    def __init__(__self__, *,
                 name: Optional[_builtins.str] = None,
                 type: Optional[_builtins.str] = None,
                 value: Optional[_builtins.str] = None):
        """
        :param _builtins.str name: DNS record name (host/subdomain)
        :param _builtins.str type: DNS record type (typically CNAME)
        :param _builtins.str value: DNS record value to point to
        """
        if name is not None:
            pulumi.set(__self__, "name", name)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[_builtins.str]:
        """
        DNS record name (host/subdomain)
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        """
        DNS record type (typically CNAME)
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]:
        """
        DNS record value to point to
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class RuleAuthActionConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "authPass":
            suggest = "auth_pass"
        elif key == "authUser":
            suggest = "auth_user"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleAuthActionConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleAuthActionConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleAuthActionConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 auth_pass: Optional[_builtins.str] = None,
                 auth_user: Optional[_builtins.str] = None):
        """
        :param _builtins.str auth_pass: Authentication password
        :param _builtins.str auth_user: Authentication username
        """
        if auth_pass is not None:
            pulumi.set(__self__, "auth_pass", auth_pass)
        if auth_user is not None:
            pulumi.set(__self__, "auth_user", auth_user)

    @_builtins.property
    @pulumi.getter(name="authPass")
    def auth_pass(self) -> Optional[_builtins.str]:
        """
        Authentication password
        """
        return pulumi.get(self, "auth_pass")

    @_builtins.property
    @pulumi.getter(name="authUser")
    def auth_user(self) -> Optional[_builtins.str]:
        """
        Authentication username
        """
        return pulumi.get(self, "auth_user")


@pulumi.output_type
class RuleBotChallengeActionConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "robotChallengeChallengeTtl":
            suggest = "robot_challenge_challenge_ttl"
        elif key == "robotChallengeType":
            suggest = "robot_challenge_type"
        elif key == "robotChallengeVerificationTtl":
            suggest = "robot_challenge_verification_ttl"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleBotChallengeActionConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleBotChallengeActionConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleBotChallengeActionConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 robot_challenge_challenge_ttl: Optional[_builtins.int] = None,
                 robot_challenge_type: Optional[_builtins.str] = None,
                 robot_challenge_verification_ttl: Optional[_builtins.int] = None):
        """
        :param _builtins.int robot_challenge_challenge_ttl: Challenge TTL in seconds
        :param _builtins.str robot_challenge_type: Challenge type (invisible or checkbox)
        :param _builtins.int robot_challenge_verification_ttl: Verification TTL in seconds
        """
        if robot_challenge_challenge_ttl is not None:
            pulumi.set(__self__, "robot_challenge_challenge_ttl", robot_challenge_challenge_ttl)
        if robot_challenge_type is not None:
            pulumi.set(__self__, "robot_challenge_type", robot_challenge_type)
        if robot_challenge_verification_ttl is not None:
            pulumi.set(__self__, "robot_challenge_verification_ttl", robot_challenge_verification_ttl)

    @_builtins.property
    @pulumi.getter(name="robotChallengeChallengeTtl")
    def robot_challenge_challenge_ttl(self) -> Optional[_builtins.int]:
        """
        Challenge TTL in seconds
        """
        return pulumi.get(self, "robot_challenge_challenge_ttl")

    @_builtins.property
    @pulumi.getter(name="robotChallengeType")
    def robot_challenge_type(self) -> Optional[_builtins.str]:
        """
        Challenge type (invisible or checkbox)
        """
        return pulumi.get(self, "robot_challenge_type")

    @_builtins.property
    @pulumi.getter(name="robotChallengeVerificationTtl")
    def robot_challenge_verification_ttl(self) -> Optional[_builtins.int]:
        """
        Verification TTL in seconds
        """
        return pulumi.get(self, "robot_challenge_verification_ttl")


@pulumi.output_type
class RuleContentFilterActionConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "fnUuid":
            suggest = "fn_uuid"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleContentFilterActionConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleContentFilterActionConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleContentFilterActionConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 fn_uuid: Optional[_builtins.str] = None):
        """
        :param _builtins.str fn_uuid: Function UUID
        """
        if fn_uuid is not None:
            pulumi.set(__self__, "fn_uuid", fn_uuid)

    @_builtins.property
    @pulumi.getter(name="fnUuid")
    def fn_uuid(self) -> Optional[_builtins.str]:
        """
        Function UUID
        """
        return pulumi.get(self, "fn_uuid")


@pulumi.output_type
class RuleCustomResponseActionConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "customResponseBody":
            suggest = "custom_response_body"
        elif key == "customResponseStatusCode":
            suggest = "custom_response_status_code"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleCustomResponseActionConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleCustomResponseActionConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleCustomResponseActionConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 custom_response_body: Optional[_builtins.str] = None,
                 custom_response_status_code: Optional[_builtins.int] = None):
        """
        :param _builtins.str custom_response_body: Custom response body content
        :param _builtins.int custom_response_status_code: HTTP status code for custom response
        """
        if custom_response_body is not None:
            pulumi.set(__self__, "custom_response_body", custom_response_body)
        if custom_response_status_code is not None:
            pulumi.set(__self__, "custom_response_status_code", custom_response_status_code)

    @_builtins.property
    @pulumi.getter(name="customResponseBody")
    def custom_response_body(self) -> Optional[_builtins.str]:
        """
        Custom response body content
        """
        return pulumi.get(self, "custom_response_body")

    @_builtins.property
    @pulumi.getter(name="customResponseStatusCode")
    def custom_response_status_code(self) -> Optional[_builtins.int]:
        """
        HTTP status code for custom response
        """
        return pulumi.get(self, "custom_response_status_code")


@pulumi.output_type
class RuleFunctionActionConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "fnUuid":
            suggest = "fn_uuid"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleFunctionActionConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleFunctionActionConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleFunctionActionConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 fn_uuid: Optional[_builtins.str] = None):
        """
        :param _builtins.str fn_uuid: Function UUID
        """
        if fn_uuid is not None:
            pulumi.set(__self__, "fn_uuid", fn_uuid)

    @_builtins.property
    @pulumi.getter(name="fnUuid")
    def fn_uuid(self) -> Optional[_builtins.str]:
        """
        Function UUID
        """
        return pulumi.get(self, "fn_uuid")


@pulumi.output_type
class RuleHeadersActionConfig(dict):
    def __init__(__self__, *,
                 headers: Optional[Mapping[str, _builtins.str]] = None):
        """
        :param Mapping[str, _builtins.str] headers: Headers to set
        """
        if headers is not None:
            pulumi.set(__self__, "headers", headers)

    @_builtins.property
    @pulumi.getter
    def headers(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Headers to set
        """
        return pulumi.get(self, "headers")


@pulumi.output_type
class RuleProxyActionConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "applicationContainer":
            suggest = "application_container"
        elif key == "applicationEnvironment":
            suggest = "application_environment"
        elif key == "applicationName":
            suggest = "application_name"
        elif key == "applicationPort":
            suggest = "application_port"
        elif key == "applicationProxy":
            suggest = "application_proxy"
        elif key == "authPass":
            suggest = "auth_pass"
        elif key == "authUser":
            suggest = "auth_user"
        elif key == "cacheLifetime":
            suggest = "cache_lifetime"
        elif key == "disableSslVerify":
            suggest = "disable_ssl_verify"
        elif key == "failoverLifetime":
            suggest = "failover_lifetime"
        elif key == "failoverMode":
            suggest = "failover_mode"
        elif key == "failoverOriginStatusCodes":
            suggest = "failover_origin_status_codes"
        elif key == "failoverOriginTtfb":
            suggest = "failover_origin_ttfb"
        elif key == "injectHeaders":
            suggest = "inject_headers"
        elif key == "notifyConfig":
            suggest = "notify_config"
        elif key == "onlyProxy404":
            suggest = "only_proxy404"
        elif key == "originTimeout":
            suggest = "origin_timeout"
        elif key == "proxyAlertEnabled":
            suggest = "proxy_alert_enabled"
        elif key == "proxyInlineFnEnabled":
            suggest = "proxy_inline_fn_enabled"
        elif key == "proxyStripHeaders":
            suggest = "proxy_strip_headers"
        elif key == "proxyStripRequestHeaders":
            suggest = "proxy_strip_request_headers"
        elif key == "quantCloudSelection":
            suggest = "quant_cloud_selection"
        elif key == "staticErrorPage":
            suggest = "static_error_page"
        elif key == "staticErrorPageStatusCodes":
            suggest = "static_error_page_status_codes"
        elif key == "wafConfig":
            suggest = "waf_config"
        elif key == "wafEnabled":
            suggest = "waf_enabled"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleProxyActionConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleProxyActionConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleProxyActionConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 application_container: Optional[_builtins.str] = None,
                 application_environment: Optional[_builtins.str] = None,
                 application_name: Optional[_builtins.str] = None,
                 application_port: Optional[_builtins.int] = None,
                 application_proxy: Optional[_builtins.bool] = None,
                 auth_pass: Optional[_builtins.str] = None,
                 auth_user: Optional[_builtins.str] = None,
                 cache_lifetime: Optional[_builtins.str] = None,
                 disable_ssl_verify: Optional[_builtins.bool] = None,
                 failover_lifetime: Optional[_builtins.str] = None,
                 failover_mode: Optional[_builtins.bool] = None,
                 failover_origin_status_codes: Optional[Sequence[_builtins.str]] = None,
                 failover_origin_ttfb: Optional[_builtins.str] = None,
                 host: Optional[_builtins.str] = None,
                 inject_headers: Optional[Mapping[str, _builtins.str]] = None,
                 notify: Optional[_builtins.str] = None,
                 notify_config: Optional['outputs.RuleProxyActionConfigNotifyConfig'] = None,
                 only_proxy404: Optional[_builtins.bool] = None,
                 origin_timeout: Optional[_builtins.str] = None,
                 proxy_alert_enabled: Optional[_builtins.bool] = None,
                 proxy_inline_fn_enabled: Optional[_builtins.bool] = None,
                 proxy_strip_headers: Optional[Sequence[_builtins.str]] = None,
                 proxy_strip_request_headers: Optional[Sequence[_builtins.str]] = None,
                 quant_cloud_selection: Optional['outputs.RuleProxyActionConfigQuantCloudSelection'] = None,
                 static_error_page: Optional[_builtins.str] = None,
                 static_error_page_status_codes: Optional[Sequence[_builtins.str]] = None,
                 to: Optional[_builtins.str] = None,
                 waf_config: Optional['outputs.RuleProxyActionConfigWafConfig'] = None,
                 waf_enabled: Optional[_builtins.bool] = None):
        """
        :param _builtins.str application_container: Quant Cloud application container (required when application_proxy is true)
        :param _builtins.str application_environment: Quant Cloud application environment (required when application_proxy is true)
        :param _builtins.str application_name: Quant Cloud application name (required when application_proxy is true)
        :param _builtins.int application_port: Quant Cloud application port (required when application_proxy is true)
        :param _builtins.bool application_proxy: Enable Quant Cloud application proxy mode
        :param _builtins.str auth_pass: Basic auth password
        :param _builtins.str auth_user: Basic auth username
        :param _builtins.str cache_lifetime: Cache lifetime
        :param _builtins.bool disable_ssl_verify: Disable SSL verification
        :param _builtins.str failover_lifetime: Failover cache lifetime
        :param _builtins.bool failover_mode: Enable failover mode
        :param Sequence[_builtins.str] failover_origin_status_codes: Status codes for failover (default: 200,404,301,302,304)
        :param _builtins.str failover_origin_ttfb: Failover TTFB threshold
        :param _builtins.str host: Host header override
        :param Mapping[str, _builtins.str] inject_headers: Headers to inject
        :param _builtins.str notify: Notification type (none, slack)
        :param 'RuleProxyActionConfigNotifyConfigArgs' notify_config: Notification configuration (required when notify is slack)
        :param _builtins.bool only_proxy404: Only proxy 404 responses
        :param _builtins.str origin_timeout: Origin timeout
        :param _builtins.bool proxy_alert_enabled: Proxy alert enabled
        :param _builtins.bool proxy_inline_fn_enabled: Proxy inline function enabled
        :param Sequence[_builtins.str] proxy_strip_headers: Headers to strip from response
        :param Sequence[_builtins.str] proxy_strip_request_headers: Headers to strip from request
        :param 'RuleProxyActionConfigQuantCloudSelectionArgs' quant_cloud_selection: Quant Cloud application proxy selection (populated automatically when application_proxy is enabled)
        :param _builtins.str static_error_page: Static error page content (HTML) to serve on origin errors
        :param Sequence[_builtins.str] static_error_page_status_codes: Origin status codes that trigger static error page
        :param _builtins.str to: Target URL to proxy to
        :param 'RuleProxyActionConfigWafConfigArgs' waf_config: Web Application Firewall configuration
        :param _builtins.bool waf_enabled: WAF enabled
        """
        if application_container is not None:
            pulumi.set(__self__, "application_container", application_container)
        if application_environment is not None:
            pulumi.set(__self__, "application_environment", application_environment)
        if application_name is not None:
            pulumi.set(__self__, "application_name", application_name)
        if application_port is not None:
            pulumi.set(__self__, "application_port", application_port)
        if application_proxy is not None:
            pulumi.set(__self__, "application_proxy", application_proxy)
        if auth_pass is not None:
            pulumi.set(__self__, "auth_pass", auth_pass)
        if auth_user is not None:
            pulumi.set(__self__, "auth_user", auth_user)
        if cache_lifetime is not None:
            pulumi.set(__self__, "cache_lifetime", cache_lifetime)
        if disable_ssl_verify is not None:
            pulumi.set(__self__, "disable_ssl_verify", disable_ssl_verify)
        if failover_lifetime is not None:
            pulumi.set(__self__, "failover_lifetime", failover_lifetime)
        if failover_mode is not None:
            pulumi.set(__self__, "failover_mode", failover_mode)
        if failover_origin_status_codes is not None:
            pulumi.set(__self__, "failover_origin_status_codes", failover_origin_status_codes)
        if failover_origin_ttfb is not None:
            pulumi.set(__self__, "failover_origin_ttfb", failover_origin_ttfb)
        if host is not None:
            pulumi.set(__self__, "host", host)
        if inject_headers is not None:
            pulumi.set(__self__, "inject_headers", inject_headers)
        if notify is not None:
            pulumi.set(__self__, "notify", notify)
        if notify_config is not None:
            pulumi.set(__self__, "notify_config", notify_config)
        if only_proxy404 is not None:
            pulumi.set(__self__, "only_proxy404", only_proxy404)
        if origin_timeout is not None:
            pulumi.set(__self__, "origin_timeout", origin_timeout)
        if proxy_alert_enabled is not None:
            pulumi.set(__self__, "proxy_alert_enabled", proxy_alert_enabled)
        if proxy_inline_fn_enabled is not None:
            pulumi.set(__self__, "proxy_inline_fn_enabled", proxy_inline_fn_enabled)
        if proxy_strip_headers is not None:
            pulumi.set(__self__, "proxy_strip_headers", proxy_strip_headers)
        if proxy_strip_request_headers is not None:
            pulumi.set(__self__, "proxy_strip_request_headers", proxy_strip_request_headers)
        if quant_cloud_selection is not None:
            pulumi.set(__self__, "quant_cloud_selection", quant_cloud_selection)
        if static_error_page is not None:
            pulumi.set(__self__, "static_error_page", static_error_page)
        if static_error_page_status_codes is not None:
            pulumi.set(__self__, "static_error_page_status_codes", static_error_page_status_codes)
        if to is not None:
            pulumi.set(__self__, "to", to)
        if waf_config is not None:
            pulumi.set(__self__, "waf_config", waf_config)
        if waf_enabled is not None:
            pulumi.set(__self__, "waf_enabled", waf_enabled)

    @_builtins.property
    @pulumi.getter(name="applicationContainer")
    def application_container(self) -> Optional[_builtins.str]:
        """
        Quant Cloud application container (required when application_proxy is true)
        """
        return pulumi.get(self, "application_container")

    @_builtins.property
    @pulumi.getter(name="applicationEnvironment")
    def application_environment(self) -> Optional[_builtins.str]:
        """
        Quant Cloud application environment (required when application_proxy is true)
        """
        return pulumi.get(self, "application_environment")

    @_builtins.property
    @pulumi.getter(name="applicationName")
    def application_name(self) -> Optional[_builtins.str]:
        """
        Quant Cloud application name (required when application_proxy is true)
        """
        return pulumi.get(self, "application_name")

    @_builtins.property
    @pulumi.getter(name="applicationPort")
    def application_port(self) -> Optional[_builtins.int]:
        """
        Quant Cloud application port (required when application_proxy is true)
        """
        return pulumi.get(self, "application_port")

    @_builtins.property
    @pulumi.getter(name="applicationProxy")
    def application_proxy(self) -> Optional[_builtins.bool]:
        """
        Enable Quant Cloud application proxy mode
        """
        return pulumi.get(self, "application_proxy")

    @_builtins.property
    @pulumi.getter(name="authPass")
    def auth_pass(self) -> Optional[_builtins.str]:
        """
        Basic auth password
        """
        return pulumi.get(self, "auth_pass")

    @_builtins.property
    @pulumi.getter(name="authUser")
    def auth_user(self) -> Optional[_builtins.str]:
        """
        Basic auth username
        """
        return pulumi.get(self, "auth_user")

    @_builtins.property
    @pulumi.getter(name="cacheLifetime")
    def cache_lifetime(self) -> Optional[_builtins.str]:
        """
        Cache lifetime
        """
        return pulumi.get(self, "cache_lifetime")

    @_builtins.property
    @pulumi.getter(name="disableSslVerify")
    def disable_ssl_verify(self) -> Optional[_builtins.bool]:
        """
        Disable SSL verification
        """
        return pulumi.get(self, "disable_ssl_verify")

    @_builtins.property
    @pulumi.getter(name="failoverLifetime")
    def failover_lifetime(self) -> Optional[_builtins.str]:
        """
        Failover cache lifetime
        """
        return pulumi.get(self, "failover_lifetime")

    @_builtins.property
    @pulumi.getter(name="failoverMode")
    def failover_mode(self) -> Optional[_builtins.bool]:
        """
        Enable failover mode
        """
        return pulumi.get(self, "failover_mode")

    @_builtins.property
    @pulumi.getter(name="failoverOriginStatusCodes")
    def failover_origin_status_codes(self) -> Optional[Sequence[_builtins.str]]:
        """
        Status codes for failover (default: 200,404,301,302,304)
        """
        return pulumi.get(self, "failover_origin_status_codes")

    @_builtins.property
    @pulumi.getter(name="failoverOriginTtfb")
    def failover_origin_ttfb(self) -> Optional[_builtins.str]:
        """
        Failover TTFB threshold
        """
        return pulumi.get(self, "failover_origin_ttfb")

    @_builtins.property
    @pulumi.getter
    def host(self) -> Optional[_builtins.str]:
        """
        Host header override
        """
        return pulumi.get(self, "host")

    @_builtins.property
    @pulumi.getter(name="injectHeaders")
    def inject_headers(self) -> Optional[Mapping[str, _builtins.str]]:
        """
        Headers to inject
        """
        return pulumi.get(self, "inject_headers")

    @_builtins.property
    @pulumi.getter
    def notify(self) -> Optional[_builtins.str]:
        """
        Notification type (none, slack)
        """
        return pulumi.get(self, "notify")

    @_builtins.property
    @pulumi.getter(name="notifyConfig")
    def notify_config(self) -> Optional['outputs.RuleProxyActionConfigNotifyConfig']:
        """
        Notification configuration (required when notify is slack)
        """
        return pulumi.get(self, "notify_config")

    @_builtins.property
    @pulumi.getter(name="onlyProxy404")
    def only_proxy404(self) -> Optional[_builtins.bool]:
        """
        Only proxy 404 responses
        """
        return pulumi.get(self, "only_proxy404")

    @_builtins.property
    @pulumi.getter(name="originTimeout")
    def origin_timeout(self) -> Optional[_builtins.str]:
        """
        Origin timeout
        """
        return pulumi.get(self, "origin_timeout")

    @_builtins.property
    @pulumi.getter(name="proxyAlertEnabled")
    def proxy_alert_enabled(self) -> Optional[_builtins.bool]:
        """
        Proxy alert enabled
        """
        return pulumi.get(self, "proxy_alert_enabled")

    @_builtins.property
    @pulumi.getter(name="proxyInlineFnEnabled")
    def proxy_inline_fn_enabled(self) -> Optional[_builtins.bool]:
        """
        Proxy inline function enabled
        """
        return pulumi.get(self, "proxy_inline_fn_enabled")

    @_builtins.property
    @pulumi.getter(name="proxyStripHeaders")
    def proxy_strip_headers(self) -> Optional[Sequence[_builtins.str]]:
        """
        Headers to strip from response
        """
        return pulumi.get(self, "proxy_strip_headers")

    @_builtins.property
    @pulumi.getter(name="proxyStripRequestHeaders")
    def proxy_strip_request_headers(self) -> Optional[Sequence[_builtins.str]]:
        """
        Headers to strip from request
        """
        return pulumi.get(self, "proxy_strip_request_headers")

    @_builtins.property
    @pulumi.getter(name="quantCloudSelection")
    def quant_cloud_selection(self) -> Optional['outputs.RuleProxyActionConfigQuantCloudSelection']:
        """
        Quant Cloud application proxy selection (populated automatically when application_proxy is enabled)
        """
        return pulumi.get(self, "quant_cloud_selection")

    @_builtins.property
    @pulumi.getter(name="staticErrorPage")
    def static_error_page(self) -> Optional[_builtins.str]:
        """
        Static error page content (HTML) to serve on origin errors
        """
        return pulumi.get(self, "static_error_page")

    @_builtins.property
    @pulumi.getter(name="staticErrorPageStatusCodes")
    def static_error_page_status_codes(self) -> Optional[Sequence[_builtins.str]]:
        """
        Origin status codes that trigger static error page
        """
        return pulumi.get(self, "static_error_page_status_codes")

    @_builtins.property
    @pulumi.getter
    def to(self) -> Optional[_builtins.str]:
        """
        Target URL to proxy to
        """
        return pulumi.get(self, "to")

    @_builtins.property
    @pulumi.getter(name="wafConfig")
    def waf_config(self) -> Optional['outputs.RuleProxyActionConfigWafConfig']:
        """
        Web Application Firewall configuration
        """
        return pulumi.get(self, "waf_config")

    @_builtins.property
    @pulumi.getter(name="wafEnabled")
    def waf_enabled(self) -> Optional[_builtins.bool]:
        """
        WAF enabled
        """
        return pulumi.get(self, "waf_enabled")


@pulumi.output_type
class RuleProxyActionConfigNotifyConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "webhookUrl":
            suggest = "webhook_url"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleProxyActionConfigNotifyConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleProxyActionConfigNotifyConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleProxyActionConfigNotifyConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 webhook_url: Optional[_builtins.str] = None):
        """
        :param _builtins.str webhook_url: Slack webhook URL
        """
        if webhook_url is not None:
            pulumi.set(__self__, "webhook_url", webhook_url)

    @_builtins.property
    @pulumi.getter(name="webhookUrl")
    def webhook_url(self) -> Optional[_builtins.str]:
        """
        Slack webhook URL
        """
        return pulumi.get(self, "webhook_url")


@pulumi.output_type
class RuleProxyActionConfigQuantCloudSelection(dict):
    def __init__(__self__, *,
                 app: Optional[_builtins.str] = None,
                 container: Optional[_builtins.str] = None,
                 env: Optional[_builtins.str] = None,
                 port: Optional[_builtins.int] = None):
        """
        :param _builtins.str app: Application name
        :param _builtins.str container: Container name
        :param _builtins.str env: Environment name
        :param _builtins.int port: Container port
        """
        if app is not None:
            pulumi.set(__self__, "app", app)
        if container is not None:
            pulumi.set(__self__, "container", container)
        if env is not None:
            pulumi.set(__self__, "env", env)
        if port is not None:
            pulumi.set(__self__, "port", port)

    @_builtins.property
    @pulumi.getter
    def app(self) -> Optional[_builtins.str]:
        """
        Application name
        """
        return pulumi.get(self, "app")

    @_builtins.property
    @pulumi.getter
    def container(self) -> Optional[_builtins.str]:
        """
        Container name
        """
        return pulumi.get(self, "container")

    @_builtins.property
    @pulumi.getter
    def env(self) -> Optional[_builtins.str]:
        """
        Environment name
        """
        return pulumi.get(self, "env")

    @_builtins.property
    @pulumi.getter
    def port(self) -> Optional[_builtins.int]:
        """
        Container port
        """
        return pulumi.get(self, "port")


@pulumi.output_type
class RuleProxyActionConfigWafConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "allowIps":
            suggest = "allow_ips"
        elif key == "allowRules":
            suggest = "allow_rules"
        elif key == "blockAsns":
            suggest = "block_asns"
        elif key == "blockIps":
            suggest = "block_ips"
        elif key == "blockLists":
            suggest = "block_lists"
        elif key == "blockReferers":
            suggest = "block_referers"
        elif key == "blockUas":
            suggest = "block_uas"
        elif key == "notifyEmails":
            suggest = "notify_emails"
        elif key == "notifySlack":
            suggest = "notify_slack"
        elif key == "notifySlackHitsRpm":
            suggest = "notify_slack_hits_rpm"
        elif key == "paranoiaLevel":
            suggest = "paranoia_level"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleProxyActionConfigWafConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleProxyActionConfigWafConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleProxyActionConfigWafConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 allow_ips: Optional[Sequence[_builtins.str]] = None,
                 allow_rules: Optional[Sequence[_builtins.str]] = None,
                 block_asns: Optional[Sequence[_builtins.str]] = None,
                 block_ips: Optional[Sequence[_builtins.str]] = None,
                 block_lists: Optional['outputs.RuleProxyActionConfigWafConfigBlockLists'] = None,
                 block_referers: Optional[Sequence[_builtins.str]] = None,
                 block_uas: Optional[Sequence[_builtins.str]] = None,
                 httpbl: Optional['outputs.RuleProxyActionConfigWafConfigHttpbl'] = None,
                 mode: Optional[_builtins.str] = None,
                 notify_emails: Optional[Sequence[_builtins.str]] = None,
                 notify_slack: Optional[_builtins.str] = None,
                 notify_slack_hits_rpm: Optional[_builtins.int] = None,
                 paranoia_level: Optional[_builtins.int] = None,
                 thresholds: Optional[Sequence['outputs.RuleProxyActionConfigWafConfigThreshold']] = None):
        """
        :param Sequence[_builtins.str] allow_ips: IP addresses to allow
        :param Sequence[_builtins.str] allow_rules: WAF rule IDs to allow/whitelist
        :param Sequence[_builtins.str] block_asns: ASN numbers to block
        :param Sequence[_builtins.str] block_ips: IP addresses to block
        :param 'RuleProxyActionConfigWafConfigBlockListsArgs' block_lists: Enable predefined block lists
        :param Sequence[_builtins.str] block_referers: Referer patterns to block
        :param Sequence[_builtins.str] block_uas: User agent patterns to block
        :param 'RuleProxyActionConfigWafConfigHttpblArgs' httpbl: Project Honey Pot HTTP:BL configuration
        :param _builtins.str mode: WAF operation mode
        :param Sequence[_builtins.str] notify_emails: Email addresses for notifications
        :param _builtins.str notify_slack: Slack webhook URL for notifications
        :param _builtins.int notify_slack_hits_rpm: Minimum hits per minute to trigger Slack notification
        :param _builtins.int paranoia_level: OWASP paranoia level
        :param Sequence['RuleProxyActionConfigWafConfigThresholdArgs'] thresholds: Rate limiting thresholds
        """
        if allow_ips is not None:
            pulumi.set(__self__, "allow_ips", allow_ips)
        if allow_rules is not None:
            pulumi.set(__self__, "allow_rules", allow_rules)
        if block_asns is not None:
            pulumi.set(__self__, "block_asns", block_asns)
        if block_ips is not None:
            pulumi.set(__self__, "block_ips", block_ips)
        if block_lists is not None:
            pulumi.set(__self__, "block_lists", block_lists)
        if block_referers is not None:
            pulumi.set(__self__, "block_referers", block_referers)
        if block_uas is not None:
            pulumi.set(__self__, "block_uas", block_uas)
        if httpbl is not None:
            pulumi.set(__self__, "httpbl", httpbl)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)
        if notify_emails is not None:
            pulumi.set(__self__, "notify_emails", notify_emails)
        if notify_slack is not None:
            pulumi.set(__self__, "notify_slack", notify_slack)
        if notify_slack_hits_rpm is not None:
            pulumi.set(__self__, "notify_slack_hits_rpm", notify_slack_hits_rpm)
        if paranoia_level is not None:
            pulumi.set(__self__, "paranoia_level", paranoia_level)
        if thresholds is not None:
            pulumi.set(__self__, "thresholds", thresholds)

    @_builtins.property
    @pulumi.getter(name="allowIps")
    def allow_ips(self) -> Optional[Sequence[_builtins.str]]:
        """
        IP addresses to allow
        """
        return pulumi.get(self, "allow_ips")

    @_builtins.property
    @pulumi.getter(name="allowRules")
    def allow_rules(self) -> Optional[Sequence[_builtins.str]]:
        """
        WAF rule IDs to allow/whitelist
        """
        return pulumi.get(self, "allow_rules")

    @_builtins.property
    @pulumi.getter(name="blockAsns")
    def block_asns(self) -> Optional[Sequence[_builtins.str]]:
        """
        ASN numbers to block
        """
        return pulumi.get(self, "block_asns")

    @_builtins.property
    @pulumi.getter(name="blockIps")
    def block_ips(self) -> Optional[Sequence[_builtins.str]]:
        """
        IP addresses to block
        """
        return pulumi.get(self, "block_ips")

    @_builtins.property
    @pulumi.getter(name="blockLists")
    def block_lists(self) -> Optional['outputs.RuleProxyActionConfigWafConfigBlockLists']:
        """
        Enable predefined block lists
        """
        return pulumi.get(self, "block_lists")

    @_builtins.property
    @pulumi.getter(name="blockReferers")
    def block_referers(self) -> Optional[Sequence[_builtins.str]]:
        """
        Referer patterns to block
        """
        return pulumi.get(self, "block_referers")

    @_builtins.property
    @pulumi.getter(name="blockUas")
    def block_uas(self) -> Optional[Sequence[_builtins.str]]:
        """
        User agent patterns to block
        """
        return pulumi.get(self, "block_uas")

    @_builtins.property
    @pulumi.getter
    def httpbl(self) -> Optional['outputs.RuleProxyActionConfigWafConfigHttpbl']:
        """
        Project Honey Pot HTTP:BL configuration
        """
        return pulumi.get(self, "httpbl")

    @_builtins.property
    @pulumi.getter
    def mode(self) -> Optional[_builtins.str]:
        """
        WAF operation mode
        """
        return pulumi.get(self, "mode")

    @_builtins.property
    @pulumi.getter(name="notifyEmails")
    def notify_emails(self) -> Optional[Sequence[_builtins.str]]:
        """
        Email addresses for notifications
        """
        return pulumi.get(self, "notify_emails")

    @_builtins.property
    @pulumi.getter(name="notifySlack")
    def notify_slack(self) -> Optional[_builtins.str]:
        """
        Slack webhook URL for notifications
        """
        return pulumi.get(self, "notify_slack")

    @_builtins.property
    @pulumi.getter(name="notifySlackHitsRpm")
    def notify_slack_hits_rpm(self) -> Optional[_builtins.int]:
        """
        Minimum hits per minute to trigger Slack notification
        """
        return pulumi.get(self, "notify_slack_hits_rpm")

    @_builtins.property
    @pulumi.getter(name="paranoiaLevel")
    def paranoia_level(self) -> Optional[_builtins.int]:
        """
        OWASP paranoia level
        """
        return pulumi.get(self, "paranoia_level")

    @_builtins.property
    @pulumi.getter
    def thresholds(self) -> Optional[Sequence['outputs.RuleProxyActionConfigWafConfigThreshold']]:
        """
        Rate limiting thresholds
        """
        return pulumi.get(self, "thresholds")


@pulumi.output_type
class RuleProxyActionConfigWafConfigBlockLists(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "userAgent":
            suggest = "user_agent"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleProxyActionConfigWafConfigBlockLists. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleProxyActionConfigWafConfigBlockLists.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleProxyActionConfigWafConfigBlockLists.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 ai: Optional[_builtins.bool] = None,
                 ip: Optional[_builtins.bool] = None,
                 referer: Optional[_builtins.bool] = None,
                 user_agent: Optional[_builtins.bool] = None):
        """
        :param _builtins.bool ai: Block AI crawlers
        :param _builtins.bool ip: Block known bad IPs
        :param _builtins.bool referer: Block known bad referers
        :param _builtins.bool user_agent: Block known bad user agents
        """
        if ai is not None:
            pulumi.set(__self__, "ai", ai)
        if ip is not None:
            pulumi.set(__self__, "ip", ip)
        if referer is not None:
            pulumi.set(__self__, "referer", referer)
        if user_agent is not None:
            pulumi.set(__self__, "user_agent", user_agent)

    @_builtins.property
    @pulumi.getter
    def ai(self) -> Optional[_builtins.bool]:
        """
        Block AI crawlers
        """
        return pulumi.get(self, "ai")

    @_builtins.property
    @pulumi.getter
    def ip(self) -> Optional[_builtins.bool]:
        """
        Block known bad IPs
        """
        return pulumi.get(self, "ip")

    @_builtins.property
    @pulumi.getter
    def referer(self) -> Optional[_builtins.bool]:
        """
        Block known bad referers
        """
        return pulumi.get(self, "referer")

    @_builtins.property
    @pulumi.getter(name="userAgent")
    def user_agent(self) -> Optional[_builtins.bool]:
        """
        Block known bad user agents
        """
        return pulumi.get(self, "user_agent")


@pulumi.output_type
class RuleProxyActionConfigWafConfigHttpbl(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "blockHarvester":
            suggest = "block_harvester"
        elif key == "blockSearchEngine":
            suggest = "block_search_engine"
        elif key == "blockSpam":
            suggest = "block_spam"
        elif key == "blockSuspicious":
            suggest = "block_suspicious"
        elif key == "httpblEnabled":
            suggest = "httpbl_enabled"
        elif key == "httpblKey":
            suggest = "httpbl_key"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleProxyActionConfigWafConfigHttpbl. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleProxyActionConfigWafConfigHttpbl.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleProxyActionConfigWafConfigHttpbl.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 block_harvester: Optional[_builtins.bool] = None,
                 block_search_engine: Optional[_builtins.bool] = None,
                 block_spam: Optional[_builtins.bool] = None,
                 block_suspicious: Optional[_builtins.bool] = None,
                 httpbl_enabled: Optional[_builtins.bool] = None,
                 httpbl_key: Optional[_builtins.str] = None):
        """
        :param _builtins.bool block_harvester: Block email harvesters
        :param _builtins.bool block_search_engine: Block search engines
        :param _builtins.bool block_spam: Block spam sources
        :param _builtins.bool block_suspicious: Block suspicious IPs
        :param _builtins.bool httpbl_enabled: Enable HTTP:BL
        :param _builtins.str httpbl_key: HTTP:BL API key
        """
        if block_harvester is not None:
            pulumi.set(__self__, "block_harvester", block_harvester)
        if block_search_engine is not None:
            pulumi.set(__self__, "block_search_engine", block_search_engine)
        if block_spam is not None:
            pulumi.set(__self__, "block_spam", block_spam)
        if block_suspicious is not None:
            pulumi.set(__self__, "block_suspicious", block_suspicious)
        if httpbl_enabled is not None:
            pulumi.set(__self__, "httpbl_enabled", httpbl_enabled)
        if httpbl_key is not None:
            pulumi.set(__self__, "httpbl_key", httpbl_key)

    @_builtins.property
    @pulumi.getter(name="blockHarvester")
    def block_harvester(self) -> Optional[_builtins.bool]:
        """
        Block email harvesters
        """
        return pulumi.get(self, "block_harvester")

    @_builtins.property
    @pulumi.getter(name="blockSearchEngine")
    def block_search_engine(self) -> Optional[_builtins.bool]:
        """
        Block search engines
        """
        return pulumi.get(self, "block_search_engine")

    @_builtins.property
    @pulumi.getter(name="blockSpam")
    def block_spam(self) -> Optional[_builtins.bool]:
        """
        Block spam sources
        """
        return pulumi.get(self, "block_spam")

    @_builtins.property
    @pulumi.getter(name="blockSuspicious")
    def block_suspicious(self) -> Optional[_builtins.bool]:
        """
        Block suspicious IPs
        """
        return pulumi.get(self, "block_suspicious")

    @_builtins.property
    @pulumi.getter(name="httpblEnabled")
    def httpbl_enabled(self) -> Optional[_builtins.bool]:
        """
        Enable HTTP:BL
        """
        return pulumi.get(self, "httpbl_enabled")

    @_builtins.property
    @pulumi.getter(name="httpblKey")
    def httpbl_key(self) -> Optional[_builtins.str]:
        """
        HTTP:BL API key
        """
        return pulumi.get(self, "httpbl_key")


@pulumi.output_type
class RuleProxyActionConfigWafConfigThreshold(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "notifySlack":
            suggest = "notify_slack"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleProxyActionConfigWafConfigThreshold. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleProxyActionConfigWafConfigThreshold.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleProxyActionConfigWafConfigThreshold.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 cooldown: Optional[_builtins.int] = None,
                 hits: Optional[_builtins.int] = None,
                 minutes: Optional[_builtins.int] = None,
                 mode: Optional[_builtins.str] = None,
                 notify_slack: Optional[_builtins.str] = None,
                 rps: Optional[_builtins.int] = None,
                 type: Optional[_builtins.str] = None,
                 value: Optional[_builtins.str] = None):
        """
        :param _builtins.int cooldown: Cooldown period in seconds
        :param _builtins.int hits: Hit count limit (for waf_hit_by_ip)
        :param _builtins.int minutes: Time window in minutes (for waf_hit_by_ip)
        :param _builtins.str mode: Threshold enforcement mode
        :param _builtins.str notify_slack: Slack webhook for this threshold
        :param _builtins.int rps: Requests per second limit (for ip/header)
        :param _builtins.str type: Threshold type
        :param _builtins.str value: Header name (for header type)
        """
        if cooldown is not None:
            pulumi.set(__self__, "cooldown", cooldown)
        if hits is not None:
            pulumi.set(__self__, "hits", hits)
        if minutes is not None:
            pulumi.set(__self__, "minutes", minutes)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)
        if notify_slack is not None:
            pulumi.set(__self__, "notify_slack", notify_slack)
        if rps is not None:
            pulumi.set(__self__, "rps", rps)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def cooldown(self) -> Optional[_builtins.int]:
        """
        Cooldown period in seconds
        """
        return pulumi.get(self, "cooldown")

    @_builtins.property
    @pulumi.getter
    def hits(self) -> Optional[_builtins.int]:
        """
        Hit count limit (for waf_hit_by_ip)
        """
        return pulumi.get(self, "hits")

    @_builtins.property
    @pulumi.getter
    def minutes(self) -> Optional[_builtins.int]:
        """
        Time window in minutes (for waf_hit_by_ip)
        """
        return pulumi.get(self, "minutes")

    @_builtins.property
    @pulumi.getter
    def mode(self) -> Optional[_builtins.str]:
        """
        Threshold enforcement mode
        """
        return pulumi.get(self, "mode")

    @_builtins.property
    @pulumi.getter(name="notifySlack")
    def notify_slack(self) -> Optional[_builtins.str]:
        """
        Slack webhook for this threshold
        """
        return pulumi.get(self, "notify_slack")

    @_builtins.property
    @pulumi.getter
    def rps(self) -> Optional[_builtins.int]:
        """
        Requests per second limit (for ip/header)
        """
        return pulumi.get(self, "rps")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        """
        Threshold type
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]:
        """
        Header name (for header type)
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class RuleProxyWafConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "allowIps":
            suggest = "allow_ips"
        elif key == "allowRules":
            suggest = "allow_rules"
        elif key == "blockAsns":
            suggest = "block_asns"
        elif key == "blockIps":
            suggest = "block_ips"
        elif key == "blockLists":
            suggest = "block_lists"
        elif key == "blockReferers":
            suggest = "block_referers"
        elif key == "blockUas":
            suggest = "block_uas"
        elif key == "notifyEmails":
            suggest = "notify_emails"
        elif key == "notifySlack":
            suggest = "notify_slack"
        elif key == "notifySlackHitsRpm":
            suggest = "notify_slack_hits_rpm"
        elif key == "paranoiaLevel":
            suggest = "paranoia_level"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleProxyWafConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleProxyWafConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleProxyWafConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 allow_ips: Optional[Sequence[_builtins.str]] = None,
                 allow_rules: Optional[Sequence[_builtins.str]] = None,
                 block_asns: Optional[Sequence[_builtins.str]] = None,
                 block_ips: Optional[Sequence[_builtins.str]] = None,
                 block_lists: Optional['outputs.RuleProxyWafConfigBlockLists'] = None,
                 block_referers: Optional[Sequence[_builtins.str]] = None,
                 block_uas: Optional[Sequence[_builtins.str]] = None,
                 httpbl: Optional['outputs.RuleProxyWafConfigHttpbl'] = None,
                 mode: Optional[_builtins.str] = None,
                 notify_emails: Optional[Sequence[_builtins.str]] = None,
                 notify_slack: Optional[_builtins.str] = None,
                 notify_slack_hits_rpm: Optional[_builtins.int] = None,
                 paranoia_level: Optional[_builtins.int] = None,
                 thresholds: Optional[Sequence['outputs.RuleProxyWafConfigThreshold']] = None):
        """
        :param Sequence[_builtins.str] allow_ips: IP addresses to allow
        :param Sequence[_builtins.str] allow_rules: WAF rule IDs to allow/whitelist
        :param Sequence[_builtins.str] block_asns: ASN numbers to block
        :param Sequence[_builtins.str] block_ips: IP addresses to block
        :param 'RuleProxyWafConfigBlockListsArgs' block_lists: Enable predefined block lists
        :param Sequence[_builtins.str] block_referers: Referer patterns to block
        :param Sequence[_builtins.str] block_uas: User agent patterns to block
        :param 'RuleProxyWafConfigHttpblArgs' httpbl: Project Honey Pot HTTP:BL configuration
        :param _builtins.str mode: WAF operation mode
        :param Sequence[_builtins.str] notify_emails: Email addresses for notifications
        :param _builtins.str notify_slack: Slack webhook URL for notifications
        :param _builtins.int notify_slack_hits_rpm: Minimum hits per minute to trigger Slack notification
        :param _builtins.int paranoia_level: OWASP paranoia level
        :param Sequence['RuleProxyWafConfigThresholdArgs'] thresholds: Rate limiting thresholds
        """
        if allow_ips is not None:
            pulumi.set(__self__, "allow_ips", allow_ips)
        if allow_rules is not None:
            pulumi.set(__self__, "allow_rules", allow_rules)
        if block_asns is not None:
            pulumi.set(__self__, "block_asns", block_asns)
        if block_ips is not None:
            pulumi.set(__self__, "block_ips", block_ips)
        if block_lists is not None:
            pulumi.set(__self__, "block_lists", block_lists)
        if block_referers is not None:
            pulumi.set(__self__, "block_referers", block_referers)
        if block_uas is not None:
            pulumi.set(__self__, "block_uas", block_uas)
        if httpbl is not None:
            pulumi.set(__self__, "httpbl", httpbl)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)
        if notify_emails is not None:
            pulumi.set(__self__, "notify_emails", notify_emails)
        if notify_slack is not None:
            pulumi.set(__self__, "notify_slack", notify_slack)
        if notify_slack_hits_rpm is not None:
            pulumi.set(__self__, "notify_slack_hits_rpm", notify_slack_hits_rpm)
        if paranoia_level is not None:
            pulumi.set(__self__, "paranoia_level", paranoia_level)
        if thresholds is not None:
            pulumi.set(__self__, "thresholds", thresholds)

    @_builtins.property
    @pulumi.getter(name="allowIps")
    def allow_ips(self) -> Optional[Sequence[_builtins.str]]:
        """
        IP addresses to allow
        """
        return pulumi.get(self, "allow_ips")

    @_builtins.property
    @pulumi.getter(name="allowRules")
    def allow_rules(self) -> Optional[Sequence[_builtins.str]]:
        """
        WAF rule IDs to allow/whitelist
        """
        return pulumi.get(self, "allow_rules")

    @_builtins.property
    @pulumi.getter(name="blockAsns")
    def block_asns(self) -> Optional[Sequence[_builtins.str]]:
        """
        ASN numbers to block
        """
        return pulumi.get(self, "block_asns")

    @_builtins.property
    @pulumi.getter(name="blockIps")
    def block_ips(self) -> Optional[Sequence[_builtins.str]]:
        """
        IP addresses to block
        """
        return pulumi.get(self, "block_ips")

    @_builtins.property
    @pulumi.getter(name="blockLists")
    def block_lists(self) -> Optional['outputs.RuleProxyWafConfigBlockLists']:
        """
        Enable predefined block lists
        """
        return pulumi.get(self, "block_lists")

    @_builtins.property
    @pulumi.getter(name="blockReferers")
    def block_referers(self) -> Optional[Sequence[_builtins.str]]:
        """
        Referer patterns to block
        """
        return pulumi.get(self, "block_referers")

    @_builtins.property
    @pulumi.getter(name="blockUas")
    def block_uas(self) -> Optional[Sequence[_builtins.str]]:
        """
        User agent patterns to block
        """
        return pulumi.get(self, "block_uas")

    @_builtins.property
    @pulumi.getter
    def httpbl(self) -> Optional['outputs.RuleProxyWafConfigHttpbl']:
        """
        Project Honey Pot HTTP:BL configuration
        """
        return pulumi.get(self, "httpbl")

    @_builtins.property
    @pulumi.getter
    def mode(self) -> Optional[_builtins.str]:
        """
        WAF operation mode
        """
        return pulumi.get(self, "mode")

    @_builtins.property
    @pulumi.getter(name="notifyEmails")
    def notify_emails(self) -> Optional[Sequence[_builtins.str]]:
        """
        Email addresses for notifications
        """
        return pulumi.get(self, "notify_emails")

    @_builtins.property
    @pulumi.getter(name="notifySlack")
    def notify_slack(self) -> Optional[_builtins.str]:
        """
        Slack webhook URL for notifications
        """
        return pulumi.get(self, "notify_slack")

    @_builtins.property
    @pulumi.getter(name="notifySlackHitsRpm")
    def notify_slack_hits_rpm(self) -> Optional[_builtins.int]:
        """
        Minimum hits per minute to trigger Slack notification
        """
        return pulumi.get(self, "notify_slack_hits_rpm")

    @_builtins.property
    @pulumi.getter(name="paranoiaLevel")
    def paranoia_level(self) -> Optional[_builtins.int]:
        """
        OWASP paranoia level
        """
        return pulumi.get(self, "paranoia_level")

    @_builtins.property
    @pulumi.getter
    def thresholds(self) -> Optional[Sequence['outputs.RuleProxyWafConfigThreshold']]:
        """
        Rate limiting thresholds
        """
        return pulumi.get(self, "thresholds")


@pulumi.output_type
class RuleProxyWafConfigBlockLists(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "userAgent":
            suggest = "user_agent"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleProxyWafConfigBlockLists. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleProxyWafConfigBlockLists.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleProxyWafConfigBlockLists.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 ai: Optional[_builtins.bool] = None,
                 ip: Optional[_builtins.bool] = None,
                 referer: Optional[_builtins.bool] = None,
                 user_agent: Optional[_builtins.bool] = None):
        """
        :param _builtins.bool ai: Block AI crawlers
        :param _builtins.bool ip: Block known bad IPs
        :param _builtins.bool referer: Block known bad referers
        :param _builtins.bool user_agent: Block known bad user agents
        """
        if ai is not None:
            pulumi.set(__self__, "ai", ai)
        if ip is not None:
            pulumi.set(__self__, "ip", ip)
        if referer is not None:
            pulumi.set(__self__, "referer", referer)
        if user_agent is not None:
            pulumi.set(__self__, "user_agent", user_agent)

    @_builtins.property
    @pulumi.getter
    def ai(self) -> Optional[_builtins.bool]:
        """
        Block AI crawlers
        """
        return pulumi.get(self, "ai")

    @_builtins.property
    @pulumi.getter
    def ip(self) -> Optional[_builtins.bool]:
        """
        Block known bad IPs
        """
        return pulumi.get(self, "ip")

    @_builtins.property
    @pulumi.getter
    def referer(self) -> Optional[_builtins.bool]:
        """
        Block known bad referers
        """
        return pulumi.get(self, "referer")

    @_builtins.property
    @pulumi.getter(name="userAgent")
    def user_agent(self) -> Optional[_builtins.bool]:
        """
        Block known bad user agents
        """
        return pulumi.get(self, "user_agent")


@pulumi.output_type
class RuleProxyWafConfigHttpbl(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "blockHarvester":
            suggest = "block_harvester"
        elif key == "blockSearchEngine":
            suggest = "block_search_engine"
        elif key == "blockSpam":
            suggest = "block_spam"
        elif key == "blockSuspicious":
            suggest = "block_suspicious"
        elif key == "httpblEnabled":
            suggest = "httpbl_enabled"
        elif key == "httpblKey":
            suggest = "httpbl_key"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleProxyWafConfigHttpbl. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleProxyWafConfigHttpbl.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleProxyWafConfigHttpbl.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 block_harvester: Optional[_builtins.bool] = None,
                 block_search_engine: Optional[_builtins.bool] = None,
                 block_spam: Optional[_builtins.bool] = None,
                 block_suspicious: Optional[_builtins.bool] = None,
                 httpbl_enabled: Optional[_builtins.bool] = None,
                 httpbl_key: Optional[_builtins.str] = None):
        """
        :param _builtins.bool block_harvester: Block email harvesters
        :param _builtins.bool block_search_engine: Block search engines
        :param _builtins.bool block_spam: Block spam sources
        :param _builtins.bool block_suspicious: Block suspicious IPs
        :param _builtins.bool httpbl_enabled: Enable HTTP:BL
        :param _builtins.str httpbl_key: HTTP:BL API key
        """
        if block_harvester is not None:
            pulumi.set(__self__, "block_harvester", block_harvester)
        if block_search_engine is not None:
            pulumi.set(__self__, "block_search_engine", block_search_engine)
        if block_spam is not None:
            pulumi.set(__self__, "block_spam", block_spam)
        if block_suspicious is not None:
            pulumi.set(__self__, "block_suspicious", block_suspicious)
        if httpbl_enabled is not None:
            pulumi.set(__self__, "httpbl_enabled", httpbl_enabled)
        if httpbl_key is not None:
            pulumi.set(__self__, "httpbl_key", httpbl_key)

    @_builtins.property
    @pulumi.getter(name="blockHarvester")
    def block_harvester(self) -> Optional[_builtins.bool]:
        """
        Block email harvesters
        """
        return pulumi.get(self, "block_harvester")

    @_builtins.property
    @pulumi.getter(name="blockSearchEngine")
    def block_search_engine(self) -> Optional[_builtins.bool]:
        """
        Block search engines
        """
        return pulumi.get(self, "block_search_engine")

    @_builtins.property
    @pulumi.getter(name="blockSpam")
    def block_spam(self) -> Optional[_builtins.bool]:
        """
        Block spam sources
        """
        return pulumi.get(self, "block_spam")

    @_builtins.property
    @pulumi.getter(name="blockSuspicious")
    def block_suspicious(self) -> Optional[_builtins.bool]:
        """
        Block suspicious IPs
        """
        return pulumi.get(self, "block_suspicious")

    @_builtins.property
    @pulumi.getter(name="httpblEnabled")
    def httpbl_enabled(self) -> Optional[_builtins.bool]:
        """
        Enable HTTP:BL
        """
        return pulumi.get(self, "httpbl_enabled")

    @_builtins.property
    @pulumi.getter(name="httpblKey")
    def httpbl_key(self) -> Optional[_builtins.str]:
        """
        HTTP:BL API key
        """
        return pulumi.get(self, "httpbl_key")


@pulumi.output_type
class RuleProxyWafConfigThreshold(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "notifySlack":
            suggest = "notify_slack"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleProxyWafConfigThreshold. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleProxyWafConfigThreshold.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleProxyWafConfigThreshold.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 cooldown: Optional[_builtins.int] = None,
                 hits: Optional[_builtins.int] = None,
                 minutes: Optional[_builtins.int] = None,
                 mode: Optional[_builtins.str] = None,
                 notify_slack: Optional[_builtins.str] = None,
                 rps: Optional[_builtins.int] = None,
                 type: Optional[_builtins.str] = None,
                 value: Optional[_builtins.str] = None):
        """
        :param _builtins.int cooldown: Cooldown period in seconds
        :param _builtins.int hits: Hit count limit (for waf_hit_by_ip)
        :param _builtins.int minutes: Time window in minutes (for waf_hit_by_ip)
        :param _builtins.str mode: Threshold enforcement mode
        :param _builtins.str notify_slack: Slack webhook for this threshold
        :param _builtins.int rps: Requests per second limit (for ip/header)
        :param _builtins.str type: Threshold type
        :param _builtins.str value: Header name (for header type)
        """
        if cooldown is not None:
            pulumi.set(__self__, "cooldown", cooldown)
        if hits is not None:
            pulumi.set(__self__, "hits", hits)
        if minutes is not None:
            pulumi.set(__self__, "minutes", minutes)
        if mode is not None:
            pulumi.set(__self__, "mode", mode)
        if notify_slack is not None:
            pulumi.set(__self__, "notify_slack", notify_slack)
        if rps is not None:
            pulumi.set(__self__, "rps", rps)
        if type is not None:
            pulumi.set(__self__, "type", type)
        if value is not None:
            pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def cooldown(self) -> Optional[_builtins.int]:
        """
        Cooldown period in seconds
        """
        return pulumi.get(self, "cooldown")

    @_builtins.property
    @pulumi.getter
    def hits(self) -> Optional[_builtins.int]:
        """
        Hit count limit (for waf_hit_by_ip)
        """
        return pulumi.get(self, "hits")

    @_builtins.property
    @pulumi.getter
    def minutes(self) -> Optional[_builtins.int]:
        """
        Time window in minutes (for waf_hit_by_ip)
        """
        return pulumi.get(self, "minutes")

    @_builtins.property
    @pulumi.getter
    def mode(self) -> Optional[_builtins.str]:
        """
        Threshold enforcement mode
        """
        return pulumi.get(self, "mode")

    @_builtins.property
    @pulumi.getter(name="notifySlack")
    def notify_slack(self) -> Optional[_builtins.str]:
        """
        Slack webhook for this threshold
        """
        return pulumi.get(self, "notify_slack")

    @_builtins.property
    @pulumi.getter
    def rps(self) -> Optional[_builtins.int]:
        """
        Requests per second limit (for ip/header)
        """
        return pulumi.get(self, "rps")

    @_builtins.property
    @pulumi.getter
    def type(self) -> Optional[_builtins.str]:
        """
        Threshold type
        """
        return pulumi.get(self, "type")

    @_builtins.property
    @pulumi.getter
    def value(self) -> Optional[_builtins.str]:
        """
        Header name (for header type)
        """
        return pulumi.get(self, "value")


@pulumi.output_type
class RuleRedirectActionConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "statusCode":
            suggest = "status_code"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleRedirectActionConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleRedirectActionConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleRedirectActionConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 status_code: Optional[_builtins.str] = None,
                 to: Optional[_builtins.str] = None):
        """
        :param _builtins.str status_code: HTTP status code for redirect
        :param _builtins.str to: Redirect destination URL
        """
        if status_code is not None:
            pulumi.set(__self__, "status_code", status_code)
        if to is not None:
            pulumi.set(__self__, "to", to)

    @_builtins.property
    @pulumi.getter(name="statusCode")
    def status_code(self) -> Optional[_builtins.str]:
        """
        HTTP status code for redirect
        """
        return pulumi.get(self, "status_code")

    @_builtins.property
    @pulumi.getter
    def to(self) -> Optional[_builtins.str]:
        """
        Redirect destination URL
        """
        return pulumi.get(self, "to")


@pulumi.output_type
class RuleServeStaticActionConfig(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "staticFilePath":
            suggest = "static_file_path"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in RuleServeStaticActionConfig. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        RuleServeStaticActionConfig.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        RuleServeStaticActionConfig.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 static_file_path: Optional[_builtins.str] = None):
        """
        :param _builtins.str static_file_path: Path to the static file to serve
        """
        if static_file_path is not None:
            pulumi.set(__self__, "static_file_path", static_file_path)

    @_builtins.property
    @pulumi.getter(name="staticFilePath")
    def static_file_path(self) -> Optional[_builtins.str]:
        """
        Path to the static file to serve
        """
        return pulumi.get(self, "static_file_path")


@pulumi.output_type
class GetProjectsProjectResult(dict):
    def __init__(__self__, *,
                 machine_name: _builtins.str,
                 name: _builtins.str):
        pulumi.set(__self__, "machine_name", machine_name)
        pulumi.set(__self__, "name", name)

    @_builtins.property
    @pulumi.getter(name="machineName")
    def machine_name(self) -> _builtins.str:
        return pulumi.get(self, "machine_name")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        return pulumi.get(self, "name")


