# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['RuleBotChallengeArgs', 'RuleBotChallenge']

@pulumi.input_type
class RuleBotChallengeArgs:
    def __init__(__self__, *,
                 domains: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 robot_challenge_type: pulumi.Input[_builtins.str],
                 urls: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]],
                 country: Optional[pulumi.Input[_builtins.str]] = None,
                 country_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 country_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 ip: Optional[pulumi.Input[_builtins.str]] = None,
                 ip_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ip_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 method: Optional[pulumi.Input[_builtins.str]] = None,
                 method_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 method_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 robot_challenge_challenge_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 robot_challenge_verification_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 rule: Optional[pulumi.Input[_builtins.str]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 weight: Optional[pulumi.Input[_builtins.int]] = None):
        """
        The set of arguments for constructing a RuleBotChallenge resource.

        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domains: Domain patterns (default: any)
        :param pulumi.Input[_builtins.str] robot_challenge_type: Challenge type (invisible or checkbox)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] urls: URL patterns
        :param pulumi.Input[_builtins.str] country: Country filter type (country_is, country_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] country_is: Allowed countries
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] country_is_nots: Excluded countries
        :param pulumi.Input[_builtins.bool] disabled: Whether rule is disabled
        :param pulumi.Input[_builtins.str] ip: IP filter type (ip_is, ip_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_is: Allowed IP addresses
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_is_nots: Excluded IP addresses
        :param pulumi.Input[_builtins.str] method: Method filter type (method_is, method_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] method_is: Allowed HTTP methods
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] method_is_nots: Excluded HTTP methods
        :param pulumi.Input[_builtins.str] name: Rule name
        :param pulumi.Input[_builtins.str] organization: Organization identifier
        :param pulumi.Input[_builtins.str] project: Project identifier
        :param pulumi.Input[_builtins.int] robot_challenge_challenge_ttl: Challenge TTL in seconds
        :param pulumi.Input[_builtins.int] robot_challenge_verification_ttl: Verification TTL in seconds
        :param pulumi.Input[_builtins.str] rule: Rule identifier
        :param pulumi.Input[_builtins.str] uuid: Rule UUID
        :param pulumi.Input[_builtins.int] weight: Rule weight
        """
        pulumi.set(__self__, "domains", domains)
        pulumi.set(__self__, "robot_challenge_type", robot_challenge_type)
        pulumi.set(__self__, "urls", urls)
        if country is not None:
            pulumi.set(__self__, "country", country)
        if country_is is not None:
            pulumi.set(__self__, "country_is", country_is)
        if country_is_nots is not None:
            pulumi.set(__self__, "country_is_nots", country_is_nots)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if ip is not None:
            pulumi.set(__self__, "ip", ip)
        if ip_is is not None:
            pulumi.set(__self__, "ip_is", ip_is)
        if ip_is_nots is not None:
            pulumi.set(__self__, "ip_is_nots", ip_is_nots)
        if method is not None:
            pulumi.set(__self__, "method", method)
        if method_is is not None:
            pulumi.set(__self__, "method_is", method_is)
        if method_is_nots is not None:
            pulumi.set(__self__, "method_is_nots", method_is_nots)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if project is not None:
            pulumi.set(__self__, "project", project)
        if robot_challenge_challenge_ttl is not None:
            pulumi.set(__self__, "robot_challenge_challenge_ttl", robot_challenge_challenge_ttl)
        if robot_challenge_verification_ttl is not None:
            pulumi.set(__self__, "robot_challenge_verification_ttl", robot_challenge_verification_ttl)
        if rule is not None:
            pulumi.set(__self__, "rule", rule)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)
        if weight is not None:
            pulumi.set(__self__, "weight", weight)

    @_builtins.property
    @pulumi.getter
    def domains(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        Domain patterns (default: any)
        """
        return pulumi.get(self, "domains")

    @domains.setter
    def domains(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "domains", value)

    @_builtins.property
    @pulumi.getter(name="robotChallengeType")
    def robot_challenge_type(self) -> pulumi.Input[_builtins.str]:
        """
        Challenge type (invisible or checkbox)
        """
        return pulumi.get(self, "robot_challenge_type")

    @robot_challenge_type.setter
    def robot_challenge_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "robot_challenge_type", value)

    @_builtins.property
    @pulumi.getter
    def urls(self) -> pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]:
        """
        URL patterns
        """
        return pulumi.get(self, "urls")

    @urls.setter
    def urls(self, value: pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "urls", value)

    @_builtins.property
    @pulumi.getter
    def country(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Country filter type (country_is, country_is_not, any)
        """
        return pulumi.get(self, "country")

    @country.setter
    def country(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "country", value)

    @_builtins.property
    @pulumi.getter(name="countryIs")
    def country_is(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Allowed countries
        """
        return pulumi.get(self, "country_is")

    @country_is.setter
    def country_is(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "country_is", value)

    @_builtins.property
    @pulumi.getter(name="countryIsNots")
    def country_is_nots(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Excluded countries
        """
        return pulumi.get(self, "country_is_nots")

    @country_is_nots.setter
    def country_is_nots(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "country_is_nots", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether rule is disabled
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter
    def ip(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        IP filter type (ip_is, ip_is_not, any)
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ip", value)

    @_builtins.property
    @pulumi.getter(name="ipIs")
    def ip_is(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Allowed IP addresses
        """
        return pulumi.get(self, "ip_is")

    @ip_is.setter
    def ip_is(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ip_is", value)

    @_builtins.property
    @pulumi.getter(name="ipIsNots")
    def ip_is_nots(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Excluded IP addresses
        """
        return pulumi.get(self, "ip_is_nots")

    @ip_is_nots.setter
    def ip_is_nots(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ip_is_nots", value)

    @_builtins.property
    @pulumi.getter
    def method(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Method filter type (method_is, method_is_not, any)
        """
        return pulumi.get(self, "method")

    @method.setter
    def method(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "method", value)

    @_builtins.property
    @pulumi.getter(name="methodIs")
    def method_is(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Allowed HTTP methods
        """
        return pulumi.get(self, "method_is")

    @method_is.setter
    def method_is(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "method_is", value)

    @_builtins.property
    @pulumi.getter(name="methodIsNots")
    def method_is_nots(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Excluded HTTP methods
        """
        return pulumi.get(self, "method_is_nots")

    @method_is_nots.setter
    def method_is_nots(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "method_is_nots", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Rule name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Organization identifier
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization", value)

    @_builtins.property
    @pulumi.getter
    def project(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Project identifier
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter(name="robotChallengeChallengeTtl")
    def robot_challenge_challenge_ttl(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Challenge TTL in seconds
        """
        return pulumi.get(self, "robot_challenge_challenge_ttl")

    @robot_challenge_challenge_ttl.setter
    def robot_challenge_challenge_ttl(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "robot_challenge_challenge_ttl", value)

    @_builtins.property
    @pulumi.getter(name="robotChallengeVerificationTtl")
    def robot_challenge_verification_ttl(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Verification TTL in seconds
        """
        return pulumi.get(self, "robot_challenge_verification_ttl")

    @robot_challenge_verification_ttl.setter
    def robot_challenge_verification_ttl(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "robot_challenge_verification_ttl", value)

    @_builtins.property
    @pulumi.getter
    def rule(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Rule identifier
        """
        return pulumi.get(self, "rule")

    @rule.setter
    def rule(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rule", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Rule UUID
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)

    @_builtins.property
    @pulumi.getter
    def weight(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Rule weight
        """
        return pulumi.get(self, "weight")

    @weight.setter
    def weight(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "weight", value)


@pulumi.input_type
class _RuleBotChallengeState:
    def __init__(__self__, *,
                 action: Optional[pulumi.Input[_builtins.str]] = None,
                 action_config: Optional[pulumi.Input['RuleBotChallengeActionConfigArgs']] = None,
                 country: Optional[pulumi.Input[_builtins.str]] = None,
                 country_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 country_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ip: Optional[pulumi.Input[_builtins.str]] = None,
                 ip_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ip_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 method: Optional[pulumi.Input[_builtins.str]] = None,
                 method_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 method_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 only_with_cookie: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 robot_challenge_challenge_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 robot_challenge_type: Optional[pulumi.Input[_builtins.str]] = None,
                 robot_challenge_verification_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 rule: Optional[pulumi.Input[_builtins.str]] = None,
                 rule_id: Optional[pulumi.Input[_builtins.str]] = None,
                 urls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 weight: Optional[pulumi.Input[_builtins.int]] = None):
        """
        Input properties used for looking up and filtering RuleBotChallenge resources.

        :param pulumi.Input[_builtins.str] action: Rule action
        :param pulumi.Input[_builtins.str] country: Country filter type (country_is, country_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] country_is: Allowed countries
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] country_is_nots: Excluded countries
        :param pulumi.Input[_builtins.bool] disabled: Whether rule is disabled
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domains: Domain patterns (default: any)
        :param pulumi.Input[_builtins.str] ip: IP filter type (ip_is, ip_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_is: Allowed IP addresses
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_is_nots: Excluded IP addresses
        :param pulumi.Input[_builtins.str] method: Method filter type (method_is, method_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] method_is: Allowed HTTP methods
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] method_is_nots: Excluded HTTP methods
        :param pulumi.Input[_builtins.str] name: Rule name
        :param pulumi.Input[_builtins.str] only_with_cookie: Only apply with cookie
        :param pulumi.Input[_builtins.str] organization: Organization identifier
        :param pulumi.Input[_builtins.str] project: Project identifier
        :param pulumi.Input[_builtins.int] robot_challenge_challenge_ttl: Challenge TTL in seconds
        :param pulumi.Input[_builtins.str] robot_challenge_type: Challenge type (invisible or checkbox)
        :param pulumi.Input[_builtins.int] robot_challenge_verification_ttl: Verification TTL in seconds
        :param pulumi.Input[_builtins.str] rule: Rule identifier
        :param pulumi.Input[_builtins.str] rule_id: Rule ID
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] urls: URL patterns
        :param pulumi.Input[_builtins.str] uuid: Rule UUID
        :param pulumi.Input[_builtins.int] weight: Rule weight
        """
        if action is not None:
            pulumi.set(__self__, "action", action)
        if action_config is not None:
            pulumi.set(__self__, "action_config", action_config)
        if country is not None:
            pulumi.set(__self__, "country", country)
        if country_is is not None:
            pulumi.set(__self__, "country_is", country_is)
        if country_is_nots is not None:
            pulumi.set(__self__, "country_is_nots", country_is_nots)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if domains is not None:
            pulumi.set(__self__, "domains", domains)
        if ip is not None:
            pulumi.set(__self__, "ip", ip)
        if ip_is is not None:
            pulumi.set(__self__, "ip_is", ip_is)
        if ip_is_nots is not None:
            pulumi.set(__self__, "ip_is_nots", ip_is_nots)
        if method is not None:
            pulumi.set(__self__, "method", method)
        if method_is is not None:
            pulumi.set(__self__, "method_is", method_is)
        if method_is_nots is not None:
            pulumi.set(__self__, "method_is_nots", method_is_nots)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if only_with_cookie is not None:
            pulumi.set(__self__, "only_with_cookie", only_with_cookie)
        if organization is not None:
            pulumi.set(__self__, "organization", organization)
        if project is not None:
            pulumi.set(__self__, "project", project)
        if robot_challenge_challenge_ttl is not None:
            pulumi.set(__self__, "robot_challenge_challenge_ttl", robot_challenge_challenge_ttl)
        if robot_challenge_type is not None:
            pulumi.set(__self__, "robot_challenge_type", robot_challenge_type)
        if robot_challenge_verification_ttl is not None:
            pulumi.set(__self__, "robot_challenge_verification_ttl", robot_challenge_verification_ttl)
        if rule is not None:
            pulumi.set(__self__, "rule", rule)
        if rule_id is not None:
            pulumi.set(__self__, "rule_id", rule_id)
        if urls is not None:
            pulumi.set(__self__, "urls", urls)
        if uuid is not None:
            pulumi.set(__self__, "uuid", uuid)
        if weight is not None:
            pulumi.set(__self__, "weight", weight)

    @_builtins.property
    @pulumi.getter
    def action(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Rule action
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "action", value)

    @_builtins.property
    @pulumi.getter(name="actionConfig")
    def action_config(self) -> Optional[pulumi.Input['RuleBotChallengeActionConfigArgs']]:
        return pulumi.get(self, "action_config")

    @action_config.setter
    def action_config(self, value: Optional[pulumi.Input['RuleBotChallengeActionConfigArgs']]):
        pulumi.set(self, "action_config", value)

    @_builtins.property
    @pulumi.getter
    def country(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Country filter type (country_is, country_is_not, any)
        """
        return pulumi.get(self, "country")

    @country.setter
    def country(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "country", value)

    @_builtins.property
    @pulumi.getter(name="countryIs")
    def country_is(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Allowed countries
        """
        return pulumi.get(self, "country_is")

    @country_is.setter
    def country_is(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "country_is", value)

    @_builtins.property
    @pulumi.getter(name="countryIsNots")
    def country_is_nots(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Excluded countries
        """
        return pulumi.get(self, "country_is_nots")

    @country_is_nots.setter
    def country_is_nots(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "country_is_nots", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Whether rule is disabled
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter
    def domains(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Domain patterns (default: any)
        """
        return pulumi.get(self, "domains")

    @domains.setter
    def domains(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "domains", value)

    @_builtins.property
    @pulumi.getter
    def ip(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        IP filter type (ip_is, ip_is_not, any)
        """
        return pulumi.get(self, "ip")

    @ip.setter
    def ip(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "ip", value)

    @_builtins.property
    @pulumi.getter(name="ipIs")
    def ip_is(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Allowed IP addresses
        """
        return pulumi.get(self, "ip_is")

    @ip_is.setter
    def ip_is(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ip_is", value)

    @_builtins.property
    @pulumi.getter(name="ipIsNots")
    def ip_is_nots(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Excluded IP addresses
        """
        return pulumi.get(self, "ip_is_nots")

    @ip_is_nots.setter
    def ip_is_nots(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "ip_is_nots", value)

    @_builtins.property
    @pulumi.getter
    def method(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Method filter type (method_is, method_is_not, any)
        """
        return pulumi.get(self, "method")

    @method.setter
    def method(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "method", value)

    @_builtins.property
    @pulumi.getter(name="methodIs")
    def method_is(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Allowed HTTP methods
        """
        return pulumi.get(self, "method_is")

    @method_is.setter
    def method_is(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "method_is", value)

    @_builtins.property
    @pulumi.getter(name="methodIsNots")
    def method_is_nots(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Excluded HTTP methods
        """
        return pulumi.get(self, "method_is_nots")

    @method_is_nots.setter
    def method_is_nots(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "method_is_nots", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Rule name
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="onlyWithCookie")
    def only_with_cookie(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Only apply with cookie
        """
        return pulumi.get(self, "only_with_cookie")

    @only_with_cookie.setter
    def only_with_cookie(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "only_with_cookie", value)

    @_builtins.property
    @pulumi.getter
    def organization(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Organization identifier
        """
        return pulumi.get(self, "organization")

    @organization.setter
    def organization(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "organization", value)

    @_builtins.property
    @pulumi.getter
    def project(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Project identifier
        """
        return pulumi.get(self, "project")

    @project.setter
    def project(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "project", value)

    @_builtins.property
    @pulumi.getter(name="robotChallengeChallengeTtl")
    def robot_challenge_challenge_ttl(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Challenge TTL in seconds
        """
        return pulumi.get(self, "robot_challenge_challenge_ttl")

    @robot_challenge_challenge_ttl.setter
    def robot_challenge_challenge_ttl(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "robot_challenge_challenge_ttl", value)

    @_builtins.property
    @pulumi.getter(name="robotChallengeType")
    def robot_challenge_type(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Challenge type (invisible or checkbox)
        """
        return pulumi.get(self, "robot_challenge_type")

    @robot_challenge_type.setter
    def robot_challenge_type(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "robot_challenge_type", value)

    @_builtins.property
    @pulumi.getter(name="robotChallengeVerificationTtl")
    def robot_challenge_verification_ttl(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Verification TTL in seconds
        """
        return pulumi.get(self, "robot_challenge_verification_ttl")

    @robot_challenge_verification_ttl.setter
    def robot_challenge_verification_ttl(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "robot_challenge_verification_ttl", value)

    @_builtins.property
    @pulumi.getter
    def rule(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Rule identifier
        """
        return pulumi.get(self, "rule")

    @rule.setter
    def rule(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rule", value)

    @_builtins.property
    @pulumi.getter(name="ruleId")
    def rule_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Rule ID
        """
        return pulumi.get(self, "rule_id")

    @rule_id.setter
    def rule_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "rule_id", value)

    @_builtins.property
    @pulumi.getter
    def urls(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        URL patterns
        """
        return pulumi.get(self, "urls")

    @urls.setter
    def urls(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "urls", value)

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        Rule UUID
        """
        return pulumi.get(self, "uuid")

    @uuid.setter
    def uuid(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "uuid", value)

    @_builtins.property
    @pulumi.getter
    def weight(self) -> Optional[pulumi.Input[_builtins.int]]:
        """
        Rule weight
        """
        return pulumi.get(self, "weight")

    @weight.setter
    def weight(self, value: Optional[pulumi.Input[_builtins.int]]):
        pulumi.set(self, "weight", value)


@pulumi.type_token("quant:index:RuleBotChallenge")
class RuleBotChallenge(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 country: Optional[pulumi.Input[_builtins.str]] = None,
                 country_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 country_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ip: Optional[pulumi.Input[_builtins.str]] = None,
                 ip_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ip_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 method: Optional[pulumi.Input[_builtins.str]] = None,
                 method_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 method_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 robot_challenge_challenge_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 robot_challenge_type: Optional[pulumi.Input[_builtins.str]] = None,
                 robot_challenge_verification_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 rule: Optional[pulumi.Input[_builtins.str]] = None,
                 urls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 weight: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        """
        Create a RuleBotChallenge resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] country: Country filter type (country_is, country_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] country_is: Allowed countries
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] country_is_nots: Excluded countries
        :param pulumi.Input[_builtins.bool] disabled: Whether rule is disabled
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domains: Domain patterns (default: any)
        :param pulumi.Input[_builtins.str] ip: IP filter type (ip_is, ip_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_is: Allowed IP addresses
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_is_nots: Excluded IP addresses
        :param pulumi.Input[_builtins.str] method: Method filter type (method_is, method_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] method_is: Allowed HTTP methods
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] method_is_nots: Excluded HTTP methods
        :param pulumi.Input[_builtins.str] name: Rule name
        :param pulumi.Input[_builtins.str] organization: Organization identifier
        :param pulumi.Input[_builtins.str] project: Project identifier
        :param pulumi.Input[_builtins.int] robot_challenge_challenge_ttl: Challenge TTL in seconds
        :param pulumi.Input[_builtins.str] robot_challenge_type: Challenge type (invisible or checkbox)
        :param pulumi.Input[_builtins.int] robot_challenge_verification_ttl: Verification TTL in seconds
        :param pulumi.Input[_builtins.str] rule: Rule identifier
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] urls: URL patterns
        :param pulumi.Input[_builtins.str] uuid: Rule UUID
        :param pulumi.Input[_builtins.int] weight: Rule weight
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RuleBotChallengeArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a RuleBotChallenge resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param RuleBotChallengeArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RuleBotChallengeArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 country: Optional[pulumi.Input[_builtins.str]] = None,
                 country_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 country_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 disabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ip: Optional[pulumi.Input[_builtins.str]] = None,
                 ip_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 ip_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 method: Optional[pulumi.Input[_builtins.str]] = None,
                 method_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 method_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 organization: Optional[pulumi.Input[_builtins.str]] = None,
                 project: Optional[pulumi.Input[_builtins.str]] = None,
                 robot_challenge_challenge_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 robot_challenge_type: Optional[pulumi.Input[_builtins.str]] = None,
                 robot_challenge_verification_ttl: Optional[pulumi.Input[_builtins.int]] = None,
                 rule: Optional[pulumi.Input[_builtins.str]] = None,
                 urls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 uuid: Optional[pulumi.Input[_builtins.str]] = None,
                 weight: Optional[pulumi.Input[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RuleBotChallengeArgs.__new__(RuleBotChallengeArgs)

            __props__.__dict__["country"] = country
            __props__.__dict__["country_is"] = country_is
            __props__.__dict__["country_is_nots"] = country_is_nots
            __props__.__dict__["disabled"] = disabled
            if domains is None and not opts.urn:
                raise TypeError("Missing required property 'domains'")
            __props__.__dict__["domains"] = domains
            __props__.__dict__["ip"] = ip
            __props__.__dict__["ip_is"] = ip_is
            __props__.__dict__["ip_is_nots"] = ip_is_nots
            __props__.__dict__["method"] = method
            __props__.__dict__["method_is"] = method_is
            __props__.__dict__["method_is_nots"] = method_is_nots
            __props__.__dict__["name"] = name
            __props__.__dict__["organization"] = organization
            __props__.__dict__["project"] = project
            __props__.__dict__["robot_challenge_challenge_ttl"] = robot_challenge_challenge_ttl
            if robot_challenge_type is None and not opts.urn:
                raise TypeError("Missing required property 'robot_challenge_type'")
            __props__.__dict__["robot_challenge_type"] = robot_challenge_type
            __props__.__dict__["robot_challenge_verification_ttl"] = robot_challenge_verification_ttl
            __props__.__dict__["rule"] = rule
            if urls is None and not opts.urn:
                raise TypeError("Missing required property 'urls'")
            __props__.__dict__["urls"] = urls
            __props__.__dict__["uuid"] = uuid
            __props__.__dict__["weight"] = weight
            __props__.__dict__["action"] = None
            __props__.__dict__["action_config"] = None
            __props__.__dict__["only_with_cookie"] = None
            __props__.__dict__["rule_id"] = None
        super(RuleBotChallenge, __self__).__init__(
            'quant:index:RuleBotChallenge',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            action: Optional[pulumi.Input[_builtins.str]] = None,
            action_config: Optional[pulumi.Input[Union['RuleBotChallengeActionConfigArgs', 'RuleBotChallengeActionConfigArgsDict']]] = None,
            country: Optional[pulumi.Input[_builtins.str]] = None,
            country_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            country_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            disabled: Optional[pulumi.Input[_builtins.bool]] = None,
            domains: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            ip: Optional[pulumi.Input[_builtins.str]] = None,
            ip_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            ip_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            method: Optional[pulumi.Input[_builtins.str]] = None,
            method_is: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            method_is_nots: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            name: Optional[pulumi.Input[_builtins.str]] = None,
            only_with_cookie: Optional[pulumi.Input[_builtins.str]] = None,
            organization: Optional[pulumi.Input[_builtins.str]] = None,
            project: Optional[pulumi.Input[_builtins.str]] = None,
            robot_challenge_challenge_ttl: Optional[pulumi.Input[_builtins.int]] = None,
            robot_challenge_type: Optional[pulumi.Input[_builtins.str]] = None,
            robot_challenge_verification_ttl: Optional[pulumi.Input[_builtins.int]] = None,
            rule: Optional[pulumi.Input[_builtins.str]] = None,
            rule_id: Optional[pulumi.Input[_builtins.str]] = None,
            urls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
            uuid: Optional[pulumi.Input[_builtins.str]] = None,
            weight: Optional[pulumi.Input[_builtins.int]] = None) -> 'RuleBotChallenge':
        """
        Get an existing RuleBotChallenge resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] action: Rule action
        :param pulumi.Input[_builtins.str] country: Country filter type (country_is, country_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] country_is: Allowed countries
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] country_is_nots: Excluded countries
        :param pulumi.Input[_builtins.bool] disabled: Whether rule is disabled
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] domains: Domain patterns (default: any)
        :param pulumi.Input[_builtins.str] ip: IP filter type (ip_is, ip_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_is: Allowed IP addresses
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] ip_is_nots: Excluded IP addresses
        :param pulumi.Input[_builtins.str] method: Method filter type (method_is, method_is_not, any)
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] method_is: Allowed HTTP methods
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] method_is_nots: Excluded HTTP methods
        :param pulumi.Input[_builtins.str] name: Rule name
        :param pulumi.Input[_builtins.str] only_with_cookie: Only apply with cookie
        :param pulumi.Input[_builtins.str] organization: Organization identifier
        :param pulumi.Input[_builtins.str] project: Project identifier
        :param pulumi.Input[_builtins.int] robot_challenge_challenge_ttl: Challenge TTL in seconds
        :param pulumi.Input[_builtins.str] robot_challenge_type: Challenge type (invisible or checkbox)
        :param pulumi.Input[_builtins.int] robot_challenge_verification_ttl: Verification TTL in seconds
        :param pulumi.Input[_builtins.str] rule: Rule identifier
        :param pulumi.Input[_builtins.str] rule_id: Rule ID
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] urls: URL patterns
        :param pulumi.Input[_builtins.str] uuid: Rule UUID
        :param pulumi.Input[_builtins.int] weight: Rule weight
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _RuleBotChallengeState.__new__(_RuleBotChallengeState)

        __props__.__dict__["action"] = action
        __props__.__dict__["action_config"] = action_config
        __props__.__dict__["country"] = country
        __props__.__dict__["country_is"] = country_is
        __props__.__dict__["country_is_nots"] = country_is_nots
        __props__.__dict__["disabled"] = disabled
        __props__.__dict__["domains"] = domains
        __props__.__dict__["ip"] = ip
        __props__.__dict__["ip_is"] = ip_is
        __props__.__dict__["ip_is_nots"] = ip_is_nots
        __props__.__dict__["method"] = method
        __props__.__dict__["method_is"] = method_is
        __props__.__dict__["method_is_nots"] = method_is_nots
        __props__.__dict__["name"] = name
        __props__.__dict__["only_with_cookie"] = only_with_cookie
        __props__.__dict__["organization"] = organization
        __props__.__dict__["project"] = project
        __props__.__dict__["robot_challenge_challenge_ttl"] = robot_challenge_challenge_ttl
        __props__.__dict__["robot_challenge_type"] = robot_challenge_type
        __props__.__dict__["robot_challenge_verification_ttl"] = robot_challenge_verification_ttl
        __props__.__dict__["rule"] = rule
        __props__.__dict__["rule_id"] = rule_id
        __props__.__dict__["urls"] = urls
        __props__.__dict__["uuid"] = uuid
        __props__.__dict__["weight"] = weight
        return RuleBotChallenge(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def action(self) -> pulumi.Output[_builtins.str]:
        """
        Rule action
        """
        return pulumi.get(self, "action")

    @_builtins.property
    @pulumi.getter(name="actionConfig")
    def action_config(self) -> pulumi.Output['outputs.RuleBotChallengeActionConfig']:
        return pulumi.get(self, "action_config")

    @_builtins.property
    @pulumi.getter
    def country(self) -> pulumi.Output[_builtins.str]:
        """
        Country filter type (country_is, country_is_not, any)
        """
        return pulumi.get(self, "country")

    @_builtins.property
    @pulumi.getter(name="countryIs")
    def country_is(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Allowed countries
        """
        return pulumi.get(self, "country_is")

    @_builtins.property
    @pulumi.getter(name="countryIsNots")
    def country_is_nots(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Excluded countries
        """
        return pulumi.get(self, "country_is_nots")

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether rule is disabled
        """
        return pulumi.get(self, "disabled")

    @_builtins.property
    @pulumi.getter
    def domains(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Domain patterns (default: any)
        """
        return pulumi.get(self, "domains")

    @_builtins.property
    @pulumi.getter
    def ip(self) -> pulumi.Output[_builtins.str]:
        """
        IP filter type (ip_is, ip_is_not, any)
        """
        return pulumi.get(self, "ip")

    @_builtins.property
    @pulumi.getter(name="ipIs")
    def ip_is(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Allowed IP addresses
        """
        return pulumi.get(self, "ip_is")

    @_builtins.property
    @pulumi.getter(name="ipIsNots")
    def ip_is_nots(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Excluded IP addresses
        """
        return pulumi.get(self, "ip_is_nots")

    @_builtins.property
    @pulumi.getter
    def method(self) -> pulumi.Output[_builtins.str]:
        """
        Method filter type (method_is, method_is_not, any)
        """
        return pulumi.get(self, "method")

    @_builtins.property
    @pulumi.getter(name="methodIs")
    def method_is(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Allowed HTTP methods
        """
        return pulumi.get(self, "method_is")

    @_builtins.property
    @pulumi.getter(name="methodIsNots")
    def method_is_nots(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        Excluded HTTP methods
        """
        return pulumi.get(self, "method_is_nots")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Rule name
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="onlyWithCookie")
    def only_with_cookie(self) -> pulumi.Output[_builtins.str]:
        """
        Only apply with cookie
        """
        return pulumi.get(self, "only_with_cookie")

    @_builtins.property
    @pulumi.getter
    def organization(self) -> pulumi.Output[_builtins.str]:
        """
        Organization identifier
        """
        return pulumi.get(self, "organization")

    @_builtins.property
    @pulumi.getter
    def project(self) -> pulumi.Output[_builtins.str]:
        """
        Project identifier
        """
        return pulumi.get(self, "project")

    @_builtins.property
    @pulumi.getter(name="robotChallengeChallengeTtl")
    def robot_challenge_challenge_ttl(self) -> pulumi.Output[_builtins.int]:
        """
        Challenge TTL in seconds
        """
        return pulumi.get(self, "robot_challenge_challenge_ttl")

    @_builtins.property
    @pulumi.getter(name="robotChallengeType")
    def robot_challenge_type(self) -> pulumi.Output[_builtins.str]:
        """
        Challenge type (invisible or checkbox)
        """
        return pulumi.get(self, "robot_challenge_type")

    @_builtins.property
    @pulumi.getter(name="robotChallengeVerificationTtl")
    def robot_challenge_verification_ttl(self) -> pulumi.Output[_builtins.int]:
        """
        Verification TTL in seconds
        """
        return pulumi.get(self, "robot_challenge_verification_ttl")

    @_builtins.property
    @pulumi.getter
    def rule(self) -> pulumi.Output[_builtins.str]:
        """
        Rule identifier
        """
        return pulumi.get(self, "rule")

    @_builtins.property
    @pulumi.getter(name="ruleId")
    def rule_id(self) -> pulumi.Output[_builtins.str]:
        """
        Rule ID
        """
        return pulumi.get(self, "rule_id")

    @_builtins.property
    @pulumi.getter
    def urls(self) -> pulumi.Output[Sequence[_builtins.str]]:
        """
        URL patterns
        """
        return pulumi.get(self, "urls")

    @_builtins.property
    @pulumi.getter
    def uuid(self) -> pulumi.Output[_builtins.str]:
        """
        Rule UUID
        """
        return pulumi.get(self, "uuid")

    @_builtins.property
    @pulumi.getter
    def weight(self) -> pulumi.Output[_builtins.int]:
        """
        Rule weight
        """
        return pulumi.get(self, "weight")

