// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Outputs
{

    [OutputType]
    public sealed class CrawlerSitemap
    {
        /// <summary>
        /// Recursively follow sitemap links
        /// </summary>
        public readonly bool? Recursive;
        /// <summary>
        /// Sitemap URL
        /// </summary>
        public readonly string? Url;

        [OutputConstructor]
        private CrawlerSitemap(
            bool? recursive,

            string? url)
        {
            Recursive = recursive;
            Url = url;
        }
    }
}
