// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Outputs
{

    [OutputType]
    public sealed class DomainDnsValidationRecord
    {
        /// <summary>
        /// DNS record name (host/subdomain)
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// DNS record type (typically CNAME)
        /// </summary>
        public readonly string? Type;
        /// <summary>
        /// DNS record value to point to
        /// </summary>
        public readonly string? Value;

        [OutputConstructor]
        private DomainDnsValidationRecord(
            string? name,

            string? type,

            string? value)
        {
            Name = name;
            Type = type;
            Value = value;
        }
    }
}
