// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Outputs
{

    [OutputType]
    public sealed class GetProjectsProjectResult
    {
        public readonly string MachineName;
        public readonly string Name;

        [OutputConstructor]
        private GetProjectsProjectResult(
            string machineName,

            string name)
        {
            MachineName = machineName;
            Name = name;
        }
    }
}
