// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Outputs
{

    [OutputType]
    public sealed class RuleRedirectActionConfig
    {
        /// <summary>
        /// HTTP status code for redirect
        /// </summary>
        public readonly string? StatusCode;
        /// <summary>
        /// Redirect destination URL
        /// </summary>
        public readonly string? To;

        [OutputConstructor]
        private RuleRedirectActionConfig(
            string? statusCode,

            string? to)
        {
            StatusCode = statusCode;
            To = to;
        }
    }
}
