// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Outputs
{

    [OutputType]
    public sealed class RuleProxyWafConfig
    {
        /// <summary>
        /// IP addresses to allow
        /// </summary>
        public readonly ImmutableArray<string> AllowIps;
        /// <summary>
        /// WAF rule IDs to allow/whitelist
        /// </summary>
        public readonly ImmutableArray<string> AllowRules;
        /// <summary>
        /// ASN numbers to block
        /// </summary>
        public readonly ImmutableArray<string> BlockAsns;
        /// <summary>
        /// IP addresses to block
        /// </summary>
        public readonly ImmutableArray<string> BlockIps;
        /// <summary>
        /// Enable predefined block lists
        /// </summary>
        public readonly Outputs.RuleProxyWafConfigBlockLists? BlockLists;
        /// <summary>
        /// Referer patterns to block
        /// </summary>
        public readonly ImmutableArray<string> BlockReferers;
        /// <summary>
        /// User agent patterns to block
        /// </summary>
        public readonly ImmutableArray<string> BlockUas;
        /// <summary>
        /// Project Honey Pot HTTP:BL configuration
        /// </summary>
        public readonly Outputs.RuleProxyWafConfigHttpbl? Httpbl;
        /// <summary>
        /// WAF operation mode
        /// </summary>
        public readonly string? Mode;
        /// <summary>
        /// Email addresses for notifications
        /// </summary>
        public readonly ImmutableArray<string> NotifyEmails;
        /// <summary>
        /// Slack webhook URL for notifications
        /// </summary>
        public readonly string? NotifySlack;
        /// <summary>
        /// Minimum hits per minute to trigger Slack notification
        /// </summary>
        public readonly int? NotifySlackHitsRpm;
        /// <summary>
        /// OWASP paranoia level
        /// </summary>
        public readonly int? ParanoiaLevel;
        /// <summary>
        /// Rate limiting thresholds
        /// </summary>
        public readonly ImmutableArray<Outputs.RuleProxyWafConfigThreshold> Thresholds;

        [OutputConstructor]
        private RuleProxyWafConfig(
            ImmutableArray<string> allowIps,

            ImmutableArray<string> allowRules,

            ImmutableArray<string> blockAsns,

            ImmutableArray<string> blockIps,

            Outputs.RuleProxyWafConfigBlockLists? blockLists,

            ImmutableArray<string> blockReferers,

            ImmutableArray<string> blockUas,

            Outputs.RuleProxyWafConfigHttpbl? httpbl,

            string? mode,

            ImmutableArray<string> notifyEmails,

            string? notifySlack,

            int? notifySlackHitsRpm,

            int? paranoiaLevel,

            ImmutableArray<Outputs.RuleProxyWafConfigThreshold> thresholds)
        {
            AllowIps = allowIps;
            AllowRules = allowRules;
            BlockAsns = blockAsns;
            BlockIps = blockIps;
            BlockLists = blockLists;
            BlockReferers = blockReferers;
            BlockUas = blockUas;
            Httpbl = httpbl;
            Mode = mode;
            NotifyEmails = notifyEmails;
            NotifySlack = notifySlack;
            NotifySlackHitsRpm = notifySlackHitsRpm;
            ParanoiaLevel = paranoiaLevel;
            Thresholds = thresholds;
        }
    }
}
