// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Outputs
{

    [OutputType]
    public sealed class RuleProxyActionConfigQuantCloudSelection
    {
        /// <summary>
        /// Application name
        /// </summary>
        public readonly string? App;
        /// <summary>
        /// Container name
        /// </summary>
        public readonly string? Container;
        /// <summary>
        /// Environment name
        /// </summary>
        public readonly string? Env;
        /// <summary>
        /// Container port
        /// </summary>
        public readonly int? Port;

        [OutputConstructor]
        private RuleProxyActionConfigQuantCloudSelection(
            string? app,

            string? container,

            string? env,

            int? port)
        {
            App = app;
            Container = container;
            Env = env;
            Port = port;
        }
    }
}
