// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Outputs
{

    [OutputType]
    public sealed class RuleCustomResponseActionConfig
    {
        /// <summary>
        /// Custom response body content
        /// </summary>
        public readonly string? CustomResponseBody;
        /// <summary>
        /// HTTP status code for custom response
        /// </summary>
        public readonly int? CustomResponseStatusCode;

        [OutputConstructor]
        private RuleCustomResponseActionConfig(
            string? customResponseBody,

            int? customResponseStatusCode)
        {
            CustomResponseBody = customResponseBody;
            CustomResponseStatusCode = customResponseStatusCode;
        }
    }
}
