// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Inputs
{

    public sealed class CrawlerAssetsNetworkInterceptGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable network intercept
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Execute JavaScript during asset collection
        /// </summary>
        [Input("executeJs")]
        public Input<bool>? ExecuteJs { get; set; }

        /// <summary>
        /// Request timeout in seconds
        /// </summary>
        [Input("timeout")]
        public Input<int>? Timeout { get; set; }

        public CrawlerAssetsNetworkInterceptGetArgs()
        {
        }
        public static new CrawlerAssetsNetworkInterceptGetArgs Empty => new CrawlerAssetsNetworkInterceptGetArgs();
    }
}
