// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Inputs
{

    public sealed class CrawlerAssetsParserGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable parser
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        public CrawlerAssetsParserGetArgs()
        {
        }
        public static new CrawlerAssetsParserGetArgs Empty => new CrawlerAssetsParserGetArgs();
    }
}
