// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Inputs
{

    public sealed class DomainDnsValidationRecordGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// DNS record name (host/subdomain)
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// DNS record type (typically CNAME)
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// DNS record value to point to
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public DomainDnsValidationRecordGetArgs()
        {
        }
        public static new DomainDnsValidationRecordGetArgs Empty => new DomainDnsValidationRecordGetArgs();
    }
}
