// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Inputs
{

    public sealed class DomainDnsGoLiveRecordGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Human-readable instructions for configuring this DNS record
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// DNS record name/host (@ for apex/root domains, subdomain name for subdomains)
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// DNS record type (CNAME, A, or ALIAS)
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// DNS record value (IP addresses for A records, domain name for CNAME/ALIAS)
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public DomainDnsGoLiveRecordGetArgs()
        {
        }
        public static new DomainDnsGoLiveRecordGetArgs Empty => new DomainDnsGoLiveRecordGetArgs();
    }
}
