// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Inputs
{

    public sealed class RuleProxyActionConfigQuantCloudSelectionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Application name
        /// </summary>
        [Input("app")]
        public Input<string>? App { get; set; }

        /// <summary>
        /// Container name
        /// </summary>
        [Input("container")]
        public Input<string>? Container { get; set; }

        /// <summary>
        /// Environment name
        /// </summary>
        [Input("env")]
        public Input<string>? Env { get; set; }

        /// <summary>
        /// Container port
        /// </summary>
        [Input("port")]
        public Input<int>? Port { get; set; }

        public RuleProxyActionConfigQuantCloudSelectionGetArgs()
        {
        }
        public static new RuleProxyActionConfigQuantCloudSelectionGetArgs Empty => new RuleProxyActionConfigQuantCloudSelectionGetArgs();
    }
}
