// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Inputs
{

    public sealed class RuleProxyWafConfigThresholdArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Cooldown period in seconds
        /// </summary>
        [Input("cooldown")]
        public Input<int>? Cooldown { get; set; }

        /// <summary>
        /// Hit count limit (for waf_hit_by_ip)
        /// </summary>
        [Input("hits")]
        public Input<int>? Hits { get; set; }

        /// <summary>
        /// Time window in minutes (for waf_hit_by_ip)
        /// </summary>
        [Input("minutes")]
        public Input<int>? Minutes { get; set; }

        /// <summary>
        /// Threshold enforcement mode
        /// </summary>
        [Input("mode")]
        public Input<string>? Mode { get; set; }

        /// <summary>
        /// Slack webhook for this threshold
        /// </summary>
        [Input("notifySlack")]
        public Input<string>? NotifySlack { get; set; }

        /// <summary>
        /// Requests per second limit (for ip/header)
        /// </summary>
        [Input("rps")]
        public Input<int>? Rps { get; set; }

        /// <summary>
        /// Threshold type
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        /// <summary>
        /// Header name (for header type)
        /// </summary>
        [Input("value")]
        public Input<string>? Value { get; set; }

        public RuleProxyWafConfigThresholdArgs()
        {
        }
        public static new RuleProxyWafConfigThresholdArgs Empty => new RuleProxyWafConfigThresholdArgs();
    }
}
