// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Inputs
{

    public sealed class RuleProxyActionConfigWafConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowIps")]
        private InputList<string>? _allowIps;

        /// <summary>
        /// IP addresses to allow
        /// </summary>
        public InputList<string> AllowIps
        {
            get => _allowIps ?? (_allowIps = new InputList<string>());
            set => _allowIps = value;
        }

        [Input("allowRules")]
        private InputList<string>? _allowRules;

        /// <summary>
        /// WAF rule IDs to allow/whitelist
        /// </summary>
        public InputList<string> AllowRules
        {
            get => _allowRules ?? (_allowRules = new InputList<string>());
            set => _allowRules = value;
        }

        [Input("blockAsns")]
        private InputList<string>? _blockAsns;

        /// <summary>
        /// ASN numbers to block
        /// </summary>
        public InputList<string> BlockAsns
        {
            get => _blockAsns ?? (_blockAsns = new InputList<string>());
            set => _blockAsns = value;
        }

        [Input("blockIps")]
        private InputList<string>? _blockIps;

        /// <summary>
        /// IP addresses to block
        /// </summary>
        public InputList<string> BlockIps
        {
            get => _blockIps ?? (_blockIps = new InputList<string>());
            set => _blockIps = value;
        }

        /// <summary>
        /// Enable predefined block lists
        /// </summary>
        [Input("blockLists")]
        public Input<Inputs.RuleProxyActionConfigWafConfigBlockListsGetArgs>? BlockLists { get; set; }

        [Input("blockReferers")]
        private InputList<string>? _blockReferers;

        /// <summary>
        /// Referer patterns to block
        /// </summary>
        public InputList<string> BlockReferers
        {
            get => _blockReferers ?? (_blockReferers = new InputList<string>());
            set => _blockReferers = value;
        }

        [Input("blockUas")]
        private InputList<string>? _blockUas;

        /// <summary>
        /// User agent patterns to block
        /// </summary>
        public InputList<string> BlockUas
        {
            get => _blockUas ?? (_blockUas = new InputList<string>());
            set => _blockUas = value;
        }

        /// <summary>
        /// Project Honey Pot HTTP:BL configuration
        /// </summary>
        [Input("httpbl")]
        public Input<Inputs.RuleProxyActionConfigWafConfigHttpblGetArgs>? Httpbl { get; set; }

        /// <summary>
        /// WAF operation mode
        /// </summary>
        [Input("mode")]
        public Input<string>? Mode { get; set; }

        [Input("notifyEmails")]
        private InputList<string>? _notifyEmails;

        /// <summary>
        /// Email addresses for notifications
        /// </summary>
        public InputList<string> NotifyEmails
        {
            get => _notifyEmails ?? (_notifyEmails = new InputList<string>());
            set => _notifyEmails = value;
        }

        /// <summary>
        /// Slack webhook URL for notifications
        /// </summary>
        [Input("notifySlack")]
        public Input<string>? NotifySlack { get; set; }

        /// <summary>
        /// Minimum hits per minute to trigger Slack notification
        /// </summary>
        [Input("notifySlackHitsRpm")]
        public Input<int>? NotifySlackHitsRpm { get; set; }

        /// <summary>
        /// OWASP paranoia level
        /// </summary>
        [Input("paranoiaLevel")]
        public Input<int>? ParanoiaLevel { get; set; }

        [Input("thresholds")]
        private InputList<Inputs.RuleProxyActionConfigWafConfigThresholdGetArgs>? _thresholds;

        /// <summary>
        /// Rate limiting thresholds
        /// </summary>
        public InputList<Inputs.RuleProxyActionConfigWafConfigThresholdGetArgs> Thresholds
        {
            get => _thresholds ?? (_thresholds = new InputList<Inputs.RuleProxyActionConfigWafConfigThresholdGetArgs>());
            set => _thresholds = value;
        }

        public RuleProxyActionConfigWafConfigGetArgs()
        {
        }
        public static new RuleProxyActionConfigWafConfigGetArgs Empty => new RuleProxyActionConfigWafConfigGetArgs();
    }
}
