// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Inputs
{

    public sealed class RuleServeStaticActionConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Path to the static file to serve
        /// </summary>
        [Input("staticFilePath")]
        public Input<string>? StaticFilePath { get; set; }

        public RuleServeStaticActionConfigArgs()
        {
        }
        public static new RuleServeStaticActionConfigArgs Empty => new RuleServeStaticActionConfigArgs();
    }
}
