// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Inputs
{

    public sealed class RuleBotChallengeActionConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Challenge TTL in seconds
        /// </summary>
        [Input("robotChallengeChallengeTtl")]
        public Input<int>? RobotChallengeChallengeTtl { get; set; }

        /// <summary>
        /// Challenge type (invisible or checkbox)
        /// </summary>
        [Input("robotChallengeType")]
        public Input<string>? RobotChallengeType { get; set; }

        /// <summary>
        /// Verification TTL in seconds
        /// </summary>
        [Input("robotChallengeVerificationTtl")]
        public Input<int>? RobotChallengeVerificationTtl { get; set; }

        public RuleBotChallengeActionConfigArgs()
        {
        }
        public static new RuleBotChallengeActionConfigArgs Empty => new RuleBotChallengeActionConfigArgs();
    }
}
