// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace QuantCDN.Quant.Inputs
{

    public sealed class RuleHeadersActionConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("headers")]
        private InputMap<string>? _headers;

        /// <summary>
        /// Headers to set
        /// </summary>
        public InputMap<string> Headers
        {
            get => _headers ?? (_headers = new InputMap<string>());
            set => _headers = value;
        }

        public RuleHeadersActionConfigGetArgs()
        {
        }
        public static new RuleHeadersActionConfigGetArgs Empty => new RuleHeadersActionConfigGetArgs();
    }
}
