// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Application extends pulumi.CustomResource {
    /**
     * Get an existing Application resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ApplicationState, opts?: pulumi.CustomResourceOptions): Application {
        return new Application(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'quant:index:Application';

    /**
     * Returns true if the given object is an instance of Application.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Application {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Application.__pulumiType;
    }

    /**
     * Application name
     */
    declare public readonly appName: pulumi.Output<string>;
    /**
     * Compose definition as a JSON string. Defines containers, CPU, memory, networking, and other task configuration.
     */
    declare public readonly composeDefinition: pulumi.Output<string>;
    /**
     * List of container names as a JSON array
     */
    declare public /*out*/ readonly containerNames: pulumi.Output<string>;
    /**
     * Database engine type (mysql, postgres)
     */
    declare public readonly databaseEngine: pulumi.Output<string>;
    /**
     * RDS instance class
     */
    declare public readonly databaseInstanceClass: pulumi.Output<string>;
    /**
     * Enable Multi-AZ database deployment
     */
    declare public readonly databaseMultiAz: pulumi.Output<boolean>;
    /**
     * Database allocated storage in GiB
     */
    declare public readonly databaseStorageGb: pulumi.Output<number>;
    /**
     * Desired task count
     */
    declare public /*out*/ readonly desiredCount: pulumi.Output<number>;
    /**
     * Initial environment variables as a JSON array of {name, value} objects
     */
    declare public readonly environment: pulumi.Output<string>;
    /**
     * Mount path inside containers for the shared filesystem
     */
    declare public readonly filesystemMountPath: pulumi.Output<string>;
    /**
     * Whether to create a shared filesystem
     */
    declare public readonly filesystemRequired: pulumi.Output<boolean>;
    /**
     * Maximum task count for auto-scaling
     */
    declare public readonly maxCapacity: pulumi.Output<number>;
    /**
     * Minimum task count for auto-scaling
     */
    declare public readonly minCapacity: pulumi.Output<number>;
    /**
     * Organization machine name. Defaults to the provider-level organization.
     */
    declare public readonly organization: pulumi.Output<string>;
    /**
     * Currently running task count
     */
    declare public /*out*/ readonly runningCount: pulumi.Output<number>;
    /**
     * Application status
     */
    declare public /*out*/ readonly status: pulumi.Output<string>;

    /**
     * Create a Application resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApplicationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ApplicationArgs | ApplicationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ApplicationState | undefined;
            resourceInputs["appName"] = state?.appName;
            resourceInputs["composeDefinition"] = state?.composeDefinition;
            resourceInputs["containerNames"] = state?.containerNames;
            resourceInputs["databaseEngine"] = state?.databaseEngine;
            resourceInputs["databaseInstanceClass"] = state?.databaseInstanceClass;
            resourceInputs["databaseMultiAz"] = state?.databaseMultiAz;
            resourceInputs["databaseStorageGb"] = state?.databaseStorageGb;
            resourceInputs["desiredCount"] = state?.desiredCount;
            resourceInputs["environment"] = state?.environment;
            resourceInputs["filesystemMountPath"] = state?.filesystemMountPath;
            resourceInputs["filesystemRequired"] = state?.filesystemRequired;
            resourceInputs["maxCapacity"] = state?.maxCapacity;
            resourceInputs["minCapacity"] = state?.minCapacity;
            resourceInputs["organization"] = state?.organization;
            resourceInputs["runningCount"] = state?.runningCount;
            resourceInputs["status"] = state?.status;
        } else {
            const args = argsOrState as ApplicationArgs | undefined;
            if (args?.appName === undefined && !opts.urn) {
                throw new Error("Missing required property 'appName'");
            }
            if (args?.composeDefinition === undefined && !opts.urn) {
                throw new Error("Missing required property 'composeDefinition'");
            }
            resourceInputs["appName"] = args?.appName;
            resourceInputs["composeDefinition"] = args?.composeDefinition;
            resourceInputs["databaseEngine"] = args?.databaseEngine;
            resourceInputs["databaseInstanceClass"] = args?.databaseInstanceClass;
            resourceInputs["databaseMultiAz"] = args?.databaseMultiAz;
            resourceInputs["databaseStorageGb"] = args?.databaseStorageGb;
            resourceInputs["environment"] = args?.environment;
            resourceInputs["filesystemMountPath"] = args?.filesystemMountPath;
            resourceInputs["filesystemRequired"] = args?.filesystemRequired;
            resourceInputs["maxCapacity"] = args?.maxCapacity;
            resourceInputs["minCapacity"] = args?.minCapacity;
            resourceInputs["organization"] = args?.organization;
            resourceInputs["containerNames"] = undefined /*out*/;
            resourceInputs["desiredCount"] = undefined /*out*/;
            resourceInputs["runningCount"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Application.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Application resources.
 */
export interface ApplicationState {
    /**
     * Application name
     */
    appName?: pulumi.Input<string>;
    /**
     * Compose definition as a JSON string. Defines containers, CPU, memory, networking, and other task configuration.
     */
    composeDefinition?: pulumi.Input<string>;
    /**
     * List of container names as a JSON array
     */
    containerNames?: pulumi.Input<string>;
    /**
     * Database engine type (mysql, postgres)
     */
    databaseEngine?: pulumi.Input<string>;
    /**
     * RDS instance class
     */
    databaseInstanceClass?: pulumi.Input<string>;
    /**
     * Enable Multi-AZ database deployment
     */
    databaseMultiAz?: pulumi.Input<boolean>;
    /**
     * Database allocated storage in GiB
     */
    databaseStorageGb?: pulumi.Input<number>;
    /**
     * Desired task count
     */
    desiredCount?: pulumi.Input<number>;
    /**
     * Initial environment variables as a JSON array of {name, value} objects
     */
    environment?: pulumi.Input<string>;
    /**
     * Mount path inside containers for the shared filesystem
     */
    filesystemMountPath?: pulumi.Input<string>;
    /**
     * Whether to create a shared filesystem
     */
    filesystemRequired?: pulumi.Input<boolean>;
    /**
     * Maximum task count for auto-scaling
     */
    maxCapacity?: pulumi.Input<number>;
    /**
     * Minimum task count for auto-scaling
     */
    minCapacity?: pulumi.Input<number>;
    /**
     * Organization machine name. Defaults to the provider-level organization.
     */
    organization?: pulumi.Input<string>;
    /**
     * Currently running task count
     */
    runningCount?: pulumi.Input<number>;
    /**
     * Application status
     */
    status?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Application resource.
 */
export interface ApplicationArgs {
    /**
     * Application name
     */
    appName: pulumi.Input<string>;
    /**
     * Compose definition as a JSON string. Defines containers, CPU, memory, networking, and other task configuration.
     */
    composeDefinition: pulumi.Input<string>;
    /**
     * Database engine type (mysql, postgres)
     */
    databaseEngine?: pulumi.Input<string>;
    /**
     * RDS instance class
     */
    databaseInstanceClass?: pulumi.Input<string>;
    /**
     * Enable Multi-AZ database deployment
     */
    databaseMultiAz?: pulumi.Input<boolean>;
    /**
     * Database allocated storage in GiB
     */
    databaseStorageGb?: pulumi.Input<number>;
    /**
     * Initial environment variables as a JSON array of {name, value} objects
     */
    environment?: pulumi.Input<string>;
    /**
     * Mount path inside containers for the shared filesystem
     */
    filesystemMountPath?: pulumi.Input<string>;
    /**
     * Whether to create a shared filesystem
     */
    filesystemRequired?: pulumi.Input<boolean>;
    /**
     * Maximum task count for auto-scaling
     */
    maxCapacity?: pulumi.Input<number>;
    /**
     * Minimum task count for auto-scaling
     */
    minCapacity?: pulumi.Input<number>;
    /**
     * Organization machine name. Defaults to the provider-level organization.
     */
    organization?: pulumi.Input<string>;
}
