// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Crawler extends pulumi.CustomResource {
    /**
     * Get an existing Crawler resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CrawlerState, opts?: pulumi.CustomResourceOptions): Crawler {
        return new Crawler(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'quant:index:Crawler';

    /**
     * Returns true if the given object is an instance of Crawler.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Crawler {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Crawler.__pulumiType;
    }

    /**
     * Allowed domains for multi-domain crawling, automatically enables merge_domains
     */
    declare public readonly allowedDomains: pulumi.Output<string[]>;
    /**
     * Asset harvesting configuration
     */
    declare public readonly assets: pulumi.Output<outputs.CrawlerAssets>;
    /**
     * Enable browser mode
     */
    declare public readonly browserMode: pulumi.Output<boolean>;
    /**
     * Crawler configuration (YAML)
     */
    declare public /*out*/ readonly config: pulumi.Output<string>;
    declare public readonly crawler: pulumi.Output<string>;
    /**
     * Creation timestamp
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * Delay between requests in seconds (default: 4, non-default requires verification)
     */
    declare public readonly delay: pulumi.Output<number>;
    /**
     * Deletion timestamp
     */
    declare public /*out*/ readonly deletedAt: pulumi.Output<string>;
    /**
     * Maximum crawl depth, -1 for unlimited
     */
    declare public readonly depth: pulumi.Output<number>;
    /**
     * Domain to crawl
     */
    declare public readonly domain: pulumi.Output<string>;
    /**
     * Domain verification status
     */
    declare public /*out*/ readonly domainVerified: pulumi.Output<number>;
    /**
     * URL patterns to exclude (regex)
     */
    declare public readonly excludes: pulumi.Output<string[]>;
    /**
     * Custom headers
     */
    declare public readonly headers: pulumi.Output<{[key: string]: string}>;
    /**
     * URL patterns to include (regex)
     */
    declare public readonly includes: pulumi.Output<string[]>;
    /**
     * Maximum errors before stopping crawl
     */
    declare public readonly maxErrors: pulumi.Output<number>;
    /**
     * Maximum total requests, 0 for unlimited (default: 0, non-default requires verification)
     */
    declare public readonly maxHits: pulumi.Output<number>;
    /**
     * Maximum HTML pages, 0 for unlimited (default: org limit, non-default requires verification)
     */
    declare public readonly maxHtml: pulumi.Output<number>;
    /**
     * Crawler name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Organization identifier
     */
    declare public readonly organization: pulumi.Output<string>;
    /**
     * Project identifier
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * Project ID
     */
    declare public /*out*/ readonly projectId: pulumi.Output<number>;
    /**
     * Sitemap configuration
     */
    declare public readonly sitemaps: pulumi.Output<outputs.CrawlerSitemap[]>;
    /**
     * Starting URLs for crawl
     */
    declare public readonly startUrls: pulumi.Output<string[]>;
    /**
     * HTTP status codes that will result in content being captured and pushed to Quant
     */
    declare public readonly statusOks: pulumi.Output<number[]>;
    /**
     * Last update timestamp
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;
    /**
     * URLs to crawl
     */
    declare public readonly urls: pulumi.Output<string[]>;
    /**
     * URLs list (YAML)
     */
    declare public /*out*/ readonly urlsList: pulumi.Output<string>;
    /**
     * Custom user agent, only when browserMode is false
     */
    declare public readonly userAgent: pulumi.Output<string>;
    /**
     * Crawler UUID
     */
    declare public /*out*/ readonly uuid: pulumi.Output<string>;
    /**
     * Authorization header for webhook
     */
    declare public readonly webhookAuthHeader: pulumi.Output<string>;
    /**
     * Extra variables for webhook
     */
    declare public readonly webhookExtraVars: pulumi.Output<string>;
    /**
     * Webhook URL for notifications
     */
    declare public readonly webhookUrl: pulumi.Output<string>;
    /**
     * Number of concurrent workers (default: 2, non-default requires verification)
     */
    declare public readonly workers: pulumi.Output<number>;

    /**
     * Create a Crawler resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CrawlerArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CrawlerArgs | CrawlerState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CrawlerState | undefined;
            resourceInputs["allowedDomains"] = state?.allowedDomains;
            resourceInputs["assets"] = state?.assets;
            resourceInputs["browserMode"] = state?.browserMode;
            resourceInputs["config"] = state?.config;
            resourceInputs["crawler"] = state?.crawler;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["delay"] = state?.delay;
            resourceInputs["deletedAt"] = state?.deletedAt;
            resourceInputs["depth"] = state?.depth;
            resourceInputs["domain"] = state?.domain;
            resourceInputs["domainVerified"] = state?.domainVerified;
            resourceInputs["excludes"] = state?.excludes;
            resourceInputs["headers"] = state?.headers;
            resourceInputs["includes"] = state?.includes;
            resourceInputs["maxErrors"] = state?.maxErrors;
            resourceInputs["maxHits"] = state?.maxHits;
            resourceInputs["maxHtml"] = state?.maxHtml;
            resourceInputs["name"] = state?.name;
            resourceInputs["organization"] = state?.organization;
            resourceInputs["project"] = state?.project;
            resourceInputs["projectId"] = state?.projectId;
            resourceInputs["sitemaps"] = state?.sitemaps;
            resourceInputs["startUrls"] = state?.startUrls;
            resourceInputs["statusOks"] = state?.statusOks;
            resourceInputs["updatedAt"] = state?.updatedAt;
            resourceInputs["urls"] = state?.urls;
            resourceInputs["urlsList"] = state?.urlsList;
            resourceInputs["userAgent"] = state?.userAgent;
            resourceInputs["uuid"] = state?.uuid;
            resourceInputs["webhookAuthHeader"] = state?.webhookAuthHeader;
            resourceInputs["webhookExtraVars"] = state?.webhookExtraVars;
            resourceInputs["webhookUrl"] = state?.webhookUrl;
            resourceInputs["workers"] = state?.workers;
        } else {
            const args = argsOrState as CrawlerArgs | undefined;
            if (args?.domain === undefined && !opts.urn) {
                throw new Error("Missing required property 'domain'");
            }
            resourceInputs["allowedDomains"] = args?.allowedDomains;
            resourceInputs["assets"] = args?.assets;
            resourceInputs["browserMode"] = args?.browserMode;
            resourceInputs["crawler"] = args?.crawler;
            resourceInputs["delay"] = args?.delay;
            resourceInputs["depth"] = args?.depth;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["excludes"] = args?.excludes;
            resourceInputs["headers"] = args?.headers;
            resourceInputs["includes"] = args?.includes;
            resourceInputs["maxErrors"] = args?.maxErrors;
            resourceInputs["maxHits"] = args?.maxHits;
            resourceInputs["maxHtml"] = args?.maxHtml;
            resourceInputs["name"] = args?.name;
            resourceInputs["organization"] = args?.organization;
            resourceInputs["project"] = args?.project;
            resourceInputs["sitemaps"] = args?.sitemaps;
            resourceInputs["startUrls"] = args?.startUrls;
            resourceInputs["statusOks"] = args?.statusOks;
            resourceInputs["urls"] = args?.urls;
            resourceInputs["userAgent"] = args?.userAgent;
            resourceInputs["webhookAuthHeader"] = args?.webhookAuthHeader;
            resourceInputs["webhookExtraVars"] = args?.webhookExtraVars;
            resourceInputs["webhookUrl"] = args?.webhookUrl;
            resourceInputs["workers"] = args?.workers;
            resourceInputs["config"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["deletedAt"] = undefined /*out*/;
            resourceInputs["domainVerified"] = undefined /*out*/;
            resourceInputs["projectId"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
            resourceInputs["urlsList"] = undefined /*out*/;
            resourceInputs["uuid"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Crawler.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Crawler resources.
 */
export interface CrawlerState {
    /**
     * Allowed domains for multi-domain crawling, automatically enables merge_domains
     */
    allowedDomains?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Asset harvesting configuration
     */
    assets?: pulumi.Input<inputs.CrawlerAssets>;
    /**
     * Enable browser mode
     */
    browserMode?: pulumi.Input<boolean>;
    /**
     * Crawler configuration (YAML)
     */
    config?: pulumi.Input<string>;
    crawler?: pulumi.Input<string>;
    /**
     * Creation timestamp
     */
    createdAt?: pulumi.Input<string>;
    /**
     * Delay between requests in seconds (default: 4, non-default requires verification)
     */
    delay?: pulumi.Input<number>;
    /**
     * Deletion timestamp
     */
    deletedAt?: pulumi.Input<string>;
    /**
     * Maximum crawl depth, -1 for unlimited
     */
    depth?: pulumi.Input<number>;
    /**
     * Domain to crawl
     */
    domain?: pulumi.Input<string>;
    /**
     * Domain verification status
     */
    domainVerified?: pulumi.Input<number>;
    /**
     * URL patterns to exclude (regex)
     */
    excludes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Custom headers
     */
    headers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * URL patterns to include (regex)
     */
    includes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Maximum errors before stopping crawl
     */
    maxErrors?: pulumi.Input<number>;
    /**
     * Maximum total requests, 0 for unlimited (default: 0, non-default requires verification)
     */
    maxHits?: pulumi.Input<number>;
    /**
     * Maximum HTML pages, 0 for unlimited (default: org limit, non-default requires verification)
     */
    maxHtml?: pulumi.Input<number>;
    /**
     * Crawler name
     */
    name?: pulumi.Input<string>;
    /**
     * Organization identifier
     */
    organization?: pulumi.Input<string>;
    /**
     * Project identifier
     */
    project?: pulumi.Input<string>;
    /**
     * Project ID
     */
    projectId?: pulumi.Input<number>;
    /**
     * Sitemap configuration
     */
    sitemaps?: pulumi.Input<pulumi.Input<inputs.CrawlerSitemap>[]>;
    /**
     * Starting URLs for crawl
     */
    startUrls?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * HTTP status codes that will result in content being captured and pushed to Quant
     */
    statusOks?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * Last update timestamp
     */
    updatedAt?: pulumi.Input<string>;
    /**
     * URLs to crawl
     */
    urls?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * URLs list (YAML)
     */
    urlsList?: pulumi.Input<string>;
    /**
     * Custom user agent, only when browserMode is false
     */
    userAgent?: pulumi.Input<string>;
    /**
     * Crawler UUID
     */
    uuid?: pulumi.Input<string>;
    /**
     * Authorization header for webhook
     */
    webhookAuthHeader?: pulumi.Input<string>;
    /**
     * Extra variables for webhook
     */
    webhookExtraVars?: pulumi.Input<string>;
    /**
     * Webhook URL for notifications
     */
    webhookUrl?: pulumi.Input<string>;
    /**
     * Number of concurrent workers (default: 2, non-default requires verification)
     */
    workers?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Crawler resource.
 */
export interface CrawlerArgs {
    /**
     * Allowed domains for multi-domain crawling, automatically enables merge_domains
     */
    allowedDomains?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Asset harvesting configuration
     */
    assets?: pulumi.Input<inputs.CrawlerAssets>;
    /**
     * Enable browser mode
     */
    browserMode?: pulumi.Input<boolean>;
    crawler?: pulumi.Input<string>;
    /**
     * Delay between requests in seconds (default: 4, non-default requires verification)
     */
    delay?: pulumi.Input<number>;
    /**
     * Maximum crawl depth, -1 for unlimited
     */
    depth?: pulumi.Input<number>;
    /**
     * Domain to crawl
     */
    domain: pulumi.Input<string>;
    /**
     * URL patterns to exclude (regex)
     */
    excludes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Custom headers
     */
    headers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * URL patterns to include (regex)
     */
    includes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Maximum errors before stopping crawl
     */
    maxErrors?: pulumi.Input<number>;
    /**
     * Maximum total requests, 0 for unlimited (default: 0, non-default requires verification)
     */
    maxHits?: pulumi.Input<number>;
    /**
     * Maximum HTML pages, 0 for unlimited (default: org limit, non-default requires verification)
     */
    maxHtml?: pulumi.Input<number>;
    /**
     * Crawler name
     */
    name?: pulumi.Input<string>;
    /**
     * Organization identifier
     */
    organization?: pulumi.Input<string>;
    /**
     * Project identifier
     */
    project?: pulumi.Input<string>;
    /**
     * Sitemap configuration
     */
    sitemaps?: pulumi.Input<pulumi.Input<inputs.CrawlerSitemap>[]>;
    /**
     * Starting URLs for crawl
     */
    startUrls?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * HTTP status codes that will result in content being captured and pushed to Quant
     */
    statusOks?: pulumi.Input<pulumi.Input<number>[]>;
    /**
     * URLs to crawl
     */
    urls?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Custom user agent, only when browserMode is false
     */
    userAgent?: pulumi.Input<string>;
    /**
     * Authorization header for webhook
     */
    webhookAuthHeader?: pulumi.Input<string>;
    /**
     * Extra variables for webhook
     */
    webhookExtraVars?: pulumi.Input<string>;
    /**
     * Webhook URL for notifications
     */
    webhookUrl?: pulumi.Input<string>;
    /**
     * Number of concurrent workers (default: 2, non-default requires verification)
     */
    workers?: pulumi.Input<number>;
}
