// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CronJob extends pulumi.CustomResource {
    /**
     * Get an existing CronJob resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: CronJobState, opts?: pulumi.CustomResourceOptions): CronJob {
        return new CronJob(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'quant:index:CronJob';

    /**
     * Returns true if the given object is an instance of CronJob.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CronJob {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CronJob.__pulumiType;
    }

    /**
     * Application name
     */
    declare public readonly application: pulumi.Output<string>;
    /**
     * Command to execute as a JSON array of strings
     */
    declare public readonly command: pulumi.Output<string>;
    /**
     * Cron job description
     */
    declare public readonly description: pulumi.Output<string>;
    /**
     * Environment name
     */
    declare public readonly environment: pulumi.Output<string>;
    /**
     * Whether the cron job is enabled
     */
    declare public readonly isEnabled: pulumi.Output<boolean>;
    /**
     * Cron job name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Organization machine name (defaults to provider organization)
     */
    declare public readonly organization: pulumi.Output<string>;
    /**
     * Resolved cron schedule
     */
    declare public /*out*/ readonly schedule: pulumi.Output<string>;
    /**
     * Cron schedule expression
     */
    declare public readonly scheduleExpression: pulumi.Output<string>;
    /**
     * Target container name
     */
    declare public readonly targetContainerName: pulumi.Output<string>;

    /**
     * Create a CronJob resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CronJobArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: CronJobArgs | CronJobState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as CronJobState | undefined;
            resourceInputs["application"] = state?.application;
            resourceInputs["command"] = state?.command;
            resourceInputs["description"] = state?.description;
            resourceInputs["environment"] = state?.environment;
            resourceInputs["isEnabled"] = state?.isEnabled;
            resourceInputs["name"] = state?.name;
            resourceInputs["organization"] = state?.organization;
            resourceInputs["schedule"] = state?.schedule;
            resourceInputs["scheduleExpression"] = state?.scheduleExpression;
            resourceInputs["targetContainerName"] = state?.targetContainerName;
        } else {
            const args = argsOrState as CronJobArgs | undefined;
            if (args?.application === undefined && !opts.urn) {
                throw new Error("Missing required property 'application'");
            }
            if (args?.command === undefined && !opts.urn) {
                throw new Error("Missing required property 'command'");
            }
            if (args?.environment === undefined && !opts.urn) {
                throw new Error("Missing required property 'environment'");
            }
            if (args?.scheduleExpression === undefined && !opts.urn) {
                throw new Error("Missing required property 'scheduleExpression'");
            }
            resourceInputs["application"] = args?.application;
            resourceInputs["command"] = args?.command;
            resourceInputs["description"] = args?.description;
            resourceInputs["environment"] = args?.environment;
            resourceInputs["isEnabled"] = args?.isEnabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["organization"] = args?.organization;
            resourceInputs["scheduleExpression"] = args?.scheduleExpression;
            resourceInputs["targetContainerName"] = args?.targetContainerName;
            resourceInputs["schedule"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CronJob.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering CronJob resources.
 */
export interface CronJobState {
    /**
     * Application name
     */
    application?: pulumi.Input<string>;
    /**
     * Command to execute as a JSON array of strings
     */
    command?: pulumi.Input<string>;
    /**
     * Cron job description
     */
    description?: pulumi.Input<string>;
    /**
     * Environment name
     */
    environment?: pulumi.Input<string>;
    /**
     * Whether the cron job is enabled
     */
    isEnabled?: pulumi.Input<boolean>;
    /**
     * Cron job name
     */
    name?: pulumi.Input<string>;
    /**
     * Organization machine name (defaults to provider organization)
     */
    organization?: pulumi.Input<string>;
    /**
     * Resolved cron schedule
     */
    schedule?: pulumi.Input<string>;
    /**
     * Cron schedule expression
     */
    scheduleExpression?: pulumi.Input<string>;
    /**
     * Target container name
     */
    targetContainerName?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a CronJob resource.
 */
export interface CronJobArgs {
    /**
     * Application name
     */
    application: pulumi.Input<string>;
    /**
     * Command to execute as a JSON array of strings
     */
    command: pulumi.Input<string>;
    /**
     * Cron job description
     */
    description?: pulumi.Input<string>;
    /**
     * Environment name
     */
    environment: pulumi.Input<string>;
    /**
     * Whether the cron job is enabled
     */
    isEnabled?: pulumi.Input<boolean>;
    /**
     * Cron job name
     */
    name?: pulumi.Input<string>;
    /**
     * Organization machine name (defaults to provider organization)
     */
    organization?: pulumi.Input<string>;
    /**
     * Cron schedule expression
     */
    scheduleExpression: pulumi.Input<string>;
    /**
     * Target container name
     */
    targetContainerName?: pulumi.Input<string>;
}
