// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getProject(args: GetProjectArgs, opts?: pulumi.InvokeOptions): Promise<GetProjectResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("quant:index:getProject", {
        "machineName": args.machineName,
        "withToken": args.withToken,
    }, opts);
}

/**
 * A collection of arguments for invoking getProject.
 */
export interface GetProjectArgs {
    machineName: string;
    withToken?: boolean;
}

/**
 * A collection of values returned by getProject.
 */
export interface GetProjectResult {
    readonly createdAt: string;
    readonly gitUrl: string;
    readonly id: number;
    readonly machineName: string;
    readonly name: string;
    readonly organizationId: number;
    readonly region: string;
    readonly securityScore: string;
    readonly updatedAt: string;
    readonly uuid: string;
    readonly withToken?: boolean;
    readonly writeToken: string;
}
export function getProjectOutput(args: GetProjectOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetProjectResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("quant:index:getProject", {
        "machineName": args.machineName,
        "withToken": args.withToken,
    }, opts);
}

/**
 * A collection of arguments for invoking getProject.
 */
export interface GetProjectOutputArgs {
    machineName: pulumi.Input<string>;
    withToken?: pulumi.Input<boolean>;
}
