// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class KvStore extends pulumi.CustomResource {
    /**
     * Get an existing KvStore resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: KvStoreState, opts?: pulumi.CustomResourceOptions): KvStore {
        return new KvStore(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'quant:index:KvStore';

    /**
     * Returns true if the given object is an instance of KvStore.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is KvStore {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === KvStore.__pulumiType;
    }

    /**
     * Store name
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Organization machine name (defaults to provider organization)
     */
    declare public readonly organization: pulumi.Output<string>;
    /**
     * Project machine name
     */
    declare public readonly project: pulumi.Output<string>;
    /**
     * Store ID
     */
    declare public /*out*/ readonly storeId: pulumi.Output<string>;

    /**
     * Create a KvStore resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: KvStoreArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: KvStoreArgs | KvStoreState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as KvStoreState | undefined;
            resourceInputs["name"] = state?.name;
            resourceInputs["organization"] = state?.organization;
            resourceInputs["project"] = state?.project;
            resourceInputs["storeId"] = state?.storeId;
        } else {
            const args = argsOrState as KvStoreArgs | undefined;
            if (args?.project === undefined && !opts.urn) {
                throw new Error("Missing required property 'project'");
            }
            resourceInputs["name"] = args?.name;
            resourceInputs["organization"] = args?.organization;
            resourceInputs["project"] = args?.project;
            resourceInputs["storeId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(KvStore.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering KvStore resources.
 */
export interface KvStoreState {
    /**
     * Store name
     */
    name?: pulumi.Input<string>;
    /**
     * Organization machine name (defaults to provider organization)
     */
    organization?: pulumi.Input<string>;
    /**
     * Project machine name
     */
    project?: pulumi.Input<string>;
    /**
     * Store ID
     */
    storeId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a KvStore resource.
 */
export interface KvStoreArgs {
    /**
     * Store name
     */
    name?: pulumi.Input<string>;
    /**
     * Organization machine name (defaults to provider organization)
     */
    organization?: pulumi.Input<string>;
    /**
     * Project machine name
     */
    project: pulumi.Input<string>;
}
