// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the quant package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'quant';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * The base URL for the QuantCDN API. Can also be set via QUANTCDN_BASE_URL environment variable.
     */
    declare public readonly baseUrl: pulumi.Output<string | undefined>;
    /**
     * The QuantCDN API Bearer token used to authenticate requests. Can also be set via QUANTCDN_API_TOKEN environment variable.
     */
    declare public readonly bearer: pulumi.Output<string | undefined>;
    /**
     * The QuantCDN organization machine name. Can also be set via QUANTCDN_ORGANIZATION environment variable.
     */
    declare public readonly organization: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["baseDelayMs"] = pulumi.output(args?.baseDelayMs).apply(JSON.stringify);
            resourceInputs["baseUrl"] = args?.baseUrl;
            resourceInputs["bearer"] = args?.bearer ? pulumi.secret(args.bearer) : undefined;
            resourceInputs["enableJitter"] = pulumi.output(args?.enableJitter).apply(JSON.stringify);
            resourceInputs["maxDelayMs"] = pulumi.output(args?.maxDelayMs).apply(JSON.stringify);
            resourceInputs["maxRetries"] = pulumi.output(args?.maxRetries).apply(JSON.stringify);
            resourceInputs["organization"] = args?.organization;
            resourceInputs["requestsPerSecond"] = pulumi.output(args?.requestsPerSecond).apply(JSON.stringify);
            resourceInputs["timeoutSeconds"] = pulumi.output(args?.timeoutSeconds).apply(JSON.stringify);
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["bearer"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }

    /**
     * This function returns a Terraform config object with terraform-namecased keys,to be used with the Terraform Module Provider.
     */
    terraformConfig(): pulumi.Output<Provider.TerraformConfigResult> {
        return pulumi.runtime.call("pulumi:providers:quant/terraformConfig", {
            "__self__": this,
        }, this);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Base delay in milliseconds for exponential backoff. Defaults to 500
     */
    baseDelayMs?: pulumi.Input<number>;
    /**
     * The base URL for the QuantCDN API. Can also be set via QUANTCDN_BASE_URL environment variable.
     */
    baseUrl?: pulumi.Input<string>;
    /**
     * The QuantCDN API Bearer token used to authenticate requests. Can also be set via QUANTCDN_API_TOKEN environment variable.
     */
    bearer?: pulumi.Input<string>;
    /**
     * Whether to add random jitter to retry delays to avoid thundering herd. Defaults to true
     */
    enableJitter?: pulumi.Input<boolean>;
    /**
     * Maximum delay in milliseconds for exponential backoff. Defaults to 30000 (30 seconds)
     */
    maxDelayMs?: pulumi.Input<number>;
    /**
     * Maximum number of retry attempts for failed requests. Defaults to 3
     */
    maxRetries?: pulumi.Input<number>;
    /**
     * The QuantCDN organization machine name. Can also be set via QUANTCDN_ORGANIZATION environment variable.
     */
    organization?: pulumi.Input<string>;
    /**
     * Maximum number of requests per second to send to the API. Defaults to 10.0
     */
    requestsPerSecond?: pulumi.Input<number>;
    /**
     * HTTP client timeout in seconds for API requests. Defaults to 120 seconds to handle slow operations and potential deadlocks. Can also be set via QUANTCDN_TIMEOUT_SECONDS environment variable.
     */
    timeoutSeconds?: pulumi.Input<number>;
}

export namespace Provider {
    /**
     * The results of the Provider.terraformConfig method.
     */
    export interface TerraformConfigResult {
        readonly result: {[key: string]: any};
    }

}
